package com.palmnote.data.db.migration

import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase
import com.palmnote.data.db.createBillTriggers

/**
 * v6 → v7：删除 `bills` / `bills_recycle_bin` 表中从未被 UI 使用的 `timeOfDay` 死字段。
 *
 * 标准 Room 重建表模式：新建无该列的表 → 按列搬运数据 → 删旧表 → 重命名 → 重建索引与触发器。
 * 历史 SQL 数据迁移保持冻结，不做改写。
 */
val MIGRATION_6_7 = object : Migration(6, 7) {
    override fun migrate(db: SupportSQLiteDatabase) {
        rebuildBillsTable(db)
        rebuildBillsRecycleBinTable(db)
        recreateBillsTriggers(db)
    }

    private fun rebuildBillsTable(db: SupportSQLiteDatabase) {
        db.execSQL(
            """
            |CREATE TABLE IF NOT EXISTS `new_bills`
            |(`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
            |`amount` INTEGER NOT NULL, `type` TEXT NOT NULL,
            |`category` TEXT NOT NULL, `subCategory` TEXT NOT NULL,
            |`note` TEXT NOT NULL, `date` INTEGER NOT NULL,
            |`yearMonth` TEXT NOT NULL, `accountBookId` INTEGER NOT NULL,
            |`walletId` INTEGER, `toWalletId` INTEGER,
            |`paymentMethod` TEXT NOT NULL, `merchant` TEXT NOT NULL,
            |`transactionId` TEXT NOT NULL, `location` TEXT NOT NULL,
            |`tags` TEXT NOT NULL, `images` TEXT NOT NULL,
            |`linkedAssetId` INTEGER, `linkType` TEXT,
            |`recurringId` INTEGER, `recurringFrequency` TEXT NOT NULL,
            |`splitGroupId` TEXT NOT NULL, `isReimbursable` INTEGER NOT NULL,
            |`isReimbursed` INTEGER NOT NULL, `reimbursedDate` INTEGER,
            |`isTaxDeductible` INTEGER NOT NULL, `latitude` REAL,
            |`longitude` REAL, `isAutoGenerated` INTEGER NOT NULL,
            |`createdAt` INTEGER NOT NULL, `updatedAt` INTEGER NOT NULL)
            """.trimMargin()
        )
        db.execSQL(
            """
            |INSERT INTO new_bills
            |(`id`,`amount`,`type`,`category`,`subCategory`,`note`,
            |`date`,`yearMonth`,`accountBookId`,`walletId`,`toWalletId`,
            |`paymentMethod`,`merchant`,`transactionId`,`location`,
            |`tags`,`images`,`linkedAssetId`,`linkType`,`recurringId`,
            |`recurringFrequency`,`splitGroupId`,`isReimbursable`,
            |`isReimbursed`,`reimbursedDate`,`isTaxDeductible`,
            |`latitude`,`longitude`,`isAutoGenerated`,`createdAt`,
            |`updatedAt`)
            |SELECT
            |`id`,`amount`,`type`,`category`,`subCategory`,`note`,
            |`date`,`yearMonth`,`accountBookId`,`walletId`,`toWalletId`,
            |`paymentMethod`,`merchant`,`transactionId`,`location`,
            |`tags`,`images`,`linkedAssetId`,`linkType`,`recurringId`,
            |`recurringFrequency`,`splitGroupId`,`isReimbursable`,
            |`isReimbursed`,`reimbursedDate`,`isTaxDeductible`,
            |`latitude`,`longitude`,`isAutoGenerated`,`createdAt`,
            |`updatedAt` FROM bills
            """.trimMargin()
        )
        db.execSQL("DROP TABLE bills")
        db.execSQL("ALTER TABLE new_bills RENAME TO bills")
        createBillsIndices(db)
    }

    private fun createBillsIndices(db: SupportSQLiteDatabase) {
        val indices = listOf(
            "index_bills_yearMonth_type" to "(`yearMonth`, `type`)",
            "index_bills_accountBookId_yearMonth" to "(`accountBookId`, `yearMonth`)",
            "index_bills_type" to "(`type`)",
            "index_bills_date" to "(`date`)",
            "index_bills_isReimbursable_isReimbursed" to
                "(`isReimbursable`, `isReimbursed`)",
            "index_bills_recurringId" to "(`recurringId`)",
            "index_bills_category" to "(`category`)"
        )
        for ((name, columns) in indices) {
            db.execSQL(
                "CREATE INDEX IF NOT EXISTS `$name` ON `bills` $columns"
            )
        }
    }

    private fun rebuildBillsRecycleBinTable(db: SupportSQLiteDatabase) {
        db.execSQL(
            """
            |CREATE TABLE IF NOT EXISTS `new_bills_recycle_bin`
            |(`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
            |`originalId` INTEGER NOT NULL, `amount` INTEGER NOT NULL,
            |`type` TEXT NOT NULL, `category` TEXT NOT NULL,
            |`subCategory` TEXT NOT NULL, `note` TEXT NOT NULL,
            |`date` INTEGER NOT NULL, `yearMonth` TEXT NOT NULL,
            |`accountBookId` INTEGER NOT NULL, `walletId` INTEGER,
            |`toWalletId` INTEGER, `paymentMethod` TEXT NOT NULL,
            |`merchant` TEXT NOT NULL, `transactionId` TEXT NOT NULL,
            |`location` TEXT NOT NULL, `tags` TEXT NOT NULL,
            |`images` TEXT NOT NULL, `linkedAssetId` INTEGER,
            |`linkType` TEXT, `recurringId` INTEGER,
            |`recurringFrequency` TEXT NOT NULL,
            |`splitGroupId` TEXT NOT NULL, `isReimbursable` INTEGER NOT NULL,
            |`isReimbursed` INTEGER NOT NULL, `reimbursedDate` INTEGER,
            |`isTaxDeductible` INTEGER NOT NULL, `latitude` REAL,
            |`longitude` REAL, `isAutoGenerated` INTEGER NOT NULL,
            |`createdAt` INTEGER NOT NULL, `updatedAt` INTEGER NOT NULL,
            |`deletedAt` INTEGER NOT NULL)
            """.trimMargin()
        )
        db.execSQL(
            """
            |INSERT INTO new_bills_recycle_bin
            |(`id`,`originalId`,`amount`,`type`,`category`,`subCategory`,
            |`note`,`date`,`yearMonth`,`accountBookId`,`walletId`,
            |`toWalletId`,`paymentMethod`,`merchant`,`transactionId`,
            |`location`,`tags`,`images`,`linkedAssetId`,`linkType`,
            |`recurringId`,`recurringFrequency`,`splitGroupId`,
            |`isReimbursable`,`isReimbursed`,`reimbursedDate`,
            |`isTaxDeductible`,`latitude`,`longitude`,
            |`isAutoGenerated`,`createdAt`,`updatedAt`,`deletedAt`)
            |SELECT
            |`id`,`originalId`,`amount`,`type`,`category`,`subCategory`,
            |`note`,`date`,`yearMonth`,`accountBookId`,`walletId`,
            |`toWalletId`,`paymentMethod`,`merchant`,`transactionId`,
            |`location`,`tags`,`images`,`linkedAssetId`,`linkType`,
            |`recurringId`,`recurringFrequency`,`splitGroupId`,
            |`isReimbursable`,`isReimbursed`,`reimbursedDate`,
            |`isTaxDeductible`,`latitude`,`longitude`,
            |`isAutoGenerated`,`createdAt`,`updatedAt`,`deletedAt`
            |FROM bills_recycle_bin
            """.trimMargin()
        )
        db.execSQL("DROP TABLE bills_recycle_bin")
        db.execSQL(
            "ALTER TABLE new_bills_recycle_bin RENAME TO bills_recycle_bin"
        )
    }

    private fun recreateBillsTriggers(db: SupportSQLiteDatabase) {
        // DROP TABLE bills 会连带删除其上的触发器，需重建以保持 v6 行为一致。
        createBillTriggers(db)
    }
}
