package com.palmnote.data.db.migration

import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase

/**
 * v3 → v4：金额单位从「元(Double)」迁移为「分(Long)」。
 * SQLite 无法直接修改列类型，因此对涉及金额的表执行 重建表 → 数据×100 → 改名 流程。
 */
val MIGRATION_3_4 = object : Migration(3, 4) {
    override fun migrate(db: SupportSQLiteDatabase) {
        migrateBills(db)
        migrateRecurringTemplates(db)
        migrateWallets(db)
        migrateBudgets(db)
        migrateAssets(db)
        migratePlanListItems(db)
    }

    private fun migrateBills(db: SupportSQLiteDatabase) {
        db.execSQL(
            """CREATE TABLE IF NOT EXISTS bills_new (
                id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                amount INTEGER NOT NULL,
                type TEXT NOT NULL,
                category TEXT NOT NULL,
                subCategory TEXT NOT NULL,
                note TEXT NOT NULL,
                date INTEGER NOT NULL,
                yearMonth TEXT NOT NULL,
                timeOfDay TEXT NOT NULL,
                accountBookId INTEGER NOT NULL,
                walletId INTEGER,
                toWalletId INTEGER,
                paymentMethod TEXT NOT NULL,
                merchant TEXT NOT NULL,
                transactionId TEXT NOT NULL,
                location TEXT NOT NULL,
                tags TEXT NOT NULL,
                images TEXT NOT NULL,
                linkedAssetId INTEGER,
                linkType TEXT,
                recurringId INTEGER,
                recurringFrequency TEXT NOT NULL,
                splitGroupId TEXT NOT NULL,
                isReimbursable INTEGER NOT NULL,
                isReimbursed INTEGER NOT NULL,
                reimbursedDate INTEGER,
                isTaxDeductible INTEGER NOT NULL,
                latitude REAL,
                longitude REAL,
                isAutoGenerated INTEGER NOT NULL,
                isDeleted INTEGER NOT NULL,
                deletedAt INTEGER,
                createdAt INTEGER NOT NULL,
                updatedAt INTEGER NOT NULL
            )"""
        )
        db.execSQL(
            """INSERT INTO bills_new (
                id, amount, type, category, subCategory, note, date, yearMonth, timeOfDay,
                accountBookId, walletId, toWalletId, paymentMethod, merchant, transactionId,
                location, tags, images, linkedAssetId, linkType, recurringId, recurringFrequency,
                splitGroupId, isReimbursable, isReimbursed, reimbursedDate, isTaxDeductible,
                latitude, longitude, isAutoGenerated, isDeleted, deletedAt, createdAt, updatedAt
            ) SELECT
                id, CAST(ROUND(amount * 100) AS INTEGER), type, category, subCategory, note, date,
                yearMonth, timeOfDay, accountBookId, walletId, toWalletId, paymentMethod, merchant,
                transactionId, location, tags, images, linkedAssetId, linkType, recurringId,
                recurringFrequency, splitGroupId, isReimbursable, isReimbursed, reimbursedDate,
                isTaxDeductible, latitude, longitude, isAutoGenerated, isDeleted, deletedAt,
                createdAt, updatedAt
            FROM bills"""
        )
        db.execSQL("DROP TABLE bills")
        db.execSQL("ALTER TABLE bills_new RENAME TO bills")
        recreateBillsIndices(db)
    }

    private fun recreateBillsIndices(db: SupportSQLiteDatabase) {
        db.execSQL("CREATE INDEX IF NOT EXISTS index_bills_yearMonth_type_isDeleted ON bills(yearMonth, type, isDeleted)")
        db.execSQL("CREATE INDEX IF NOT EXISTS index_bills_accountBookId_yearMonth_isDeleted ON bills(accountBookId, yearMonth, isDeleted)")
        db.execSQL("CREATE INDEX IF NOT EXISTS index_bills_type_isDeleted ON bills(type, isDeleted)")
        db.execSQL("CREATE INDEX IF NOT EXISTS index_bills_date_isDeleted ON bills(date, isDeleted)")
        db.execSQL("CREATE INDEX IF NOT EXISTS index_bills_isReimbursable_isReimbursed_isDeleted ON bills(isReimbursable, isReimbursed, isDeleted)")
        db.execSQL("CREATE INDEX IF NOT EXISTS index_bills_recurringId_isDeleted ON bills(recurringId, isDeleted)")
        db.execSQL("CREATE INDEX IF NOT EXISTS index_bills_category_isDeleted ON bills(category, isDeleted)")
    }

    private fun migrateRecurringTemplates(db: SupportSQLiteDatabase) {
        db.execSQL(
            """CREATE TABLE IF NOT EXISTS recurring_templates_new (
                id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                name TEXT NOT NULL,
                amount INTEGER NOT NULL,
                type TEXT NOT NULL,
                category TEXT NOT NULL,
                frequency TEXT NOT NULL,
                dayOfMonth INTEGER NOT NULL,
                dayOfWeek INTEGER NOT NULL,
                isActive INTEGER NOT NULL,
                lastGeneratedDate INTEGER,
                nextGenerateDate INTEGER,
                autoGenerate INTEGER NOT NULL,
                remindBeforeDays INTEGER NOT NULL,
                note TEXT NOT NULL,
                isDeleted INTEGER NOT NULL,
                createdAt INTEGER NOT NULL,
                updatedAt INTEGER NOT NULL
            )"""
        )
        db.execSQL(
            """INSERT INTO recurring_templates_new (
                id, name, amount, type, category, frequency, dayOfMonth, dayOfWeek, isActive,
                lastGeneratedDate, nextGenerateDate, autoGenerate, remindBeforeDays, note,
                isDeleted, createdAt, updatedAt
            ) SELECT
                id, name, CAST(ROUND(amount * 100) AS INTEGER), type, category, frequency,
                dayOfMonth, dayOfWeek, isActive, lastGeneratedDate, nextGenerateDate,
                autoGenerate, remindBeforeDays, note, isDeleted, createdAt, updatedAt
            FROM recurring_templates"""
        )
        db.execSQL("DROP TABLE recurring_templates")
        db.execSQL("ALTER TABLE recurring_templates_new RENAME TO recurring_templates")
    }

    private fun migrateWallets(db: SupportSQLiteDatabase) {
        db.execSQL(
            """CREATE TABLE IF NOT EXISTS wallets_new (
                id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                name TEXT NOT NULL,
                type TEXT NOT NULL,
                icon TEXT NOT NULL DEFAULT 'Payments',
                color TEXT NOT NULL,
                bankName TEXT NOT NULL,
                cardNumber TEXT NOT NULL,
                initialBalance INTEGER NOT NULL,
                currentBalance INTEGER NOT NULL,
                currency TEXT NOT NULL,
                isDefault INTEGER NOT NULL,
                isEnabled INTEGER NOT NULL,
                sortOrder INTEGER NOT NULL,
                description TEXT NOT NULL,
                isDeleted INTEGER NOT NULL,
                createdAt INTEGER NOT NULL,
                updatedAt INTEGER NOT NULL
            )"""
        )
        db.execSQL(
            """INSERT INTO wallets_new (
                id, name, type, icon, color, bankName, cardNumber, initialBalance, currentBalance,
                currency, isDefault, isEnabled, sortOrder, description, isDeleted, createdAt, updatedAt
            ) SELECT
                id, name, type, icon, color, bankName, cardNumber,
                CAST(ROUND(initialBalance * 100) AS INTEGER),
                CAST(ROUND(currentBalance * 100) AS INTEGER),
                currency, isDefault, isEnabled, sortOrder, description, isDeleted, createdAt, updatedAt
            FROM wallets"""
        )
        db.execSQL("DROP TABLE wallets")
        db.execSQL("ALTER TABLE wallets_new RENAME TO wallets")
    }

    private fun migrateBudgets(db: SupportSQLiteDatabase) {
        db.execSQL(
            """CREATE TABLE IF NOT EXISTS budgets_new (
                id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                yearMonth TEXT NOT NULL,
                totalBudget INTEGER NOT NULL,
                reminderThreshold REAL NOT NULL,
                reminderAtThreshold INTEGER NOT NULL,
                reminderOverBudget INTEGER NOT NULL,
                createdAt INTEGER NOT NULL,
                updatedAt INTEGER NOT NULL
            )"""
        )
        db.execSQL(
            """INSERT INTO budgets_new (
                id, yearMonth, totalBudget, reminderThreshold, reminderAtThreshold,
                reminderOverBudget, createdAt, updatedAt
            ) SELECT
                id, yearMonth, CAST(ROUND(totalBudget * 100) AS INTEGER), reminderThreshold,
                reminderAtThreshold, reminderOverBudget, createdAt, updatedAt
            FROM budgets"""
        )
        db.execSQL("DROP TABLE budgets")
        db.execSQL("ALTER TABLE budgets_new RENAME TO budgets")
    }

    private fun migrateAssets(db: SupportSQLiteDatabase) {
        db.execSQL(
            """CREATE TABLE IF NOT EXISTS assets_new (
                id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                name TEXT NOT NULL,
                category TEXT NOT NULL,
                subCategory TEXT NOT NULL,
                brand TEXT NOT NULL,
                model TEXT NOT NULL,
                purchasePrice INTEGER NOT NULL,
                acquisitionType TEXT NOT NULL,
                acquisitionDate INTEGER,
                status TEXT NOT NULL,
                costMode TEXT NOT NULL,
                quantity INTEGER NOT NULL,
                useCount INTEGER NOT NULL,
                totalUsageHours REAL NOT NULL,
                location TEXT NOT NULL,
                room TEXT NOT NULL,
                purchaseChannel TEXT NOT NULL,
                warrantyExpireDate INTEGER,
                insuranceExpireDate INTEGER,
                insuranceCompany TEXT NOT NULL,
                insurancePolicyNo TEXT NOT NULL,
                images TEXT NOT NULL,
                description TEXT NOT NULL,
                condition TEXT NOT NULL,
                serialNumber TEXT NOT NULL,
                receiptPath TEXT NOT NULL,
                depreciationRate REAL NOT NULL,
                currentValue INTEGER NOT NULL,
                maintenanceIntervalDays INTEGER NOT NULL,
                lastMaintenanceDate INTEGER,
                nextMaintenanceDate INTEGER,
                maintenanceNotes TEXT NOT NULL,
                isFavorite INTEGER NOT NULL,
                tags TEXT NOT NULL,
                linkedBillId INTEGER,
                linkedMomentId INTEGER,
                retireDate INTEGER,
                retireReason TEXT NOT NULL,
                lostDate INTEGER,
                lostReason TEXT NOT NULL,
                soldDate INTEGER,
                soldPrice INTEGER,
                soldChannel TEXT,
                soldToWhom TEXT,
                sortOrder INTEGER NOT NULL,
                isDeleted INTEGER NOT NULL,
                deletedAt INTEGER,
                createdAt INTEGER NOT NULL,
                updatedAt INTEGER NOT NULL
            )"""
        )
        db.execSQL(
            """INSERT INTO assets_new (
                id, name, category, subCategory, brand, model, purchasePrice, acquisitionType,
                acquisitionDate, status, costMode, quantity, useCount, totalUsageHours, location,
                room, purchaseChannel, warrantyExpireDate, insuranceExpireDate, insuranceCompany,
                insurancePolicyNo, images, description, condition, serialNumber, receiptPath,
                depreciationRate, currentValue, maintenanceIntervalDays, lastMaintenanceDate,
                nextMaintenanceDate, maintenanceNotes, isFavorite, tags, linkedBillId,
                linkedMomentId, retireDate, retireReason, lostDate, lostReason, soldDate,
                soldPrice, soldChannel, soldToWhom, sortOrder, isDeleted, deletedAt, createdAt, updatedAt
            ) SELECT
                id, name, category, subCategory, brand, model,
                CAST(ROUND(purchasePrice * 100) AS INTEGER), acquisitionType, acquisitionDate,
                status, costMode, quantity, useCount, totalUsageHours, location, room,
                purchaseChannel, warrantyExpireDate, insuranceExpireDate, insuranceCompany,
                insurancePolicyNo, images, description, condition, serialNumber, receiptPath,
                depreciationRate, CAST(ROUND(currentValue * 100) AS INTEGER),
                maintenanceIntervalDays, lastMaintenanceDate, nextMaintenanceDate,
                maintenanceNotes, isFavorite, tags, linkedBillId, linkedMomentId, retireDate,
                retireReason, lostDate, lostReason, soldDate,
                CAST(ROUND(soldPrice * 100) AS INTEGER), soldChannel, soldToWhom, sortOrder,
                isDeleted, deletedAt, createdAt, updatedAt
            FROM assets"""
        )
        db.execSQL("DROP TABLE assets")
        db.execSQL("ALTER TABLE assets_new RENAME TO assets")
        recreateAssetsIndices(db)
    }

    private fun recreateAssetsIndices(db: SupportSQLiteDatabase) {
        db.execSQL("CREATE INDEX IF NOT EXISTS index_assets_status_isDeleted ON assets(status, isDeleted)")
        db.execSQL("CREATE INDEX IF NOT EXISTS index_assets_category_isDeleted ON assets(category, isDeleted)")
        db.execSQL("CREATE INDEX IF NOT EXISTS index_assets_warrantyExpireDate_isDeleted ON assets(warrantyExpireDate, isDeleted)")
        db.execSQL("CREATE INDEX IF NOT EXISTS index_assets_nextMaintenanceDate_isDeleted ON assets(nextMaintenanceDate, isDeleted)")
        db.execSQL("CREATE INDEX IF NOT EXISTS index_assets_insuranceExpireDate_isDeleted ON assets(insuranceExpireDate, isDeleted)")
        db.execSQL("CREATE INDEX IF NOT EXISTS index_assets_isFavorite_isDeleted ON assets(isFavorite, isDeleted)")
    }

    private fun migratePlanListItems(db: SupportSQLiteDatabase) {
        db.execSQL(
            """CREATE TABLE IF NOT EXISTS plan_list_items_new (
                id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
                listId INTEGER NOT NULL,
                content TEXT NOT NULL,
                quantity INTEGER NOT NULL,
                unitPrice INTEGER,
                notes TEXT NOT NULL,
                isCompleted INTEGER NOT NULL,
                sortOrder INTEGER NOT NULL,
                createdAt INTEGER NOT NULL,
                updatedAt INTEGER NOT NULL,
                FOREIGN KEY(listId) REFERENCES plan_lists(id) ON UPDATE NO ACTION ON DELETE CASCADE
            )"""
        )
        db.execSQL(
            """INSERT INTO plan_list_items_new (
                id, listId, content, quantity, unitPrice, notes, isCompleted, sortOrder,
                createdAt, updatedAt
            ) SELECT
                id, listId, content, quantity, CAST(ROUND(unitPrice * 100) AS INTEGER),
                notes, isCompleted, sortOrder, createdAt, updatedAt
            FROM plan_list_items"""
        )
        db.execSQL("DROP TABLE plan_list_items")
        db.execSQL("ALTER TABLE plan_list_items_new RENAME TO plan_list_items")
        db.execSQL("CREATE INDEX IF NOT EXISTS index_plan_list_items_listId ON plan_list_items(listId)")
    }
}
