package com.palmnote.data.db.entity

import androidx.compose.runtime.Immutable
import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey
import com.palmnote.domain.model.BillType
import com.palmnote.domain.model.PaymentMethod
import com.palmnote.domain.model.RecurringFrequency

@Entity(
    tableName = "bills",
    indices = [
        Index(value = ["yearMonth", "type"]),
        Index(value = ["accountBookId", "yearMonth"]),
        Index(value = ["type"]),
        Index(value = ["date"]),
        Index(value = ["isReimbursable", "isReimbursed"]),
        Index(value = ["reimbursedByBillId"]),
        Index(value = ["recurringId"]),
        Index(value = ["category"])
    ]
)
@Immutable
data class Bill(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val amount: Long, // 金额（分）
    val type: BillType, // EXPENSE, INCOME, TRANSFER
    val category: String,
    val subCategory: String = "", // 子分类
    val note: String = "",
    val date: Long, // timestamp
    val yearMonth: String, // "2024-01"
    val accountBookId: Long = 1, // 关联的账本ID，默认1（默认账本）
    val walletId: Long? = null, // 关联的钱包/账户ID
    val toWalletId: Long? = null, // 转账目标账户（仅TRANSFER类型）
    val paymentMethod: PaymentMethod = PaymentMethod.OTHER, // CASH, WECHAT, ALIPAY, CARD, BANK_TRANSFER, OTHER
    val merchant: String = "", // 商家/商户
    val transactionId: String = "", // 交易单号（导入来源）
    val location: String = "", // 消费地点
    val tags: String = "", // JSON array of tags
    val images: String = "", // 发票/小票照片
    val linkedAssetId: Long? = null,
    val linkType: String? = null, // 保持 String（LinkType 枚举用于 CrossLink）
    val recurringId: Long? = null, // 关联的周期性模板ID
    val recurringFrequency: RecurringFrequency = RecurringFrequency.MONTHLY, // DAILY, WEEKLY, MONTHLY, YEARLY
    val splitGroupId: String = "", // 拆分组ID
    val isReimbursable: Boolean = false, // 是否可报销
    val isReimbursed: Boolean = false, // 是否已报销（= reimbursedAmount >= amount，由报销操作统一写入）
    val reimbursedDate: Long? = null, // 最近一次报销日期
    /**
     * 累计已报销金额（分）。支持部分报销：0 表示未报，>= amount 表示报完。
     * 与 [isReimbursed] 由同一处写入保证一致，不要单独改其中一个。
     */
    @ColumnInfo(defaultValue = "0")
    val reimbursedAmount: Long = 0,
    /**
     * 关联的报销收入账单 id（收入侧不存字段，一笔收入覆盖多条支出靠这里反查）。
     * 报销收入被删除时会被清空，不保留悬空引用。
     */
    val reimbursedByBillId: Long? = null,
    val isTaxDeductible: Boolean = false, // 是否可抵税
    val latitude: Double? = null, // GPS纬度
    val longitude: Double? = null, // GPS经度
    val isAutoGenerated: Boolean = false,
    /**
     * 演示数据标记（v14）：示例账本 / 示例钱包 / 示例账单 / 示例物品。
     * 演示模式关闭时按此列整批物理删除；CSV 导出排除（示例不进「我的数据」）。
     */
    @ColumnInfo(defaultValue = "0")
    val isDemo: Boolean = false,
    val createdAt: Long = System.currentTimeMillis(),

    val updatedAt: Long = System.currentTimeMillis()
)

@Entity(tableName = "recurring_templates")
@Immutable
data class RecurringTemplate(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val name: String, // 模板名称，如"房租"、"工资"
    val amount: Long, // 金额（分）
    val type: BillType, // EXPENSE, INCOME
    val category: String,
    val frequency: RecurringFrequency, // DAILY, WEEKLY, MONTHLY, YEARLY
    val dayOfMonth: Int = 0, // 每月几号 (MONTHLY时)
    val dayOfWeek: Int = 0, // 周几 (WEEKLY时, 1=周一)
    val isActive: Boolean = true,
    val lastGeneratedDate: Long? = null,
    val nextGenerateDate: Long? = null,
    val autoGenerate: Boolean = true, // 自动生成账单
    val remindBeforeDays: Int = 1, // 提前提醒天数
    val note: String = "",
    val createdAt: Long = System.currentTimeMillis(),
    val updatedAt: Long = System.currentTimeMillis()
)
