package com.palmnote.data.repository

import com.palmnote.data.db.dao.BillDao
import com.palmnote.data.db.entity.Bill
import com.palmnote.domain.model.BillType
import com.palmnote.domain.model.PaymentMethod
import com.palmnote.domain.model.RecurringFrequency
import io.mockk.coEvery
import io.mockk.coVerify
import io.mockk.mockk
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.flow.flowOf
import kotlinx.coroutines.test.runTest
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Before
import org.junit.Test

class BillRepositoryTest {

    private lateinit var billDao: BillDao
    private lateinit var billRepository: BillRepositoryImpl

    @Before
    fun setUp() {
        billDao = mockk(relaxUnitFun = true)
        billRepository = BillRepositoryImpl(billDao, mockk(), mockk(), mockk())
    }

    @Test
    fun `insertBill returns bill id`() = runTest {
        val bill = createTestBill()
        coEvery { billDao.insertBill(bill) } returns 1L

        val result = billRepository.insertBill(bill)

        assertEquals(1L, result)
        coVerify { billDao.insertBill(bill) }
    }

    @Test
    fun `getBillById returns bill when exists`() = runTest {
        val bill = createTestBill(id = 1L)
        coEvery { billDao.getBillById(1L) } returns bill

        val result = billRepository.getBillById(1L)

        assertNotNull(result)
        assertEquals(1L, result?.id)
        assertEquals("餐饮", result?.category)
    }

    @Test
    fun `getBillById returns null when not exists`() = runTest {
        coEvery { billDao.getBillById(999L) } returns null

        val result = billRepository.getBillById(999L)

        assertEquals(null, result)
    }

    @Test
    fun `getBillsByMonth returns bills for given month`() = runTest {
        val bills = listOf(
            createTestBill(id = 1L, amount = 5000),
            createTestBill(id = 2L, amount = 3000)
        )
        coEvery { billDao.getBillsByMonth("2026-07") } returns flowOf(bills)

        val result = billRepository.getBillsByMonth("2026-07").first()

        assertEquals(2, result.size)
        assertEquals(5000L, result[0].amount)
    }

    @Test
    fun `updateBill calls dao`() = runTest {
        val bill = createTestBill(id = 1L, amount = 10000)
        coEvery { billDao.updateBill(bill) } returns Unit

        billRepository.updateBill(bill)

        coVerify { billDao.updateBill(bill) }
    }

    private fun createTestBill(
        id: Long = 0L,
        amount: Long = 5000,
        type: BillType = BillType.EXPENSE,
        category: String = "餐饮",
        merchant: String = ""
    ) = Bill(
        id = id,
        amount = amount,
        type = type,
        category = category,
        subCategory = "",
        note = "",
        date = System.currentTimeMillis(),
        yearMonth = "2026-07",
        walletId = 1L,
        toWalletId = null,
        paymentMethod = PaymentMethod.OTHER,
        merchant = merchant,
        location = "",
        tags = "",
        images = "",
        linkedAssetId = null,
        linkType = null,
        recurringId = null,
        recurringFrequency = RecurringFrequency.MONTHLY,
        splitGroupId = "",
        isReimbursable = false,
        isReimbursed = false,
        reimbursedDate = null,
        isTaxDeductible = false,
        latitude = null,
        longitude = null,
        isAutoGenerated = false,
        createdAt = System.currentTimeMillis(),
        updatedAt = System.currentTimeMillis()
    )
}
