package com.palmnote.data.db.migration

import android.app.Application
import androidx.room.testing.MigrationTestHelper
import androidx.sqlite.db.SupportSQLiteDatabase
import androidx.sqlite.db.framework.FrameworkSQLiteOpenHelperFactory
import androidx.test.platform.app.InstrumentationRegistry
import com.palmnote.data.db.AppDatabase
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config

@RunWith(RobolectricTestRunner::class)
@Config(sdk = [30], application = Application::class)
class Migration6To7Test {

    @get:Rule
    val helper = MigrationTestHelper(
        InstrumentationRegistry.getInstrumentation(),
        AppDatabase::class.java,
        emptyList(),
        FrameworkSQLiteOpenHelperFactory()
    )

    private companion object {
        const val DB = "migration-6-to-7"
        const val DB_DATA = "migration-6-to-7-data"
    }

    @Test
    fun migrate6To7_validatesFullSchema() {
        helper.createDatabase(DB, 6).close()
        val migrated = helper.runMigrationsAndValidate(
            DB, 7, true, MIGRATION_6_7
        )
        assertTable(migrated, "bills")
        assertTable(migrated, "bills_recycle_bin")
        migrated.close()
    }

    @Test
    fun migrate6To7_preservesDataAndDropsTimeOfDay() {
        seedV6Bills()
        val migrated = helper.runMigrationsAndValidate(
            DB_DATA, 7, true, MIGRATION_6_7
        )
        assertBillRow(migrated)
        assertRecycleBinRow(migrated)
        assertColumnAbsent(migrated, "bills")
        assertColumnAbsent(migrated, "bills_recycle_bin")
        migrated.close()
    }

    @Test
    fun migrate6To7_recreatesBillsTriggers() {
        val db = helper.createDatabase(DB, 6)
        db.execSQL(
            "CREATE TRIGGER IF NOT EXISTS auto_yearmonth_insert " +
            "AFTER INSERT ON bills BEGIN " +
            "UPDATE bills SET yearMonth='2026-01' " +
            "WHERE id=NEW.id; END"
        )
        db.execSQL(
            "CREATE TRIGGER IF NOT EXISTS bills_fts_ai " +
            "AFTER INSERT ON bills BEGIN " +
            "INSERT INTO bills_fts(rowid,note,merchant,tags) " +
            "VALUES(new.id,new.note,new.merchant,new.tags); END"
        )
        db.close()
        val migrated = helper.runMigrationsAndValidate(
            DB, 7, true, MIGRATION_6_7
        )
        assertTrigger(migrated, "auto_yearmonth_insert")
        assertTrigger(migrated, "auto_yearmonth_update")
        assertTrigger(migrated, "bills_fts_ai")
        assertTrigger(migrated, "bills_fts_ad")
        assertTrigger(migrated, "bills_fts_au")
        // 注：Robolectric 的 SQLite 不加载 fts5 模块，无法在此环境验证 bills_fts 联动；
        // 触发器存在性已通过 sqlite_master 断言覆盖。
        migrated.close()
    }

    private fun seedV6Bills() {
        val db = helper.createDatabase(DB_DATA, 6)
        db.execSQL(
            "INSERT INTO bills " +
            "(id,amount,type,category,subCategory,note,date," +
            "yearMonth,timeOfDay,accountBookId,walletId," +
            "toWalletId,paymentMethod,merchant,transactionId," +
            "location,tags,images,linkedAssetId,linkType," +
            "recurringId,recurringFrequency,splitGroupId," +
            "isReimbursable,isReimbursed,reimbursedDate," +
            "isTaxDeductible,latitude,longitude," +
            "isAutoGenerated,createdAt,updatedAt) " +
            "VALUES(1,1000,'EXPENSE','food','', 'note',1," +
            "'2026-01','MORNING',1,1,NULL,'CASH','','',''," +
            "'','',NULL,NULL,NULL,'','',0,0,NULL,0,NULL," +
            "NULL,0,1,1)"
        )
        db.execSQL(
            "INSERT INTO bills_recycle_bin " +
            "(id,originalId,amount,type,category,subCategory," +
            "note,date,yearMonth,timeOfDay,accountBookId," +
            "walletId,toWalletId,paymentMethod,merchant," +
            "transactionId,location,tags,images,linkedAssetId," +
            "linkType,recurringId,recurringFrequency," +
            "splitGroupId,isReimbursable,isReimbursed," +
            "reimbursedDate,isTaxDeductible,latitude,longitude," +
            "isAutoGenerated,createdAt,updatedAt,deletedAt) " +
            "VALUES(1,2,500,'EXPENSE','transport','', 'old',2," +
            "'2026-01','NIGHT',1,NULL,NULL,'CASH','','',''," +
            "'','',NULL,NULL,NULL,'','',0,0,NULL,0,NULL," +
            "NULL,0,1,1,3)"
        )
        db.close()
    }

    private fun assertBillRow(db: SupportSQLiteDatabase) {
        db.query(
            "SELECT amount,type,note,yearMonth,walletId,images " +
            "FROM bills WHERE id=1"
        ).use { c ->
            assertTrue(c.moveToFirst())
            assertEquals(1000, c.getInt(0))
            assertEquals("EXPENSE", c.getString(1))
            assertEquals("note", c.getString(2))
            assertEquals("2026-01", c.getString(3))
            assertEquals(1, c.getInt(4))
            assertEquals("", c.getString(5))
        }
    }

    private fun assertRecycleBinRow(db: SupportSQLiteDatabase) {
        db.query(
            "SELECT amount,type,note,yearMonth,walletId,deletedAt " +
            "FROM bills_recycle_bin WHERE id=1"
        ).use { c ->
            assertTrue(c.moveToFirst())
            assertEquals(500, c.getInt(0))
            assertEquals("EXPENSE", c.getString(1))
            assertEquals("old", c.getString(2))
            assertEquals("2026-01", c.getString(3))
            assertEquals(null, c.getString(4))
            assertEquals(3, c.getInt(5))
        }
    }

    private fun assertColumnAbsent(
        db: SupportSQLiteDatabase, table: String
    ) {
        db.query("PRAGMA table_info($table)").use { c ->
            while (c.moveToNext()) {
                assertFalse("timeOfDay" == c.getString(1))
            }
        }
    }

    private fun assertTable(
        db: SupportSQLiteDatabase, table: String
    ) {
        db.query(
            "SELECT name FROM sqlite_master " +
            "WHERE type='table' AND name='$table'"
        ).use { c -> assertTrue(c.moveToFirst()) }
    }

    private fun assertTrigger(
        db: SupportSQLiteDatabase, name: String
    ) {
        db.query(
            "SELECT name FROM sqlite_master " +
            "WHERE type='trigger' AND name='$name'"
        ).use { c -> assertTrue(c.moveToFirst()) }
    }
}
