package com.palmnote.data.db.migration

import android.app.Application
import androidx.room.testing.MigrationTestHelper
import androidx.sqlite.db.framework.FrameworkSQLiteOpenHelperFactory
import androidx.test.platform.app.InstrumentationRegistry
import com.palmnote.data.db.AppDatabase
import org.junit.Assert.assertEquals
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config

/**
 * v3 → v4 金额单位迁移测试（元 REAL → 分 INTEGER，×100 换算）。
 * 通过 MigrationTestHelper 用导出的 3.json 构建 v3 库、插入 REAL 金额数据，
 * 跑迁移后校验 schema 与数据。用 Robolectric 本地 JVM 跑，无需模拟器。
 *
 * 注意：必须用无业务逻辑的 [Application]（而非合并清单里的 .PalmNoteApp），
 * 否则 Hilt 注入会触发 SQLCipher System.loadLibrary("sqlcipher")，在 JVM 上必败。
 */
@RunWith(RobolectricTestRunner::class)
@Config(sdk = [30], application = Application::class)
class Migration3To4Test {

    @get:Rule
    val helper = MigrationTestHelper(
        InstrumentationRegistry.getInstrumentation(),
        AppDatabase::class.java,
        emptyList(),
        FrameworkSQLiteOpenHelperFactory()
    )

    private companion object {
        const val DB = "migration-3-to-4"
        const val DB_DEFAULTS = "migration-3-to-4-defaults"
    }

    @Test
    fun migrate3To4_convertsAllMoneyColumnsToCents() {
        seedV3MoneyRows()

        val db = helper.runMigrationsAndValidate(DB, 4, true, MIGRATION_3_4)

        db.query("SELECT amount FROM bills").use { c ->
            c.moveToFirst(); assertEquals(1250L, c.getLong(0))
        }
        db.query("SELECT amount FROM recurring_templates").use { c ->
            c.moveToFirst(); assertEquals(300000L, c.getLong(0))
        }
        db.query("SELECT initialBalance, currentBalance FROM wallets").use { c ->
            c.moveToFirst()
            assertEquals(10000L, c.getLong(0))
            assertEquals(15050L, c.getLong(1))
        }
        db.query("SELECT totalBudget FROM budgets").use { c ->
            c.moveToFirst(); assertEquals(200000L, c.getLong(0))
        }
        db.query("SELECT purchasePrice, currentValue FROM assets").use { c ->
            c.moveToFirst()
            assertEquals(500000L, c.getLong(0))
            assertEquals(0L, c.getLong(1))
        }
        db.query("SELECT unitPrice FROM plan_list_items").use { c ->
            c.moveToFirst(); assertEquals(1050L, c.getLong(0))
        }
        db.close()
    }

    private fun seedV3MoneyRows() {
        helper.createDatabase(DB, 3).apply {
            execSQL(
                "INSERT INTO bills (amount, type, category, subCategory, note, date, yearMonth, " +
                    "timeOfDay, accountBookId, paymentMethod, merchant, transactionId, location, " +
                    "tags, images, recurringFrequency, splitGroupId, isReimbursable, isReimbursed, " +
                    "isTaxDeductible, isAutoGenerated, isDeleted, createdAt, updatedAt) VALUES " +
                    "(12.5, 'EXPENSE', '餐饮', '', '', 1750000000000, '2026-07', '', 1, '', '', '', '', '', '', '', '', 0, 0, 0, 0, 0, 1, 1)"
            )
            execSQL(
                "INSERT INTO recurring_templates (name, amount, type, category, frequency, " +
                    "dayOfMonth, dayOfWeek, isActive, autoGenerate, remindBeforeDays, note, " +
                    "isDeleted, createdAt, updatedAt) VALUES " +
                    "('房租', 3000.0, 'EXPENSE', '居住', 'MONTHLY', 1, 0, 1, 1, 1, '', 0, 1, 1)"
            )
            execSQL(
                "INSERT INTO wallets (name, type, icon, color, bankName, cardNumber, " +
                    "initialBalance, currentBalance, currency, isDefault, isEnabled, sortOrder, " +
                    "description, isDeleted, createdAt, updatedAt) VALUES " +
                    "('现金', 'CASH', 'Payments', '#4CAF50', '', '', 100.0, 150.5, 'CNY', 1, 1, 0, '', 0, 1, 1)"
            )
            execSQL(
                "INSERT INTO budgets (yearMonth, totalBudget, reminderThreshold, " +
                    "reminderAtThreshold, reminderOverBudget, createdAt, updatedAt) VALUES " +
                    "('2026-07', 2000.0, 0.8, 1, 1, 1, 1)"
            )
            execSQL(
                "INSERT INTO assets (name, category, subCategory, brand, model, purchasePrice, " +
                    "acquisitionType, status, costMode, quantity, useCount, totalUsageHours, " +
                    "location, room, purchaseChannel, insuranceCompany, insurancePolicyNo, images, " +
                    "description, condition, serialNumber, receiptPath, depreciationRate, currentValue, " +
                    "maintenanceIntervalDays, maintenanceNotes, isFavorite, tags, retireReason, " +
                    "lostReason, sortOrder, isDeleted, createdAt, updatedAt) VALUES " +
                    "('手机', '数码', '', '', '', 5000.0, 'PURCHASE', 'HELD', 'DAILY', 1, 0, 0.0, " +
                    "'', '', '', '', '', '', '', 'GOOD', '', '', 0.0, 0.0, 0, '', 0, '', '', '', 0, 0, 1, 1)"
            )
            execSQL(
                "INSERT INTO plan_list_items (listId, content, quantity, unitPrice, notes, " +
                    "isCompleted, sortOrder, createdAt, updatedAt) VALUES " +
                    "(1, '购物车', 2, 10.5, '', 0, 0, 1, 1)"
            )
            close()
        }
    }

    @Test
    fun migrate3To4_keepsWalletsIconDefaultAndPlanListForeignKey() {
        helper.createDatabase(DB_DEFAULTS, 3).apply {
            execSQL(
                "INSERT INTO wallets (name, type, icon, color, bankName, cardNumber, " +
                    "initialBalance, currentBalance, currency, isDefault, isEnabled, sortOrder, " +
                    "description, isDeleted, createdAt, updatedAt) VALUES " +
                    "('现金', 'CASH', 'Payments', '#4CAF50', '', '', 0.0, 0.0, 'CNY', 1, 1, 0, '', 0, 1, 1)"
            )
            execSQL(
                "INSERT INTO plan_list_items (listId, content, quantity, unitPrice, notes, " +
                    "isCompleted, sortOrder, createdAt, updatedAt) VALUES " +
                    "(1, '项', 1, 1.0, '', 0, 0, 1, 1)"
            )
            close()
        }

        // runMigrationsAndValidate 会对 wallets 的 DEFAULT 'Payments' 与
        // plan_list_items 的外键做 schema 校验，不匹配即抛异常
        val db = helper.runMigrationsAndValidate(DB_DEFAULTS, 4, true, MIGRATION_3_4)

        db.query("SELECT sql FROM sqlite_master WHERE type='table' AND name='wallets'").use { c ->
            c.moveToFirst()
            org.junit.Assert.assertTrue(c.getString(0).contains("DEFAULT 'Payments'"))
        }
        db.query("SELECT sql FROM sqlite_master WHERE type='table' AND name='plan_list_items'").use { c ->
            c.moveToFirst()
            org.junit.Assert.assertTrue(c.getString(0).contains("REFERENCES plan_lists"))
        }
        db.close()
    }
}
