package com.palmnote.data.db.migration

import android.app.Application
import androidx.room.testing.MigrationTestHelper
import androidx.sqlite.db.framework.FrameworkSQLiteOpenHelperFactory
import androidx.test.platform.app.InstrumentationRegistry
import com.palmnote.data.db.AppDatabase
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config

@RunWith(RobolectricTestRunner::class)
@Config(sdk = [30], application = Application::class)
class Migration5To6Test {

    @get:Rule
    val helper = MigrationTestHelper(
        InstrumentationRegistry.getInstrumentation(),
        AppDatabase::class.java,
        emptyList(),
        FrameworkSQLiteOpenHelperFactory()
    )

    private companion object {
        const val DB = "migration-5-to-6"
        const val DB_DATA = "migration-5-to-6-data"
    }

    @Test
    fun migrate5To6_validatesFullSchema() {
        helper.createDatabase(DB, 5).close()

        val migrated = helper.runMigrationsAndValidate(DB, 6, true, MIGRATION_5_6)
        migrated.query(
            "SELECT name FROM sqlite_master WHERE type='table' AND name='bills_recycle_bin'"
        ).use { cursor -> assertTrue(cursor.moveToFirst()) }
        migrated.query(
            "SELECT name FROM sqlite_master WHERE type='table' AND name='assets_recycle_bin'"
        ).use { cursor -> assertTrue(cursor.moveToFirst()) }
        migrated.query(
            "SELECT name FROM sqlite_master WHERE type='table' AND name='vault_entries'"
        ).use { cursor -> assertFalse(cursor.moveToFirst()) }
        migrated.close()
    }

    @Test
    fun migrate5To6_preservesDataAndDropsSoftDeleteColumns() {
        val db = helper.createDatabase(DB_DATA, 5)
        db.execSQL(
            "INSERT INTO vault_entries (id, title, username, passwordEncrypted, url, notes, category, createdAt, updatedAt) " +
                "VALUES (1, 't', 'u', x'0102', '', '', 'other', 1, 1)"
        )
        db.execSQL(
            "INSERT INTO bills (id, amount, type, category, subCategory, note, date, yearMonth, timeOfDay, accountBookId, walletId, toWalletId, paymentMethod, merchant, transactionId, location, tags, images, linkedAssetId, linkType, recurringId, recurringFrequency, splitGroupId, isReimbursable, isReimbursed, reimbursedDate, isTaxDeductible, latitude, longitude, isAutoGenerated, isDeleted, deletedAt, createdAt, updatedAt) " +
                "VALUES (1, 1000, 'EXPENSE', 'food', '', 'note', 1, '2026-01', 'MORNING', 1, 1, NULL, 'CASH', '', '', '', '', '', NULL, NULL, NULL, '', '', 0, 0, NULL, 0, NULL, NULL, 0, 1, 12345, 1, 1)"
        )
        db.execSQL(
            "INSERT INTO assets (id, name, category, subCategory, brand, model, purchasePrice, acquisitionType, acquisitionDate, status, costMode, quantity, useCount, totalUsageHours, location, room, purchaseChannel, warrantyExpireDate, insuranceExpireDate, insuranceCompany, insurancePolicyNo, images, description, condition, serialNumber, receiptPath, depreciationRate, currentValue, maintenanceIntervalDays, lastMaintenanceDate, nextMaintenanceDate, maintenanceNotes, isFavorite, tags, linkedBillId, linkedMomentId, retireDate, retireReason, lostDate, lostReason, soldDate, soldPrice, soldChannel, soldToWhom, sortOrder, isDeleted, deletedAt, createdAt, updatedAt) " +
                "VALUES (1, 'laptop', 'electronics', '', '', '', 5000, 'PURCHASE', 1, 'IN_USE', 'NONE', 1, 0, 0.0, '', '', '', NULL, NULL, '', '', '', '', '', '', '', 0.1, 5000, 0, NULL, NULL, '', 0, '', NULL, NULL, NULL, '', NULL, '', NULL, NULL, NULL, NULL, 0, 0, NULL, 1, 1)"
        )
        db.close()

        val migrated = helper.runMigrationsAndValidate(DB_DATA, 6, true, MIGRATION_5_6)
        migrated.query("SELECT amount, type, note FROM bills WHERE id = 1").use { cursor ->
            assertTrue(cursor.moveToFirst())
            assertEquals(1000, cursor.getInt(0))
            assertEquals("EXPENSE", cursor.getString(1))
            assertEquals("note", cursor.getString(2))
        }
        migrated.query("SELECT name, purchasePrice FROM assets WHERE id = 1").use { cursor ->
            assertTrue(cursor.moveToFirst())
            assertEquals("laptop", cursor.getString(0))
            assertEquals(5000, cursor.getInt(1))
        }
        migrated.query("SELECT COUNT(*) FROM bills_recycle_bin").use { cursor ->
            assertTrue(cursor.moveToFirst())
            assertEquals(0, cursor.getInt(0))
        }
        migrated.query("SELECT COUNT(*) FROM assets_recycle_bin").use { cursor ->
            assertTrue(cursor.moveToFirst())
            assertEquals(0, cursor.getInt(0))
        }
        migrated.query("SELECT name FROM sqlite_master WHERE type='table' AND name='vault_entries'").use { cursor ->
            assertFalse(cursor.moveToFirst())
        }
        migrated.query("PRAGMA table_info(bills)").use { cursor ->
            while (cursor.moveToNext()) {
                val column = cursor.getString(1)
                assertFalse("isDeleted" == column || "deletedAt" == column)
            }
        }
        migrated.close()
    }

    @Test
    fun migrate5To6_recreatesBillsTriggers() {
        val db = helper.createDatabase(DB, 5)
        db.execSQL(
            "CREATE TRIGGER IF NOT EXISTS auto_yearmonth_insert AFTER INSERT ON bills " +
                "BEGIN UPDATE bills SET yearMonth = '2026-01' WHERE id = NEW.id; END"
        )
        db.execSQL(
            "CREATE TRIGGER IF NOT EXISTS auto_yearmonth_update AFTER UPDATE OF date ON bills " +
                "BEGIN UPDATE bills SET yearMonth = '2026-01' WHERE id = NEW.id; END"
        )
        db.execSQL(
            "CREATE TRIGGER IF NOT EXISTS bills_fts_ai AFTER INSERT ON bills BEGIN " +
                "INSERT INTO bills_fts(rowid, note, merchant, tags) VALUES (new.id, new.note, new.merchant, new.tags); END"
        )
        db.close()

        val migrated = helper.runMigrationsAndValidate(DB, 6, true, MIGRATION_5_6)
        migrated.query(
            "SELECT name FROM sqlite_master WHERE type='trigger' AND name='auto_yearmonth_insert'"
        ).use { cursor -> assertTrue(cursor.moveToFirst()) }
        migrated.query(
            "SELECT name FROM sqlite_master WHERE type='trigger' AND name='auto_yearmonth_update'"
        ).use { cursor -> assertTrue(cursor.moveToFirst()) }
        migrated.query(
            "SELECT name FROM sqlite_master WHERE type='trigger' AND name='bills_fts_ai'"
        ).use { cursor -> assertTrue(cursor.moveToFirst()) }
        migrated.close()
    }
}
