package com.palmnote.data.db.migration

import android.app.Application
import androidx.room.testing.MigrationTestHelper
import androidx.sqlite.db.framework.FrameworkSQLiteOpenHelperFactory
import androidx.test.platform.app.InstrumentationRegistry
import com.palmnote.data.db.AppDatabase
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config

/**
 * v7 → v8 迁移测试。
 *
 * 覆盖两个发布前必须验证的场景：
 * 1. 迁移后 schema 完整（含 idx_items_due / idx_items_parent —— Room 迁移路径不自动建索引，
 *    缺失会导致校验失败、库打不开）；
 * 2. bills_fts 清退：存量触发器/虚拟表被移除，迁移后记账（INSERT bills）不再触发
 *    "no such table: bills_fts"。
 *
 * 注：Robolectric 的 SQLite 不加载 fts5 模块，无法创建 bills_fts 虚拟表本身，
 * 但触发器可以在无表状态下创建——这恰好复现了 v5→v6 受损库的真实状态（有触发器无表）。
 */
@RunWith(RobolectricTestRunner::class)
@Config(sdk = [30], application = Application::class)
class Migration7To8Test {

    @get:Rule
    val helper = MigrationTestHelper(
        InstrumentationRegistry.getInstrumentation(),
        AppDatabase::class.java,
        emptyList(),
        FrameworkSQLiteOpenHelperFactory()
    )

    private companion object {
        const val DB = "migration-7-to-8"
        const val DB_DATA = "migration-7-to-8-data"
    }

    @Test
    fun migrate7To8_validatesFullSchemaWithIndexes() {
        helper.createDatabase(DB, 7).close()
        val migrated = helper.runMigrationsAndValidate(
            DB, 8, true, MIGRATION_7_8
        )
        assertObject(migrated, "index", "idx_items_due")
        assertObject(migrated, "index", "idx_items_parent")
        migrated.close()
    }

    @Test
    fun migrate7To8_dropsFtsTriggersAndTable() {
        // 模拟存量库：v7 + 三个引用 bills_fts 的触发器（受损库形态：有触发器无表）
        val seed = helper.createDatabase(DB, 7)
        val ftsBodies = mapOf(
            "ai" to "INSERT INTO bills_fts(rowid,note,merchant,tags) " +
                "VALUES(new.id,new.note,new.merchant,new.tags)",
            "ad" to "INSERT INTO bills_fts(bills_fts,rowid,note,merchant,tags) " +
                "VALUES('delete',old.id,old.note,old.merchant,old.tags)",
            "au" to "INSERT INTO bills_fts(bills_fts,rowid,note,merchant,tags) " +
                "VALUES('delete',old.id,old.note,old.merchant,old.tags); " +
                "INSERT INTO bills_fts(rowid,note,merchant,tags) " +
                "VALUES(new.id,new.note,new.merchant,new.tags)"
        )
        ftsBodies.forEach { (suffix, body) ->
            seed.execSQL("CREATE TRIGGER IF NOT EXISTS bills_fts_$suffix AFTER INSERT ON bills BEGIN $body; END")
        }
        seed.close()

        val migrated = helper.runMigrationsAndValidate(
            DB, 8, true, MIGRATION_7_8
        )
        assertObjectAbsent(migrated, "trigger", "bills_fts_ai")
        assertObjectAbsent(migrated, "trigger", "bills_fts_ad")
        assertObjectAbsent(migrated, "trigger", "bills_fts_au")
        assertObjectAbsent(migrated, "table", "bills_fts")
        migrated.close()
    }

    @Test
    fun migrate7To8_allowsBillInsertWithoutFtsError() {
        seedV7Bill()
        val migrated = helper.runMigrationsAndValidate(
            DB_DATA, 8, true, MIGRATION_7_8
        )
        // 记账路径回归：无 FTS 触发器残留时 INSERT 不应抛 no such table
        migrated.execSQL(
            "INSERT INTO bills " +
            "(id,amount,type,category,subCategory,note,date," +
            "yearMonth,accountBookId,walletId," +
            "toWalletId,paymentMethod,merchant,transactionId," +
            "location,tags,images,linkedAssetId,linkType," +
            "recurringId,recurringFrequency,splitGroupId," +
            "isReimbursable,isReimbursed,reimbursedDate," +
            "isTaxDeductible,latitude,longitude," +
            "isAutoGenerated,createdAt,updatedAt) " +
            "VALUES(2,2000,'EXPENSE','food','', 'n',2," +
            "'2026-02',1,1,NULL,'CASH','','',''," +
            "'','',NULL,NULL,NULL,'','',0,0,NULL,0,NULL," +
            "NULL,0,2,2)"
        )
        migrated.query("SELECT COUNT(*) FROM bills").use { c ->
            assertTrue(c.moveToFirst())
            assertTrue(c.getInt(0) >= 1)
        }
        migrated.close()
    }

    private fun seedV7Bill() {
        val db = helper.createDatabase(DB_DATA, 7)
        db.execSQL(
            "INSERT INTO bills " +
            "(id,amount,type,category,subCategory,note,date," +
            "yearMonth,accountBookId,walletId," +
            "toWalletId,paymentMethod,merchant,transactionId," +
            "location,tags,images,linkedAssetId,linkType," +
            "recurringId,recurringFrequency,splitGroupId," +
            "isReimbursable,isReimbursed,reimbursedDate," +
            "isTaxDeductible,latitude,longitude," +
            "isAutoGenerated,createdAt,updatedAt) " +
            "VALUES(1,1000,'EXPENSE','food','', 'note',1," +
            "'2026-01',1,1,NULL,'CASH','','',''," +
            "'','',NULL,NULL,NULL,'','',0,0,NULL,0,NULL," +
            "NULL,0,1,1)"
        )
        db.close()
    }

    private fun assertObject(db: androidx.sqlite.db.SupportSQLiteDatabase, type: String, name: String) {
        db.query(
            "SELECT name FROM sqlite_master WHERE type='$type' AND name='$name'"
        ).use { c -> assertTrue("期望存在 $type $name", c.moveToFirst()) }
    }

    private fun assertObjectAbsent(db: androidx.sqlite.db.SupportSQLiteDatabase, type: String, name: String) {
        db.query(
            "SELECT name FROM sqlite_master WHERE type='$type' AND name='$name'"
        ).use { c -> assertFalse("期望不存在 $type $name", c.moveToFirst()) }
    }
}
