package com.palmnote.data.db.migration

import android.app.Application
import androidx.room.testing.MigrationTestHelper
import androidx.sqlite.db.SupportSQLiteDatabase
import androidx.sqlite.db.framework.FrameworkSQLiteOpenHelperFactory
import androidx.test.platform.app.InstrumentationRegistry
import com.palmnote.data.db.AppDatabase
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config

/**
 * v15 → v16 迁移测试：给 `bills` / `bills_recycle_bin` 加报销进度两列。
 *
 * 验收口径：
 * - `reimbursedAmount` 为 NOT NULL DEFAULT 0，**未标记报销的存量行一律 0**（等于「尚未开始报销」，
 *   不得凭空造出已报金额）；
 * - 但**已标记 `isReimbursed = 1` 的存量行要回填成已报满（= amount）** —— 该标记早于本迁移存在
 *   且可由 CSV 导入写入，只置 0 会让「列表算已报销 / 详情按 reimbursedAmount 显示待报销」自相矛盾；
 * - `reimbursedByBillId` 存量行一律 NULL（关联收入账单此时并不存在，无从而填）；
 * - 已经标了「可报销」的存量行原有三列（isReimbursable / isReimbursed / reimbursedDate）一字不动；
 * - 空表也要能迁移。
 */
@RunWith(RobolectricTestRunner::class)
@Config(sdk = [30], application = Application::class)
class Migration15To16Test {

    @get:Rule
    val helper = MigrationTestHelper(
        InstrumentationRegistry.getInstrumentation(),
        AppDatabase::class.java,
        emptyList(),
        FrameworkSQLiteOpenHelperFactory()
    )

    private companion object {
        const val DB = "migration-15-to-16"

        /** 第二个测试用独立库名：同名库残留文件可能让两个测试互相影响。 */
        const val DB_EMPTY = "migration-15-to-16-empty"

        const val NEW_COLUMNS = "reimbursedAmount, reimbursedByBillId"

        /** v15 的 bills 全列（迁入行必须写全，缺 NOT NULL 列会插入失败）。 */
        const val V15_BILL_COLUMNS =
            "id, amount, type, category, subCategory, note, date, yearMonth, accountBookId, " +
                "walletId, toWalletId, paymentMethod, merchant, transactionId, location, tags, images, " +
                "linkedAssetId, linkType, recurringId, recurringFrequency, splitGroupId, " +
                "isReimbursable, isReimbursed, reimbursedDate, isTaxDeductible, latitude, longitude, " +
                "isAutoGenerated, isDemo, createdAt, updatedAt"
    }

    private fun seedV15Bill(
        db: SupportSQLiteDatabase,
        id: Long,
        amount: Long,
        category: String,
        isReimbursable: Int,
        isReimbursed: Int = 0
    ) {
        db.execSQL(
            "INSERT INTO bills ($V15_BILL_COLUMNS) VALUES " +
                "(?, ?, 'EXPENSE', ?, '', '高铁票', 1700000000000, '2023-11', 1, " +
                "NULL, NULL, 'OTHER', '', '', '', '', '', " +
                "NULL, NULL, NULL, 'MONTHLY', '', " +
                "?, ?, NULL, 0, NULL, NULL, " +
                "0, 0, 1700000000000, 1700000000000)",
            arrayOf<Any?>(id, amount, category, isReimbursable, isReimbursed)
        )
    }

    @Test
    fun migrate15To16_addsZeroDefaultsAndKeepsExistingRows() {
        val seed = helper.createDatabase(DB, 15)
        seedV15Bill(seed, id = 1, amount = 100000, category = "差旅", isReimbursable = 1)
        seedV15Bill(seed, id = 2, amount = 250000, category = "办公", isReimbursable = 0)
        // 存量里「可报销且已标记报销」的行（旧版本 CSV 导入会写出这种组合）：
        // 迁移必须把它回填成已报满，否则列表页与详情页对它的判断会打架。
        seedV15Bill(seed, id = 3, amount = 88800, category = "差旅", isReimbursable = 1, isReimbursed = 1)
        seed.close()

        val migrated = helper.runMigrationsAndValidate(DB, 16, true, MIGRATION_15_16)

        migrated.query(
            "SELECT category, amount, isReimbursable, isReimbursed, reimbursedDate, $NEW_COLUMNS FROM bills WHERE id = 1"
        ).use { c ->
            assertTrue("期望存在 id=1 的账单", c.moveToFirst())
            assertEquals("差旅", c.getString(0))
            assertEquals("存量金额不得被迁移改动", 100000L, c.getLong(1))
            assertEquals("存量「可报销」标记不得被迁移改动", 1, c.getInt(2))
            assertEquals("存量「已报销」标记不得被迁移改动", 0, c.getInt(3))
            assertTrue("存量报销日期必须仍为 NULL", c.isNull(4))
            assertEquals("存量行的已报金额必须是 0（未开始报销）", 0L, c.getLong(5))
            assertTrue("存量行的关联报销收入必须为 NULL", c.isNull(6))
        }

        migrated.query(
            "SELECT amount, isReimbursed, $NEW_COLUMNS FROM bills WHERE id = 3"
        ).use { c ->
            assertTrue("期望存在 id=3 的账单", c.moveToFirst())
            assertEquals("存量金额不得被迁移改动", 88800L, c.getLong(0))
            assertEquals("存量「已报销」标记不得被迁移改动", 1, c.getInt(1))
            assertEquals("已标记报销的存量行要回填为已报满", 88800L, c.getLong(2))
            assertTrue("存量行的关联报销收入必须为 NULL", c.isNull(3))
        }

        migrated.query("SELECT COUNT(*) FROM bills").use { c ->
            assertTrue(c.moveToFirst())
            assertEquals("存量行不能被迁移丢掉", 3, c.getInt(0))
        }

        // 回收站表同样要加上这两列（空表 SELECT 即可证明列存在）
        migrated.query("SELECT $NEW_COLUMNS FROM bills_recycle_bin").use { c ->
            assertEquals(0, c.count)
        }
        migrated.close()
    }

    @Test
    fun migrate15To16_onEmptyTables_succeeds() {
        val seed = helper.createDatabase(DB_EMPTY, 15)
        seed.close()
        val migrated = helper.runMigrationsAndValidate(DB_EMPTY, 16, true, MIGRATION_15_16)
        migrated.query("SELECT COUNT(*) FROM bills").use { c ->
            assertTrue(c.moveToFirst())
            assertEquals(0, c.getInt(0))
        }
        migrated.query("SELECT $NEW_COLUMNS FROM bills_recycle_bin").use { c ->
            assertEquals(0, c.count)
        }
        migrated.close()
    }
}
