package com.palmnote.data.repository

import com.palmnote.data.db.dao.BillDao
import com.palmnote.data.db.entity.Bill
import io.mockk.coEvery
import io.mockk.coVerify
import io.mockk.mockk
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.flow.flowOf
import kotlinx.coroutines.test.runTest
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Before
import org.junit.Test

class BillRepositoryTest {

    private lateinit var billDao: BillDao
    private lateinit var billRepository: BillRepository

    @Before
    fun setUp() {
        billDao = mockk(relaxUnitFun = true)
        billRepository = BillRepository(billDao)
    }

    @Test
    fun `insertBill returns bill id`() = runTest {
        val bill = createTestBill()
        coEvery { billDao.insertBill(bill) } returns 1L

        val result = billRepository.insertBill(bill)

        assertEquals(1L, result)
        coVerify { billDao.insertBill(bill) }
    }

    @Test
    fun `getBillById returns bill when exists`() = runTest {
        val bill = createTestBill(id = 1L)
        coEvery { billDao.getBillById(1L) } returns bill

        val result = billRepository.getBillById(1L)

        assertNotNull(result)
        assertEquals(1L, result?.id)
        assertEquals("餐饮", result?.category)
    }

    @Test
    fun `getBillById returns null when not exists`() = runTest {
        coEvery { billDao.getBillById(999L) } returns null

        val result = billRepository.getBillById(999L)

        assertEquals(null, result)
    }

    @Test
    fun `getBillsByMonth returns bills for given month`() = runTest {
        val bills = listOf(
            createTestBill(id = 1L, amount = 50.0),
            createTestBill(id = 2L, amount = 30.0)
        )
        coEvery { billDao.getBillsByMonth("2026-07") } returns flowOf(bills)

        val result = billRepository.getBillsByMonth("2026-07").first()

        assertEquals(2, result.size)
        assertEquals(50.0, result[0].amount, 0.01)
    }

    @Test
    fun `softDeleteBill calls dao`() = runTest {
        coEvery { billDao.softDeleteBill(1L) } returns Unit

        billRepository.softDeleteBill(1L)

        coVerify { billDao.softDeleteBill(1L) }
    }

    @Test
    fun `updateBill calls dao`() = runTest {
        val bill = createTestBill(id = 1L, amount = 100.0)
        coEvery { billDao.updateBill(bill) } returns Unit

        billRepository.updateBill(bill)

        coVerify { billDao.updateBill(bill) }
    }

    @Test
    fun `getMonthlyExpense returns total expense`() = runTest {
        coEvery { billDao.getMonthlyExpense("2026-07") } returns flowOf(500.0)

        val result = billRepository.getMonthlyExpense("2026-07").first()

        assertEquals(500.0, result, 0.01)
    }

    @Test
    fun `getCategoryFrequency returns category counts`() = runTest {
        val categories = listOf(
            com.palmnote.data.db.dao.CategoryTotalWithCount("餐饮", 200.0, 5),
            com.palmnote.data.db.dao.CategoryTotalWithCount("交通", 100.0, 3)
        )
        coEvery { billDao.getCategoryFrequency("2026-07") } returns flowOf(categories)

        val result = billRepository.getCategoryFrequency("2026-07").first()

        assertEquals(2, result.size)
        assertEquals("餐饮", result[0].category)
        assertEquals(5, result[0].count)
    }

    @Test
    fun `getLastBillByMerchant returns bill`() = runTest {
        val bill = createTestBill(id = 1L, merchant = "星巴克")
        coEvery { billDao.getLastBillByMerchant("星巴克") } returns bill

        val result = billRepository.getLastBillByMerchant("星巴克")

        assertNotNull(result)
        assertEquals("星巴克", result?.merchant)
    }

    private fun createTestBill(
        id: Long = 0L,
        amount: Double = 50.0,
        type: String = "EXPENSE",
        category: String = "餐饮",
        merchant: String = ""
    ) = Bill(
        id = id,
        amount = amount,
        type = type,
        category = category,
        subCategory = "",
        note = "",
        date = System.currentTimeMillis(),
        yearMonth = "2026-07",
        timeOfDay = "",
        walletId = 1L,
        toWalletId = null,
        paymentMethod = "",
        merchant = merchant,
        location = "",
        tags = "",
        images = "",
        linkedAssetId = null,
        linkType = null,
        recurringId = null,
        recurringFrequency = "",
        splitGroupId = "",
        isReimbursable = false,
        isReimbursed = false,
        reimbursedDate = null,
        isTaxDeductible = false,
        latitude = null,
        longitude = null,
        isAutoGenerated = false,
        isDeleted = false,
        deletedAt = null,
        createdAt = System.currentTimeMillis(),
        updatedAt = System.currentTimeMillis()
    )
}
