package com.palmnote.data.db.entity

import androidx.room.Entity
import androidx.room.PrimaryKey
import com.palmnote.domain.model.BillType
import com.palmnote.domain.model.PaymentMethod
import com.palmnote.domain.model.RecurringFrequency
import com.palmnote.domain.model.TimeOfDay

/**
 * 账单回收站：删除的账单暂存于此，可恢复。
 */
@Entity(tableName = "bills_recycle_bin")
data class BillRecycleBin(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val originalId: Long,
    val amount: Long,
    val type: BillType,
    val category: String,
    val subCategory: String = "",
    val note: String = "",
    val date: Long,
    val yearMonth: String,
    val timeOfDay: TimeOfDay = TimeOfDay.MORNING,
    val accountBookId: Long = 1,
    val walletId: Long? = null,
    val toWalletId: Long? = null,
    val paymentMethod: PaymentMethod = PaymentMethod.OTHER,
    val merchant: String = "",
    val transactionId: String = "",
    val location: String = "",
    val tags: String = "",
    val images: String = "",
    val linkedAssetId: Long? = null,
    val linkType: String? = null,
    val recurringId: Long? = null,
    val recurringFrequency: RecurringFrequency = RecurringFrequency.MONTHLY,
    val splitGroupId: String = "",
    val isReimbursable: Boolean = false,
    val isReimbursed: Boolean = false,
    val reimbursedDate: Long? = null,
    val isTaxDeductible: Boolean = false,
    val latitude: Double? = null,
    val longitude: Double? = null,
    val isAutoGenerated: Boolean = false,
    val createdAt: Long = System.currentTimeMillis(),
    val updatedAt: Long = System.currentTimeMillis(),
    val deletedAt: Long = System.currentTimeMillis()
)

fun Bill.toRecycleBin() = BillRecycleBin(
    originalId = id, amount = amount, type = type, category = category,
    subCategory = subCategory, note = note, date = date, yearMonth = yearMonth,
    timeOfDay = timeOfDay, accountBookId = accountBookId, walletId = walletId,
    toWalletId = toWalletId, paymentMethod = paymentMethod, merchant = merchant,
    transactionId = transactionId, location = location, tags = tags, images = images,
    linkedAssetId = linkedAssetId, linkType = linkType, recurringId = recurringId,
    recurringFrequency = recurringFrequency, splitGroupId = splitGroupId,
    isReimbursable = isReimbursable, isReimbursed = isReimbursed,
    reimbursedDate = reimbursedDate, isTaxDeductible = isTaxDeductible,
    latitude = latitude, longitude = longitude, isAutoGenerated = isAutoGenerated,
    createdAt = createdAt, updatedAt = updatedAt, deletedAt = System.currentTimeMillis()
)

fun BillRecycleBin.toBill() = Bill(
    id = originalId, amount = amount, type = type, category = category,
    subCategory = subCategory, note = note, date = date, yearMonth = yearMonth,
    timeOfDay = timeOfDay, accountBookId = accountBookId, walletId = walletId,
    toWalletId = toWalletId, paymentMethod = paymentMethod, merchant = merchant,
    transactionId = transactionId, location = location, tags = tags, images = images,
    linkedAssetId = linkedAssetId, linkType = linkType, recurringId = recurringId,
    recurringFrequency = recurringFrequency, splitGroupId = splitGroupId,
    isReimbursable = isReimbursable, isReimbursed = isReimbursed,
    reimbursedDate = reimbursedDate, isTaxDeductible = isTaxDeductible,
    latitude = latitude, longitude = longitude, isAutoGenerated = isAutoGenerated,
    createdAt = createdAt, updatedAt = updatedAt
)
