package com.palmnote.data.db.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "bills")
data class Bill(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val amount: Double,
    val type: String, // EXPENSE, INCOME, TRANSFER
    val category: String,
    val subCategory: String = "", // 子分类
    val note: String = "",
    val date: Long, // timestamp
    val yearMonth: String, // "2024-01"
    val timeOfDay: String = "", // MORNING, AFTERNOON, EVENING, NIGHT (自动判断)
    val accountBookId: Long = 1, // 关联的账本ID，默认1（默认账本）
    val walletId: Long? = null, // 关联的钱包/账户ID
    val toWalletId: Long? = null, // 转账目标账户（仅TRANSFER类型）
    val paymentMethod: String = "", // CASH, WECHAT, ALIPAY, CARD, BANK_TRANSFER, OTHER
    val merchant: String = "", // 商家/商户
    val transactionId: String = "", // 交易单号（导入来源）
    val location: String = "", // 消费地点
    val tags: String = "", // JSON array of tags
    val images: String = "", // 发票/小票照片
    val linkedAssetId: Long? = null,
    val linkType: String? = null, // PURCHASE, MAINTENANCE, WARRANTY, INSURANCE
    val recurringId: Long? = null, // 关联的周期性模板ID
    val recurringFrequency: String = "", // DAILY, WEEKLY, MONTHLY, YEARLY
    val splitGroupId: String = "", // 拆分组ID
    val isReimbursable: Boolean = false, // 是否可报销
    val isReimbursed: Boolean = false, // 是否已报销
    val reimbursedDate: Long? = null,
    val isTaxDeductible: Boolean = false, // 是否可抵税
    val latitude: Double? = null, // GPS纬度
    val longitude: Double? = null, // GPS经度
    val isAutoGenerated: Boolean = false,
    val isDeleted: Boolean = false,
    val deletedAt: Long? = null,
    val createdAt: Long = System.currentTimeMillis(),
    val updatedAt: Long = System.currentTimeMillis()
)

@Entity(tableName = "recurring_templates")
data class RecurringTemplate(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val name: String, // 模板名称，如"房租"、"工资"
    val amount: Double,
    val type: String, // EXPENSE, INCOME
    val category: String,
    val frequency: String, // DAILY, WEEKLY, MONTHLY, YEARLY
    val dayOfMonth: Int = 0, // 每月几号 (MONTHLY时)
    val dayOfWeek: Int = 0, // 周几 (WEEKLY时, 1=周一)
    val isActive: Boolean = true,
    val lastGeneratedDate: Long? = null,
    val nextGenerateDate: Long? = null,
    val autoGenerate: Boolean = true, // 自动生成账单
    val remindBeforeDays: Int = 1, // 提前提醒天数
    val note: String = "",
    val isDeleted: Boolean = false,
    val createdAt: Long = System.currentTimeMillis(),
    val updatedAt: Long = System.currentTimeMillis()
)
