package com.palmnote.feature.vault.vault

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.width
import androidx.compose.material3.Checkbox
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.ModalBottomSheet
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.material3.rememberModalBottomSheetState
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableIntStateOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.foundation.text.selection.SelectionContainer
import com.palmnote.R
import com.palmnote.feature.vault.PasswordStrength
import com.palmnote.feature.vault.VaultPasswordGenerator

/**
 * 密码生成器 BottomSheet：长度与字符集可配置，显示熵与强度。
 */
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun VaultPasswordGeneratorSheet(
    onUse: (String) -> Unit,
    onDismiss: () -> Unit
) {
    val sheetState = rememberModalBottomSheetState()
    var length by remember { mutableIntStateOf(DEFAULT_LENGTH) }
    var useUpper by remember { mutableStateOf(true) }
    var useLower by remember { mutableStateOf(true) }
    var useDigits by remember { mutableStateOf(true) }
    var useSymbols by remember { mutableStateOf(true) }
    var generated by remember { mutableStateOf("") }
    val generatedOptions = listOf(8, 12, 16, 20, 24)

    fun regenerate() {
        generated = if (useUpper || useLower || useDigits || useSymbols) {
            VaultPasswordGenerator.generate(length, useUpper, useLower, useDigits, useSymbols)
        } else {
            ""
        }
    }

    if (generated.isEmpty()) {
        regenerate()
    }

    ModalBottomSheet(onDismissRequest = onDismiss, sheetState = sheetState) {
        Column(
            modifier = Modifier
                .fillMaxWidth()
                .padding(horizontal = 24.dp)
                .padding(bottom = 32.dp)
        ) {
            Text(
                text = stringResource(R.string.vault_generator_title),
                style = MaterialTheme.typography.titleLarge,
                fontWeight = FontWeight.Bold
            )
            Spacer(Modifier.height(16.dp))

            SelectionContainer {
                Text(
                    text = generated.ifEmpty { stringResource(R.string.vault_generator_empty) },
                    style = MaterialTheme.typography.bodyLarge,
                    color = if (generated.isEmpty()) MaterialTheme.colorScheme.onSurfaceVariant
                    else MaterialTheme.colorScheme.onSurface
                )
            }
            if (generated.isNotEmpty()) {
                Spacer(Modifier.height(8.dp))
                val entropy = VaultPasswordGenerator.estimateEntropy(generated)
                val strength = VaultPasswordGenerator.strengthOf(entropy)
                Text(
                    text = stringResource(
                        R.string.vault_generator_strength,
                        strengthLabel(strength),
                        entropy.toInt()
                    ),
                    style = MaterialTheme.typography.bodySmall,
                    color = strengthColor(strength)
                )
            }

            Spacer(Modifier.height(16.dp))
            Text(
                text = stringResource(R.string.vault_generator_length),
                style = MaterialTheme.typography.labelLarge
            )
            Spacer(Modifier.height(8.dp))
            Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                generatedOptions.forEach { option ->
                    OutlinedButton(
                        onClick = { length = option; regenerate() },
                        contentPadding = androidx.compose.foundation.layout.PaddingValues(horizontal = 16.dp)
                    ) {
                        Text(
                            text = option.toString(),
                            fontWeight = if (length == option) FontWeight.Bold else FontWeight.Normal
                        )
                    }
                }
            }

            Spacer(Modifier.height(12.dp))
            CharSetRow(stringResource(R.string.vault_generator_uppercase), useUpper) { useUpper = it; regenerate() }
            CharSetRow(stringResource(R.string.vault_generator_lowercase), useLower) { useLower = it; regenerate() }
            CharSetRow(stringResource(R.string.vault_generator_digits), useDigits) { useDigits = it; regenerate() }
            CharSetRow(stringResource(R.string.vault_generator_symbols), useSymbols) { useSymbols = it; regenerate() }

            Spacer(Modifier.height(16.dp))
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.spacedBy(12.dp)
            ) {
                OutlinedButton(
                    onClick = { regenerate() },
                    modifier = Modifier.weight(1f)
                ) {
                    Text(stringResource(R.string.vault_generator_regenerate))
                }
                TextButton(
                    onClick = { if (generated.isNotEmpty()) { onUse(generated); onDismiss() } },
                    modifier = Modifier.weight(1f),
                    enabled = generated.isNotEmpty()
                ) {
                    Text(
                        stringResource(R.string.vault_generator_use),
                        fontWeight = FontWeight.Bold
                    )
                }
            }
        }
    }
}

@Composable
private fun CharSetRow(label: String, checked: Boolean, onChange: (Boolean) -> Unit) {
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .padding(vertical = 2.dp),
        verticalAlignment = Alignment.CenterVertically
    ) {
        Checkbox(checked = checked, onCheckedChange = onChange)
        Spacer(Modifier.width(8.dp))
        Text(text = label, style = MaterialTheme.typography.bodyLarge)
    }
}

@Composable
private fun strengthLabel(strength: PasswordStrength): String = stringResource(
    when (strength) {
        PasswordStrength.WEAK -> R.string.vault_strength_weak
        PasswordStrength.MEDIUM -> R.string.vault_strength_medium
        PasswordStrength.STRONG -> R.string.vault_strength_strong
        PasswordStrength.VERY_STRONG -> R.string.vault_strength_very_strong
    }
)

@Composable
private fun strengthColor(strength: PasswordStrength): androidx.compose.ui.graphics.Color = when (strength) {
    PasswordStrength.WEAK -> MaterialTheme.colorScheme.error
    PasswordStrength.MEDIUM -> MaterialTheme.colorScheme.tertiary
    PasswordStrength.STRONG -> MaterialTheme.colorScheme.primary
    PasswordStrength.VERY_STRONG -> MaterialTheme.colorScheme.primary
}

private const val DEFAULT_LENGTH = 16
