package com.palmnote.data.export

import android.content.Context
import android.net.Uri
import android.util.Log
import com.palmnote.R
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.contentOrNull
import com.palmnote.data.db.AppDatabase
import com.palmnote.data.db.entity.*
import com.palmnote.data.datastore.PreferencesManager
import com.palmnote.ui.theme.AppIcon
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.withContext
import java.io.*
import java.lang.reflect.Modifier
import java.time.Instant
import java.time.LocalDateTime
import java.time.ZoneId
import java.time.format.DateTimeFormatter
import java.util.*
import java.util.zip.ZipEntry
import java.util.zip.ZipInputStream
import java.util.zip.ZipOutputStream
import com.palmnote.domain.util.AppException

class CsvDataExporter(
    private val context: Context,
    private val db: AppDatabase,
    private val preferencesManager: PreferencesManager
) {
    private val json = Json { ignoreUnknownKeys = true; coerceInputValues = true; encodeDefaults = true }

    companion object {
        private val EXCLUDED_FIELDS: Map<Class<*>, Set<String>> = mapOf(
            Asset::class.java to setOf("receiptPath"),
            Bill::class.java to setOf("yearMonth", "isAutoGenerated"),
            Moment::class.java to setOf("videoPath", "audioPath"),
            RecurringTemplate::class.java to setOf("lastGeneratedDate", "nextGenerateDate")
        )

        private val DATE_FIELDS = setOf(
            "date", "deadline", "solarDate", "startDate", "periodStartDate",
            "lastCheckInDate", "usedAt", "acquisitionDate",
            "warrantyExpireDate", "insuranceExpireDate", "lastMaintenanceDate",
            "nextMaintenanceDate", "retireDate", "lostDate", "soldDate",
            "reimbursedDate", "deletedAt", "createdAt", "updatedAt"
        )
        private val LIST_FIELDS = setOf("tags", "applicableTypes", "multiRemindJson")
        private const val IMAGE_PREFIX = "img_"
        private const val PREFERENCES_ENTRY = "preferences.json"
        val ENTITY_CLASSES = listOf(
            Asset::class.java, Bill::class.java, Wallet::class.java,
            Goal::class.java, GoalCheckIn::class.java, Anniversary::class.java,
            Moment::class.java, RecurringTemplate::class.java, Budget::class.java,
            CategoryConfig::class.java, CustomTag::class.java,
            CategoryMapping::class.java
        )

        private val CODE_TO_CN: Map<Class<*>, Map<String, Map<String, String>>> = mapOf(
            Asset::class.java to mapOf(
                "status" to mapOf("HELD" to "持有中", "AWAY" to "暂离中", "REMOVED" to "已清出"),
                "acquisitionType" to mapOf("PURCHASE" to "购买", "GIFT" to "赠送", "LOTTERY" to "抽奖", "PRIZE" to "奖品", "INHERITANCE" to "继承", "OTHER" to "其他"),
                "condition" to mapOf("NEW" to "全新", "GOOD" to "良好", "FAIR" to "一般", "POOR" to "较差"),
                "costMode" to mapOf("DAILY" to "按天计算", "PER_USE" to "按次计算", "DEPRECIATION" to "折旧")
            ),
            Bill::class.java to mapOf(
                "type" to mapOf("EXPENSE" to "支出", "INCOME" to "收入", "TRANSFER" to "转账"),
                "paymentMethod" to mapOf("CASH" to "现金", "WECHAT" to "微信", "ALIPAY" to "支付宝", "CARD" to "银行卡", "BANK_TRANSFER" to "银行转账", "OTHER" to "其他"),
                "linkType" to mapOf("PURCHASE" to "购买", "MAINTENANCE" to "维护", "WARRANTY" to "质保", "INSURANCE" to "保险"),
                "timeOfDay" to mapOf("MORNING" to "早上", "AFTERNOON" to "下午", "EVENING" to "晚上", "NIGHT" to "深夜")
            ),
            Wallet::class.java to mapOf(
                "type" to mapOf("CASH" to "现金", "E_WALLET" to "电子钱包", "BANK_CARD" to "银行卡", "CREDIT_CARD" to "信用卡", "INVESTMENT" to "投资账户", "OTHER" to "其他")
            ),
            Goal::class.java to mapOf(
                "priority" to mapOf("HIGH" to "高", "MEDIUM" to "中", "LOW" to "低"),
                "goalType" to mapOf("CUMULATIVE" to "累计", "HABIT" to "习惯", "TARGET" to "目标"),
                "frequency" to mapOf("DAILY" to "每日", "WEEKLY" to "每周", "MONTHLY" to "每月"),
                "category" to mapOf("FITNESS" to "运动", "READING" to "阅读", "SKILL" to "技能", "HABIT" to "习惯", "PROJECT" to "项目", "SAVING" to "储蓄", "CUSTOM" to "自定义")
            ),
            Anniversary::class.java to mapOf(
                "type" to mapOf("BIRTHDAY" to "生日", "WEDDING" to "结婚", "MEETING" to "相识", "GRADUATION" to "毕业", "JOB" to "工作", "TRAVEL" to "旅行", "BABY" to "宝宝", "PET" to "宠物", "CUSTOM" to "自定义")
            ),
            Moment::class.java to mapOf(
                "mood" to mapOf("GREAT" to "开心", "GOOD" to "不错", "OK" to "一般", "BAD" to "难过", "TERRIBLE" to "糟糕"),
                "weather" to mapOf("SUNNY" to "晴", "CLOUDY" to "多云", "RAINY" to "雨", "SNOWY" to "雪", "WINDY" to "风", "FOGGY" to "雾"),
                "privacy" to mapOf("PRIVATE" to "私密", "FRIENDS" to "好友", "PUBLIC" to "公开"),
                "category" to mapOf("TRAVEL" to "旅行", "FOOD" to "美食", "FAMILY" to "家庭", "WORK" to "工作", "FRIEND" to "朋友", "HOBBY" to "爱好", "NATURE" to "自然", "PET" to "宠物", "CUSTOM" to "其他")
            ),
            CategoryConfig::class.java to mapOf(
                "type" to mapOf("ASSET" to "物品", "BILL_EXPENSE" to "支出", "BILL_INCOME" to "收入", "GOAL" to "目标", "ANNIVERSARY" to "纪念日", "MOMENT" to "瞬间", "TAG" to "标签")
            ),
            GoalCheckIn::class.java to mapOf(
                "mood" to mapOf("GREAT" to "开心", "GOOD" to "不错", "OK" to "一般", "BAD" to "难过")
            ),
            RecurringTemplate::class.java to mapOf(
                "type" to mapOf("EXPENSE" to "支出", "INCOME" to "收入"),
                "frequency" to mapOf("DAILY" to "每日", "WEEKLY" to "每周", "MONTHLY" to "每月", "YEARLY" to "每年")
            )
        )

        val CN_TO_CODE: Map<Class<*>, Map<String, Map<String, String>>> by lazy {
            CODE_TO_CN.mapValues { (_, fieldMap) ->
                fieldMap.mapValues { (_, codeMap) ->
                    codeMap.entries.associate { (code, cn) -> cn to code }
                }
            }
        }

        val FIELD_LABEL_CN: Map<String, String> = mapOf(
            "id" to "编号", "name" to "名称", "type" to "类型",
            "category" to "分类", "subCategory" to "子分类",
            "color" to "颜色", "icon" to "图标", "description" to "描述",
            "isDeleted" to "已删除", "deletedAt" to "删除时间",
            "createdAt" to "创建时间", "updatedAt" to "更新时间",
            "sortOrder" to "排序", "tags" to "标签", "images" to "图片",
            "note" to "备注", "date" to "日期",
            "brand" to "品牌", "model" to "型号",
            "quantity" to "数量",
            "purchasePrice" to "购买价格",
            "acquisitionType" to "获取方式", "acquisitionDate" to "获取日期",
            "status" to "状态", "costMode" to "计费方式",
            "useCount" to "使用次数", "totalUsageHours" to "使用总时长",
            "location" to "存放位置", "room" to "房间",
            "purchaseChannel" to "购买渠道",
            "warrantyExpireDate" to "保修日期", "insuranceExpireDate" to "保险到期日",
            "insuranceCompany" to "保险公司", "insurancePolicyNo" to "保单号",
            "condition" to "成色", "serialNumber" to "序列号",
            "depreciationRate" to "折旧率", "currentValue" to "现值",
            "maintenanceIntervalDays" to "维护周期", "lastMaintenanceDate" to "上次维护",
            "nextMaintenanceDate" to "下次维护", "maintenanceNotes" to "维护备注",
            "isFavorite" to "收藏", "linkedBillId" to "关联账单",
            "linkedMomentId" to "关联瞬间", "retireDate" to "退役日期",
            "retireReason" to "退役原因", "lostDate" to "丢失日期",
            "lostReason" to "遗失原因", "soldDate" to "售出日期",
            "soldPrice" to "售出价格", "soldChannel" to "售出渠道",
            "soldToWhom" to "售出对象",
            "amount" to "金额", "yearMonth" to "年月",
            "timeOfDay" to "时段", "walletId" to "钱包",
            "toWalletId" to "目标钱包", "paymentMethod" to "支付方式",
            "merchant" to "商户名称", "linkedAssetId" to "关联物品",
            "linkType" to "关联类型",
            "recurringId" to "模板ID", "recurringFrequency" to "周期频率",
            "splitGroupId" to "拆分组ID",
            "isReimbursable" to "可报销", "isReimbursed" to "已报销",
            "reimbursedDate" to "报销日期", "isTaxDeductible" to "可抵税",
            "latitude" to "纬度", "longitude" to "经度",
            "bankName" to "银行名称", "cardNumber" to "卡号",
            "initialBalance" to "初始余额", "currentBalance" to "当前余额",
            "currency" to "币种", "isDefault" to "默认",
            "isEnabled" to "启用",
            "title" to "标题", "goalType" to "目标类型",
            "totalCount" to "目标次数", "currentCount" to "当前次数",
            "unit" to "单位", "frequency" to "频率",
            "targetPerPeriod" to "周期目标", "currentPeriodCount" to "本期完成",
            "periodStartDate" to "周期开始日期", "deadline" to "截止日期",
            "startDate" to "开始日期", "priority" to "优先级",
            "streak" to "连续天数", "longestStreak" to "最长连续",
            "lastCheckInDate" to "上次打卡日期", "totalCheckInDays" to "打卡总天数",
            "reminderEnabled" to "提醒", "reminderTime" to "提醒时间",
            "isPublic" to "公开", "notes" to "备注",
            "goalId" to "目标ID", "count" to "次数",
            "duration" to "时长", "mood" to "心情",
            "solarDate" to "公历日期", "isLunar" to "农历",
            "lunarYear" to "农历年", "lunarMonth" to "农历月",
            "lunarDay" to "农历日", "lunarLeapMonth" to "闰月",
            "personName" to "姓名", "personRelation" to "关系",
            "isYearly" to "每年", "displayMode" to "显示模式",
            "multiRemindJson" to "多次提醒", "notificationEnabled" to "通知",
            "emoji" to "表情", "isPinned" to "置顶",
            "content" to "内容", "timestamp" to "时间",
            "weather" to "天气", "temperature" to "温度",
            "privacy" to "隐私",
            "wordCount" to "字数",
            "linkedAnniversaryId" to "关联纪念日", "linkedGoalId" to "关联目标",
            "dayOfMonth" to "每月几号", "dayOfWeek" to "每周几",
            "isActive" to "激活", "autoGenerate" to "自动生成",
            "totalBudget" to "预算总额", "reminderThreshold" to "提醒阈值",
            "reminderAtThreshold" to "阈值提醒", "reminderOverBudget" to "超支提醒",
            "parentId" to "父分类", "usageCount" to "使用次数",
            "applicableTypes" to "适用类型",
            "assetCategory" to "物品分类", "billCategory" to "账单分类",
            "assetId" to "物品ID", "usedAt" to "使用时间",
            "usageRecords" to "使用记录"
        )
    }

    private val dateFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")
    private val yearMonthFormatter = DateTimeFormatter.ofPattern("yyyy-MM")
    private val imageFileMap = mutableMapOf<String, File>()

    suspend fun exportToUri(uri: Uri): Result<String> {
        return withContext(Dispatchers.IO) {
            try {
                imageFileMap.clear()
                val wallets = db.walletDao().getAllWallets().first()
                val bills = db.billDao().getAllBills().first()
                val templates = db.recurringTemplateDao().getAllTemplates().first()
                val budgets = db.budgetDao().getAllBudgets().first()
                val assets = db.assetDao().getAllAssets().first()
                val usageRecords = db.usageRecordDao().getAllUsageRecords().first()
                val goals = db.goalDao().getAllGoals().first()
                val goalCheckIns = if (goals.isNotEmpty()) {
                    db.goalCheckInDao().getCheckInsByGoalIds(goals.map { it.id }).first()
                } else {
                    emptyList()
                }
                val anniversaries = db.anniversaryDao().getAllAnniversaries().first()
                val moments = db.momentDao().getAllMoments().first()
                val categoryConfigs = db.categoryConfigDao().getAllCategories().first()
                val customTags = db.customTagDao().getAllTags().first()
                val categoryMappings = db.categoryMappingDao().getAllMappings().first()

                val entityMap: Map<Class<*>, List<*>> = mapOf(
                    Bill::class.java to bills, Wallet::class.java to wallets,
                    RecurringTemplate::class.java to templates, Budget::class.java to budgets,
                    CategoryConfig::class.java to categoryConfigs, CategoryMapping::class.java to categoryMappings,
                    Asset::class.java to assets,
                    Goal::class.java to goals, GoalCheckIn::class.java to goalCheckIns,
                    Anniversary::class.java to anniversaries, Moment::class.java to moments,
                    CustomTag::class.java to customTags
                )

                var totalCount = 0
                var imageCount = 0
                val usageByAssetId = usageRecords.groupBy { it.assetId }
                val usageJsonByAssetId = usageByAssetId.mapValues { (_, records) ->
                    records.joinToString(",", "[", "]") { r ->
                        val m = buildMap<String, kotlinx.serialization.json.JsonElement> {
                            put("usedAt", JsonPrimitive(r.usedAt))
                            put("note", JsonPrimitive(r.note))
                        }
                        JsonObject(m).toString()
                    }
                }

                val extraColumns: Map<Class<*>, List<Pair<String, (Any?) -> Any>>> = mapOf(
                    Asset::class.java to listOf("usageRecords" to { entity: Any? ->
                        val asset = entity as Asset
                        usageJsonByAssetId[asset.id] ?: ""
                    })
                )

                val themeMode = preferencesManager.themeMode.first()
                val defaultBillType = preferencesManager.defaultBillType.first()
                val budgetReminderEnabled = preferencesManager.budgetReminderEnabled.first()
                val prefsJson = JsonObject(buildMap {
                    put("themeMode", JsonPrimitive(themeMode))
                    put("defaultBillType", JsonPrimitive(defaultBillType))
                    put("budgetReminderEnabled", JsonPrimitive(budgetReminderEnabled))
                }).toString()

                val outputStream = context.contentResolver.openOutputStream(uri)
                    ?: return@withContext Result.failure(Exception(context.getString(R.string.export_error_create_file)))
                outputStream.use { os ->
                    ZipOutputStream(BufferedOutputStream(os)).use { zos ->
                        for ((csvName, classes) in CSV_GROUPS) {
                            val active = classes.mapNotNull { clazz ->
                                val typeName = TYPE_NAME_BY_CLASS[clazz] ?: return@mapNotNull null
                                val entities = entityMap[clazz] ?: return@mapNotNull null
                                (typeName to entities).takeIf { it.second.isNotEmpty() }
                            }
                            if (active.isEmpty()) continue
                            totalCount += active.sumOf { (_, list) -> list.size }
                            val csv = buildGroupCsv(active, extraColumns)
                            val data = csv.toByteArray(Charsets.UTF_8)
                            val entry = ZipEntry("$csvName.csv")
                            entry.size = data.size.toLong()
                            zos.putNextEntry(entry)
                            zos.write(data)
                            zos.closeEntry()
                        }

                        val prefsData = prefsJson.toByteArray(Charsets.UTF_8)
                        val prefsEntry = ZipEntry(PREFERENCES_ENTRY)
                        prefsEntry.size = prefsData.size.toLong()
                        zos.putNextEntry(prefsEntry)
                        zos.write(prefsData)
                        zos.closeEntry()

                        for ((name, file) in imageFileMap) {
                            if (!file.exists()) continue
                            val imageBytes = file.readBytes()
                            val imageEntry = ZipEntry("images/$name")
                            imageEntry.size = imageBytes.size.toLong()
                            zos.putNextEntry(imageEntry)
                            zos.write(imageBytes)
                            zos.closeEntry()
                            imageCount++
                        }

                        zos.flush()
                    }
                }
                val msg = if (imageCount > 0) context.getString(R.string.export_success_images, totalCount, imageCount)
                          else context.getString(R.string.export_success, totalCount)
                Result.success(msg)
            } catch (e: AppException) {
                Result.failure(e)
            } catch (e: java.io.IOException) {
                Result.failure(AppException.Io(context.getString(R.string.export_error_io, e.message), e))
            } catch (e: kotlinx.serialization.SerializationException) {
                Result.failure(AppException.Serialization(context.getString(R.string.export_error_serialization, e.message), e))
            } catch (e: Exception) {
                Result.failure(AppException.Unknown(context.getString(R.string.export_error_unknown, e.message), e))
            }
        }
    }

    suspend fun importFromUri(uri: Uri): Result<Int> {
        return withContext(Dispatchers.IO) {
            val tempFile = File(context.cacheDir, "csvimport_${UUID.randomUUID()}.tmp")
            try {
                context.contentResolver.openInputStream(uri)?.use { input ->
                    tempFile.outputStream().use { output -> input.copyTo(output) }
                } ?: return@withContext Result.failure(Exception(context.getString(R.string.export_error_read_file)))

                val zipEntries = mutableMapOf<String, ByteArray>()
                FileInputStream(tempFile).use { fis ->
                    ZipInputStream(BufferedInputStream(fis)).use { zis ->
                        var entry = zis.nextEntry
                        while (entry != null) {
                            if (!entry.isDirectory) {
                                zipEntries[entry.name] = zis.readBytes()
                            }
                            zis.closeEntry()
                            entry = zis.nextEntry
                        }
                    }
                }

                val imagesDir = File(context.filesDir, "images")
                if (!imagesDir.exists()) imagesDir.mkdirs()
                val pathMapping = mutableMapOf<String, String>()

                for ((name, bytes) in zipEntries) {
                    if (name.startsWith("images/") && name.length > 7) {
                        val filename = name.substringAfter("images/")
                        val destFile = File(imagesDir, filename)
                        destFile.writeBytes(bytes)
                        pathMapping[filename] = destFile.absolutePath
                    }
                }

                val idMaps = mutableMapOf<Class<*>, MutableMap<Long, Long>>()
                var count = 0

                // Wrap all DB writes in a single transaction for atomicity
                db.runInTransaction {
                    kotlinx.coroutines.runBlocking {
                        for ((filename, bytes) in zipEntries) {
                            if (filename.startsWith("images/") || !filename.endsWith(".csv")) continue
                            val rows = csvToRows(String(bytes, Charsets.UTF_8))
                            if (rows.isEmpty()) continue
                            for (row in rows) {
                                val clazz = CLASS_BY_TYPE_NAME[row["实体类型"]] ?: continue
                                val result = insertRow(row, clazz, pathMapping)
                                if (result != null) {
                                    val (oldId, newId) = result
                                    if (oldId != newId) {
                                        idMaps.getOrPut(clazz) { mutableMapOf() }[oldId] = newId
                                    }
                                    count++
                                }
                            }
                        }

                        if (idMaps.isNotEmpty()) {
                            updateCrossReferences(idMaps)
                        }
                    }
                }

                if (count > 0) zipEntries[PREFERENCES_ENTRY]?.let { bytes ->
                    try {
                        val prefsObj = json.parseToJsonElement(String(bytes, Charsets.UTF_8)).jsonObject
                        prefsObj["themeMode"]?.let { v ->
                            val value = (v as? JsonPrimitive)?.contentOrNull ?: v.toString()
                            preferencesManager.setThemeMode(value)
                        }
                        prefsObj["defaultBillType"]?.let { v ->
                            val value = (v as? JsonPrimitive)?.contentOrNull ?: v.toString()
                            preferencesManager.setDefaultBillType(value)
                        }
                        prefsObj["budgetReminderEnabled"]?.let { v ->
                            val str = (v as? JsonPrimitive)?.contentOrNull ?: v.toString()
                            val enabled = str == "true" || str == "是"
                            preferencesManager.setBudgetReminderEnabled(enabled)
                        }
                    } catch (e: Exception) { Log.e("CsvDataExporter", "Import preferences failed", e) }
                }

                Result.success(count)
            } catch (e: AppException) {
                Result.failure(e)
            } catch (e: java.io.IOException) {
                Result.failure(AppException.Io(context.getString(R.string.import_error_io, e.message), e))
            } catch (e: kotlinx.serialization.SerializationException) {
                Result.failure(AppException.Serialization(context.getString(R.string.import_error_parse, e.message), e))
            } catch (e: Exception) {
                Result.failure(AppException.Unknown(context.getString(R.string.import_error_unknown, e.message), e))
            } finally {
                tempFile.delete()
            }
        }
    }

    // ── Group CSV (one file per category, merged entities with "类型" column) ──

    private val entityFieldMaps: Map<Class<*>, Map<String, java.lang.reflect.Field>> by lazy {
        ENTITY_CLASSES.associateWith { clazz ->
            clazz.declaredFields
                .filter { !Modifier.isStatic(it.modifiers) && !it.name.startsWith("$") && it.name != "serialVersionUID" }
                .onEach { it.isAccessible = true }
                .associateBy { it.name }
        }
    }

    private val COMMON_PREFIX: Map<Class<*>, List<String>> = mapOf(
        Asset::class.java to listOf(
            "name", "category", "subCategory", "brand", "model",
            "quantity", "purchasePrice", "acquisitionType", "acquisitionDate",
            "status", "condition", "serialNumber",
            "location", "room"
        ),
        Bill::class.java to listOf(
            "amount", "type", "date", "category", "subCategory",
            "note", "paymentMethod", "merchant", "location", "timeOfDay", "tags"
        ),
        Wallet::class.java to listOf(
            "name", "type", "currentBalance", "initialBalance",
            "bankName", "cardNumber", "currency"
        ),
        Goal::class.java to listOf(
            "title", "goalType", "category", "totalCount", "currentCount",
            "unit", "deadline", "startDate", "priority"
        ),
        Anniversary::class.java to listOf(
            "title", "solarDate", "isLunar", "type", "personName", "personRelation"
        ),
        Moment::class.java to listOf(
            "content", "timestamp", "title", "mood", "weather", "temperature",
            "location", "tags", "category", "privacy"
        ),
        GoalCheckIn::class.java to listOf(
            "goalId", "date", "count", "mood", "duration", "note"
        ),
        RecurringTemplate::class.java to listOf(
            "name", "amount", "type", "category", "frequency", "note"
        ),
        Budget::class.java to listOf(
            "totalBudget", "reminderThreshold",
            "reminderAtThreshold", "reminderOverBudget"
        ),
        CategoryConfig::class.java to listOf(
            "type", "name", "icon", "color", "sortOrder", "isEnabled"
        ),
        CustomTag::class.java to listOf(
            "name", "color", "usageCount", "applicableTypes"
        ),
        CategoryMapping::class.java to listOf(
            "assetCategory", "billCategory", "isDefault"
        )
    )

    private fun reorderFields(fields: Iterable<String>, clazz: Class<*>): List<String> {
        val prefix = COMMON_PREFIX[clazz].orEmpty()
        val set = fields.toSet()
        return prefix.filter { it in set } + (set - prefix.toSet()).toList()
    }

    private fun buildGroupCsv(
        groupEntries: List<Pair<String, List<*>>>,
        extraColumns: Map<Class<*>, List<Pair<String, (Any?) -> Any>>> = emptyMap()
    ): String {
        val allFields = linkedSetOf<String>()
        val classExtraCols = mutableMapOf<Class<*>, List<Pair<String, (Any?) -> Any>>>()
        for ((_, entities) in groupEntries) {
            if (entities.isEmpty()) continue
            val clazz = (entities.first() ?: continue)::class.java
            entityFieldMaps[clazz]?.keys
                ?.filter { it !in (EXCLUDED_FIELDS[clazz].orEmpty()) }
                ?.let { reorderFields(it, clazz) }
                ?.let { allFields.addAll(it) }
            extraColumns[clazz]?.let { cols ->
                classExtraCols[clazz] = cols
                allFields.addAll(cols.map { it.first })
            }
        }
        val fieldNames = allFields.toList()
        val headers = listOf("实体类型") + fieldNames.map { FIELD_LABEL_CN[it] ?: it }
        val fieldLookup = headers.map { HEADER_LABEL_TO_FIELD[it] ?: it }

        val sb = StringBuilder("\uFEFF")
        sb.appendLine(headers.joinToString(",") { escapeCsv(it) })
        for ((typeName, entities) in groupEntries) {
            if (entities.isEmpty()) continue
            val clazz = (entities.first() ?: continue)::class.java
            val fieldMap = entityFieldMaps[clazz] ?: continue
            val extraForClass = classExtraCols[clazz].orEmpty()
            val typeNameEsc = escapeCsv(typeName)
            for (entity in entities) {
                val values = fieldLookup.mapIndexed { i, fieldName ->
                    if (i == 0) typeNameEsc
                    else {
                        val extraValDef = extraForClass.firstOrNull { it.first == fieldName }
                        if (extraValDef != null) {
                            valueToCsv(fieldName, extraValDef.second(entity), clazz)
                        } else {
                            val field = fieldMap[fieldName]
                            if (field != null) valueToCsv(fieldName, field.get(entity), clazz) else ""
                        }
                    }
                }
                sb.appendLine(values.joinToString(","))
            }
        }
        return sb.toString()
    }

    private fun valueToCsv(fieldName: String, value: Any?, entityClass: Class<*>): String {
        return when {
            value == null -> ""
            value is Boolean -> if (value) "是" else "否"
            value is Long && fieldName in DATE_FIELDS -> dateFormatter.format(Instant.ofEpochMilli(value).atZone(ZoneId.systemDefault()))
            value is Number -> value.toString()
            value is String && fieldName == "images" -> processImagesForExport(value)
            value is String && fieldName in LIST_FIELDS -> parseAndJoin(value)
            value is String -> {
                val fieldCnMap = CODE_TO_CN[entityClass]?.get(fieldName)
                if (fieldCnMap != null) escapeCsv(fieldCnMap[value] ?: value)
                else escapeCsv(value)
            }
            else -> escapeCsv(value.toString())
        }
    }

    private fun processImagesForExport(imagesJson: String): String {
        if (imagesJson.isBlank()) return ""
        val paths = try {
            json.decodeFromString<List<String>>(imagesJson)
        } catch (_: Exception) {
            try {
                listOf(imagesJson)
            } catch (_: Exception) {
                null
            }
        } ?: return escapeCsv(imagesJson) // fallback: keep original text

        val names = paths.map { path ->
            val file = File(path)
            if (file.exists()) {
                val name = "${IMAGE_PREFIX}${UUID.randomUUID()}.jpg"
                imageFileMap[name] = file
                name
            } else {
                "${IMAGE_PREFIX}${UUID.randomUUID()}.jpg"
            }
        }
        return if (names.isEmpty()) "" else escapeCsv(names.joinToString("|"))
    }

    private fun parseAndJoin(jsonStr: String): String {
        if (jsonStr.isBlank()) return ""
        return try {
            val list = json.decodeFromString<List<String>>(jsonStr)
            if (list.isEmpty()) "" else escapeCsv(list.joinToString("|"))
        } catch (_: Exception) {
            escapeCsv(jsonStr)
        }
    }

    private fun escapeCsv(value: String): String {
        return if (value.contains(',') || value.contains('"') || value.contains('\n') || value.contains('\r')) {
            "\"${value.replace("\"", "\"\"")}\""
        } else value
    }

    // ── CSV parsing ──

    private val HEADER_LABEL_TO_FIELD: Map<String, String> by lazy {
        FIELD_LABEL_CN.entries.associate { (field, label) -> label to field }
    }

    private fun csvToRows(csv: String): List<Map<String, String>> {
        val clean = csv.removePrefix("\uFEFF")
        val lines = clean.lines().filter { it.isNotBlank() }
        if (lines.size < 2) return emptyList()
        val rawHeaders = parseCsvLine(lines[0])
        val headers = rawHeaders.map { HEADER_LABEL_TO_FIELD[it] ?: it }
        return lines.drop(1).map { line ->
            val values = parseCsvLine(line)
            headers.mapIndexed { i, h -> h to (values.getOrElse(i) { "" }) }.toMap()
        }
    }

    private fun parseCsvLine(line: String): List<String> {
        val result = mutableListOf<String>()
        val current = StringBuilder()
        var inQuotes = false
        var i = 0
        while (i < line.length) {
            val ch = line[i]
            when {
                ch == '"' && !inQuotes -> inQuotes = true
                ch == '"' && inQuotes -> {
                    if (i + 1 < line.length && line[i + 1] == '"') {
                        current.append('"')
                        i++
                    } else {
                        inQuotes = false
                    }
                }
                ch == ',' && !inQuotes -> {
                    result.add(current.toString())
                    current.clear()
                }
                else -> current.append(ch)
            }
            i++
        }
        result.add(current.toString())
        return result
    }

    private val CLASS_BY_TYPE_NAME: Map<String, Class<*>> = mapOf(
        "物品" to Asset::class.java,
        "账单" to Bill::class.java,
        "钱包" to Wallet::class.java,
        "目标" to Goal::class.java,
        "纪念日" to Anniversary::class.java,
        "瞬间" to Moment::class.java,
        "打卡记录" to GoalCheckIn::class.java,
        "周期模板" to RecurringTemplate::class.java,
        "预算" to Budget::class.java,
        "分类配置" to CategoryConfig::class.java,
        "标签" to CustomTag::class.java,
        "分类映射" to CategoryMapping::class.java
    )

    private val CSV_GROUPS: List<Pair<String, List<Class<*>>>> = listOf(
        "记账" to listOf(Bill::class.java, Wallet::class.java, RecurringTemplate::class.java, Budget::class.java, CategoryConfig::class.java, CategoryMapping::class.java),
        "物品" to listOf(Asset::class.java),
        "生活" to listOf(Goal::class.java, GoalCheckIn::class.java, Anniversary::class.java, Moment::class.java, CustomTag::class.java)
    )

    private val TYPE_NAME_BY_CLASS: Map<Class<*>, String> by lazy {
        CLASS_BY_TYPE_NAME.entries.associate { (name, clazz) -> clazz to name }
    }

    private suspend fun insertRow(row: Map<String, String>, clazz: Class<*>, pathMapping: Map<String, String>): Pair<Long, Long>? {
        val translatedRow = translateRow(row, clazz)
        return INSERT_HANDLER[clazz]?.invoke(translatedRow, pathMapping)
    }

    private fun translateRow(row: Map<String, String>, entityClass: Class<*>): Map<String, String> {
        val cnToCodeFields = CN_TO_CODE[entityClass] ?: return row
        return row.mapValues { (key, value) ->
            val reverseMap = cnToCodeFields[key]
            if (reverseMap != null) reverseMap[value] ?: value else value
        }
    }

    private val INSERT_HANDLER: Map<Class<*>, suspend (Map<String, String>, Map<String, String>) -> Pair<Long, Long>?> = mapOf(
        Asset::class.java to { r, pm -> rowToAsset(r, pm)?.let { a ->
            val oldId = a.id
            val newId = db.assetDao().insertAsset(a)
            r["usageRecords"]?.let { usageRecordsJson ->
                if (usageRecordsJson.isNotBlank()) try {
                    val records = json.parseToJsonElement(usageRecordsJson).jsonArray
                    records.forEach { element ->
                        val rec = element.jsonObject
                        val usedAt = (rec["usedAt"] as? JsonPrimitive)?.let {
                            try { it.content.toLong() } catch (_: Exception) { null }
                        } ?: System.currentTimeMillis()
                        val note = (rec["note"] as? JsonPrimitive)?.contentOrNull ?: ""
                        db.usageRecordDao().insertUsageRecord(UsageRecord(assetId = newId, usedAt = usedAt, note = note))
                    }
                } catch (e: Exception) { Log.e("CsvDataExporter", "Import usage records failed", e) }
            }
            oldId to newId
        } },
        Bill::class.java to { r, pm -> rowToBill(r, pm)?.let { b ->
            val oldId = b.id
            val newId = db.billDao().insertBill(b)
            oldId to newId
        } },
        Wallet::class.java to { r, _ -> rowToWallet(r)?.let { w ->
            val oldId = w.id
            val newId = db.walletDao().insert(w)
            oldId to newId
        } },
        Goal::class.java to { r, _ -> rowToGoal(r)?.let { g ->
            val oldId = g.id
            val newId = db.goalDao().insertGoal(g)
            oldId to newId
        } },
        Anniversary::class.java to { r, _ -> rowToAnniversary(r)?.let { a ->
            val oldId = a.id
            val newId = db.anniversaryDao().insertAnniversary(a)
            oldId to newId
        } },
        Moment::class.java to { r, pm -> rowToMoment(r, pm)?.let { m ->
            val oldId = m.id
            val newId = db.momentDao().insertMoment(m)
            oldId to newId
        } },
        GoalCheckIn::class.java to { r, _ -> rowToGoalCheckIn(r)?.let { g ->
            val oldId = g.id
            val newId = db.goalCheckInDao().insertCheckIn(g)
            oldId to newId
        } },
        RecurringTemplate::class.java to { r, _ -> rowToRecurringTemplate(r)?.let { t ->
            val oldId = t.id
            val newId = db.recurringTemplateDao().insertTemplate(t)
            oldId to newId
        } },
        Budget::class.java to { r, _ -> rowToBudget(r)?.let { b ->
            val oldId = b.id
            val newId = db.budgetDao().insertBudget(b)
            oldId to newId
        } },
        CategoryConfig::class.java to { r, _ -> rowToCategoryConfig(r)?.let { c ->
            val oldId = c.id
            val newId = db.categoryConfigDao().insert(c)
            oldId to newId
        } },
        CustomTag::class.java to { r, _ -> rowToCustomTag(r)?.let { t ->
            val oldId = t.id
            val newId = db.customTagDao().insert(t)
            oldId to newId
        } },
        CategoryMapping::class.java to { r, _ -> rowToCategoryMapping(r)?.let { m ->
            val oldId = m.id
            val newId = db.categoryMappingDao().insertMapping(m)
            oldId to newId
        } }
    )

    // ── Row-to-entity converters ──

    private fun rowToAsset(row: Map<String, String>, pathMapping: Map<String, String>): Asset? {
        val (isDeleted, deletedAt) = parseDeletedInfo(row)
        return try {
            Asset(
                id = row["id"]?.toLongOrNull() ?: 0,
                name = row["name"] ?: return null,
                category = row["category"] ?: "",
                subCategory = row["subCategory"] ?: "",
                brand = row["brand"] ?: "",
                model = row["model"] ?: "",
                purchasePrice = row["purchasePrice"]?.toDoubleOrNull() ?: 0.0,
                acquisitionType = row["acquisitionType"] ?: "PURCHASE",
                acquisitionDate = parseDateOrNull(row["acquisitionDate"]),
                quantity = row["quantity"]?.toIntOrNull()?.coerceAtLeast(1) ?: 1,
                status = row["status"] ?: "HELD",
                costMode = row["costMode"] ?: "DAILY",
                useCount = row["useCount"]?.toIntOrNull() ?: 0,
                totalUsageHours = row["totalUsageHours"]?.toDoubleOrNull() ?: 0.0,
                location = row["location"] ?: "",
                room = row["room"] ?: "",
                purchaseChannel = row["purchaseChannel"] ?: "",
                warrantyExpireDate = parseDateOrNull(row["warrantyExpireDate"]),
                insuranceExpireDate = parseDateOrNull(row["insuranceExpireDate"]),
                insuranceCompany = row["insuranceCompany"] ?: "",
                insurancePolicyNo = row["insurancePolicyNo"] ?: "",
                images = resolveImages(row["images"], pathMapping),
                description = row["description"] ?: "",
                condition = row["condition"] ?: "GOOD",
                serialNumber = row["serialNumber"] ?: "",
                receiptPath = row["receiptPath"] ?: "",
                depreciationRate = row["depreciationRate"]?.toDoubleOrNull() ?: 0.0,
                currentValue = row["currentValue"]?.toDoubleOrNull() ?: 0.0,
                maintenanceIntervalDays = row["maintenanceIntervalDays"]?.toIntOrNull() ?: 0,
                lastMaintenanceDate = parseDateOrNull(row["lastMaintenanceDate"]),
                nextMaintenanceDate = parseDateOrNull(row["nextMaintenanceDate"]),
                maintenanceNotes = row["maintenanceNotes"] ?: "",
                isFavorite = row["isFavorite"].toBoolean(),
                tags = joinToJson(row["tags"]),
                linkedBillId = row["linkedBillId"]?.toLongOrNull(),
                linkedMomentId = row["linkedMomentId"]?.toLongOrNull(),
                retireDate = parseDateOrNull(row["retireDate"]),
                retireReason = row["retireReason"] ?: "",
                lostDate = parseDateOrNull(row["lostDate"]),
                lostReason = row["lostReason"] ?: "",
                soldDate = parseDateOrNull(row["soldDate"]),
                soldPrice = row["soldPrice"]?.toDoubleOrNull(),
                soldChannel = row["soldChannel"],
                soldToWhom = row["soldToWhom"],
                sortOrder = row["sortOrder"]?.toIntOrNull() ?: 0,
                isDeleted = isDeleted,
                deletedAt = deletedAt,
                createdAt = parseDateOrNull(row["createdAt"]) ?: System.currentTimeMillis(),
                updatedAt = parseDateOrNull(row["updatedAt"]) ?: System.currentTimeMillis()
            )
        } catch (_: Exception) { null }
    }

    private fun rowToBill(row: Map<String, String>, pathMapping: Map<String, String>): Bill? {
        val (isDeleted, deletedAt) = parseDeletedInfo(row)
        val billDate = parseDateOrNull(row["date"]) ?: return null
        return try {
            Bill(
                id = row["id"]?.toLongOrNull() ?: 0,
                amount = row["amount"]?.toDoubleOrNull() ?: return null,
                type = row["type"] ?: return null,
                category = row["category"] ?: "",
                subCategory = row["subCategory"] ?: "",
                note = row["note"] ?: "",
                date = billDate,
                yearMonth = row["yearMonth"] ?: yearMonthFormatter.format(java.time.Instant.ofEpochMilli(billDate).atZone(java.time.ZoneId.systemDefault())),
                timeOfDay = row["timeOfDay"] ?: "",
                walletId = row["walletId"]?.toLongOrNull(),
                toWalletId = row["toWalletId"]?.toLongOrNull(),
                paymentMethod = row["paymentMethod"] ?: "",
                merchant = row["merchant"] ?: "",
                location = row["location"] ?: "",
                tags = joinToJson(row["tags"]),
                images = resolveImages(row["images"], pathMapping),
                linkedAssetId = row["linkedAssetId"]?.toLongOrNull(),
                linkType = row["linkType"],
                recurringId = row["recurringId"]?.toLongOrNull(),
                recurringFrequency = row["recurringFrequency"] ?: "",
                splitGroupId = row["splitGroupId"] ?: "",
                isReimbursable = row["isReimbursable"].toBoolean(),
                isReimbursed = row["isReimbursed"].toBoolean(),
                reimbursedDate = parseDateOrNull(row["reimbursedDate"]),
                isTaxDeductible = row["isTaxDeductible"].toBoolean(),
                latitude = row["latitude"]?.toDoubleOrNull(),
                longitude = row["longitude"]?.toDoubleOrNull(),
                isAutoGenerated = row["isAutoGenerated"].toBoolean(),
                isDeleted = isDeleted,
                deletedAt = deletedAt,
                createdAt = parseDateOrNull(row["createdAt"]) ?: System.currentTimeMillis(),
                updatedAt = parseDateOrNull(row["updatedAt"]) ?: System.currentTimeMillis()
            )
        } catch (_: Exception) { null }
    }

    private fun rowToWallet(row: Map<String, String>): Wallet? {
        val (isDeleted, _) = parseDeletedInfo(row)
        return try {
            Wallet(
                id = row["id"]?.toLongOrNull() ?: 0,
                name = row["name"] ?: return null,
                type = row["type"] ?: "CASH",
                icon = AppIcon.fromName(row["icon"] ?: "Payments"),
                color = row["color"] ?: "#4CAF50",
                bankName = row["bankName"] ?: "",
                cardNumber = row["cardNumber"] ?: "",
                initialBalance = row["initialBalance"]?.toDoubleOrNull() ?: 0.0,
                currentBalance = row["currentBalance"]?.toDoubleOrNull() ?: 0.0,
                currency = row["currency"] ?: "CNY",
                isDefault = row["isDefault"].toBoolean(),
                isEnabled = row["isEnabled"].toBoolean(),
                sortOrder = row["sortOrder"]?.toIntOrNull() ?: 0,
                description = row["description"] ?: "",
                isDeleted = isDeleted,
                createdAt = parseDateOrNull(row["createdAt"]) ?: System.currentTimeMillis(),
                updatedAt = parseDateOrNull(row["updatedAt"]) ?: System.currentTimeMillis()
            )
        } catch (_: Exception) { null }
    }

    private fun rowToGoal(row: Map<String, String>): Goal? {
        val (isDeleted, deletedAt) = parseDeletedInfo(row)
        return try {
            Goal(
                id = row["id"]?.toLongOrNull() ?: 0,
                title = row["title"] ?: return null,
                description = row["description"] ?: "",
                category = row["category"] ?: "",
                goalType = row["goalType"] ?: "CUMULATIVE",
                totalCount = row["totalCount"]?.toIntOrNull() ?: 100,
                currentCount = row["currentCount"]?.toIntOrNull() ?: 0,
                unit = row["unit"] ?: "次",
                frequency = row["frequency"] ?: "",
                targetPerPeriod = row["targetPerPeriod"]?.toIntOrNull() ?: 0,
                currentPeriodCount = row["currentPeriodCount"]?.toIntOrNull() ?: 0,
                periodStartDate = parseDateOrNull(row["periodStartDate"]),
                deadline = parseDateOrNull(row["deadline"]),
                startDate = parseDateOrNull(row["startDate"]) ?: System.currentTimeMillis(),
                priority = row["priority"] ?: "MEDIUM",
                color = row["color"] ?: "",
                icon = AppIcon.fromName(row["icon"] ?: "Flag"),
                streak = row["streak"]?.toIntOrNull() ?: 0,
                longestStreak = row["longestStreak"]?.toIntOrNull() ?: 0,
                lastCheckInDate = parseDateOrNull(row["lastCheckInDate"]),
                totalCheckInDays = row["totalCheckInDays"]?.toIntOrNull() ?: 0,
                reminderEnabled = row["reminderEnabled"].toBoolean(),
                reminderTime = row["reminderTime"] ?: "",
                linkedAssetId = row["linkedAssetId"]?.toLongOrNull(),
                isPublic = row["isPublic"].toBoolean(),
                notes = row["notes"] ?: "",
                isDeleted = isDeleted,
                deletedAt = deletedAt,
                createdAt = parseDateOrNull(row["createdAt"]) ?: System.currentTimeMillis(),
                updatedAt = parseDateOrNull(row["updatedAt"]) ?: System.currentTimeMillis()
            )
        } catch (_: Exception) { null }
    }

    private fun rowToAnniversary(row: Map<String, String>): Anniversary? {
        val (isDeleted, deletedAt) = parseDeletedInfo(row)
        return try {
            Anniversary(
                id = row["id"]?.toLongOrNull() ?: 0,
                title = row["title"] ?: return null,
                description = row["description"] ?: "",
                solarDate = parseDateOrNull(row["solarDate"]) ?: return null,
                isLunar = row["isLunar"].toBoolean(),
                lunarYear = row["lunarYear"]?.toIntOrNull(),
                lunarMonth = row["lunarMonth"]?.toIntOrNull(),
                lunarDay = row["lunarDay"]?.toIntOrNull(),
                lunarLeapMonth = row["lunarLeapMonth"].toBoolean(),
                type = row["type"] ?: "OTHER",
                personName = row["personName"] ?: "",
                personRelation = row["personRelation"] ?: "",
                isYearly = row["isYearly"].toBoolean(),
                displayMode = row["displayMode"] ?: "COUNT_UP",
                multiRemindJson = joinToJson(row["multiRemindJson"]),
                reminderTime = row["reminderTime"] ?: "09:00",
                notificationEnabled = row["notificationEnabled"].toBoolean(),
                color = row["color"] ?: "",
                icon = AppIcon.fromName(row["icon"] ?: "Favorite"),
                linkedMomentId = row["linkedMomentId"]?.toLongOrNull(),
                isPinned = row["isPinned"].toBoolean(),
                isDeleted = isDeleted,
                deletedAt = deletedAt,
                createdAt = parseDateOrNull(row["createdAt"]) ?: System.currentTimeMillis(),
                updatedAt = parseDateOrNull(row["updatedAt"]) ?: System.currentTimeMillis()
            )
        } catch (_: Exception) { null }
    }

    private fun rowToMoment(row: Map<String, String>, pathMapping: Map<String, String>): Moment? {
        val (isDeleted, deletedAt) = parseDeletedInfo(row)
        return try {
            Moment(
                id = row["id"]?.toLongOrNull() ?: 0,
                title = row["title"] ?: "",
                content = row["content"] ?: return null,
                timestamp = parseDateOrNull(row["timestamp"]) ?: parseDateOrNull(row["date"]) ?: System.currentTimeMillis(),
                images = resolveImages(row["images"], pathMapping),
                videoPath = row["videoPath"] ?: "",
                audioPath = row["audioPath"] ?: "",
                mood = row["mood"] ?: "",
                weather = row["weather"] ?: "",
                temperature = row["temperature"]?.toIntOrNull() ?: Int.MIN_VALUE,
                location = row["location"] ?: "",
                latitude = row["latitude"]?.toDoubleOrNull(),
                longitude = row["longitude"]?.toDoubleOrNull(),
                tags = joinToJson(row["tags"]),
                category = row["category"] ?: "",
                privacy = row["privacy"] ?: "PRIVATE",
                isPinned = row["isPinned"].toBoolean(),
                isFavorite = row["isFavorite"].toBoolean(),
                wordCount = row["wordCount"]?.toIntOrNull() ?: 0,
                linkedAssetId = row["linkedAssetId"]?.toLongOrNull(),
                linkedAnniversaryId = row["linkedAnniversaryId"]?.toLongOrNull(),
                linkedGoalId = row["linkedGoalId"]?.toLongOrNull(),
                isDeleted = isDeleted,
                deletedAt = deletedAt,
                createdAt = parseDateOrNull(row["createdAt"]) ?: System.currentTimeMillis(),
                updatedAt = parseDateOrNull(row["updatedAt"]) ?: System.currentTimeMillis()
            )
        } catch (_: Exception) { null }
    }

    private fun rowToGoalCheckIn(row: Map<String, String>): GoalCheckIn? {
        return try {
            GoalCheckIn(
                id = row["id"]?.toLongOrNull() ?: 0,
                goalId = row["goalId"]?.toLongOrNull() ?: return null,
                date = parseDateOrNull(row["date"]) ?: return null,
                count = row["count"]?.toIntOrNull() ?: 1,
                note = row["note"] ?: "",
                mood = row["mood"] ?: "",
                duration = row["duration"]?.toIntOrNull() ?: 0,
                createdAt = parseDateOrNull(row["createdAt"]) ?: System.currentTimeMillis()
            )
        } catch (_: Exception) { null }
    }

    private fun rowToRecurringTemplate(row: Map<String, String>): RecurringTemplate? {
        val (isDeleted, _) = parseDeletedInfo(row)
        return try {
            RecurringTemplate(
                id = row["id"]?.toLongOrNull() ?: 0,
                name = row["name"] ?: return null,
                amount = row["amount"]?.toDoubleOrNull() ?: return null,
                type = row["type"] ?: return null,
                category = row["category"] ?: "",
                frequency = row["frequency"] ?: return null,
                dayOfMonth = row["dayOfMonth"]?.toIntOrNull() ?: 0,
                dayOfWeek = row["dayOfWeek"]?.toIntOrNull() ?: 0,
                isActive = row["isActive"].toBoolean(),
                lastGeneratedDate = parseDateOrNull(row["lastGeneratedDate"]),
                nextGenerateDate = parseDateOrNull(row["nextGenerateDate"]),
                autoGenerate = row["autoGenerate"].toBoolean(),
                remindBeforeDays = row["remindBeforeDays"]?.toIntOrNull() ?: 1,
                note = row["note"] ?: "",
                isDeleted = isDeleted,
                createdAt = parseDateOrNull(row["createdAt"]) ?: System.currentTimeMillis(),
                updatedAt = parseDateOrNull(row["updatedAt"]) ?: System.currentTimeMillis()
            )
        } catch (_: Exception) { null }
    }

    private fun rowToBudget(row: Map<String, String>): Budget? {
        return try {
            Budget(
                id = row["id"]?.toLongOrNull() ?: 0,
                yearMonth = row["yearMonth"] ?: return null,
                totalBudget = row["totalBudget"]?.toDoubleOrNull() ?: return null,
                reminderThreshold = row["reminderThreshold"]?.toDoubleOrNull() ?: 0.8,
                reminderAtThreshold = row["reminderAtThreshold"].toBoolean(),
                reminderOverBudget = row["reminderOverBudget"].toBoolean(),
                createdAt = parseDateOrNull(row["createdAt"]) ?: System.currentTimeMillis(),
                updatedAt = parseDateOrNull(row["updatedAt"]) ?: System.currentTimeMillis()
            )
        } catch (_: Exception) { null }
    }

    private fun rowToCategoryConfig(row: Map<String, String>): CategoryConfig? {
        return try {
            CategoryConfig(
                id = row["id"]?.toLongOrNull() ?: 0,
                type = row["type"] ?: return null,
                name = row["name"] ?: return null,
                icon = AppIcon.fromName(row["icon"] ?: "Settings"),
                color = row["color"] ?: "",
                sortOrder = row["sortOrder"]?.toIntOrNull() ?: 0,
                isDefault = row["isDefault"].toBoolean(),
                isEnabled = row["isEnabled"].toBoolean(),
                parentId = row["parentId"]?.toLongOrNull(),
                description = row["description"] ?: "",
                createdAt = parseDateOrNull(row["createdAt"]) ?: System.currentTimeMillis(),
                updatedAt = parseDateOrNull(row["updatedAt"]) ?: System.currentTimeMillis()
            )
        } catch (_: Exception) { null }
    }

    private fun rowToCustomTag(row: Map<String, String>): CustomTag? {
        val (isDeleted, _) = parseDeletedInfo(row)
        return try {
            CustomTag(
                id = row["id"]?.toLongOrNull() ?: 0,
                name = row["name"] ?: return null,
                color = row["color"] ?: "",
                icon = AppIcon.fromName(row["icon"] ?: "Flag"),
                usageCount = row["usageCount"]?.toIntOrNull() ?: 0,
                applicableTypes = joinToJson(row["applicableTypes"]),
                isDeleted = isDeleted,
                createdAt = parseDateOrNull(row["createdAt"]) ?: System.currentTimeMillis(),
                updatedAt = parseDateOrNull(row["updatedAt"]) ?: System.currentTimeMillis()
            )
        } catch (_: Exception) { null }
    }

    private fun rowToCategoryMapping(row: Map<String, String>): CategoryMapping? {
        return try {
            CategoryMapping(
                id = row["id"]?.toLongOrNull() ?: 0,
                assetCategory = row["assetCategory"] ?: return null,
                billCategory = row["billCategory"] ?: return null,
                isDefault = row["isDefault"].toBoolean(),
                createdAt = parseDateOrNull(row["createdAt"]) ?: System.currentTimeMillis(),
                updatedAt = parseDateOrNull(row["updatedAt"]) ?: System.currentTimeMillis()
            )
        } catch (_: Exception) { null }
    }

    // ── Value converters ──

    private fun parseDeletedInfo(row: Map<String, String>): Pair<Boolean, Long?> {
        val isDeleted = row["isDeleted"].toBoolean()
        return isDeleted to (if (isDeleted) parseDateOrNull(row["deletedAt"]) else null)
    }

    private fun parseDateOrNull(value: String?): Long? {
        if (value.isNullOrBlank()) return null
        return try {
            value.toLong()
        } catch (_: NumberFormatException) {
            try {
                LocalDateTime.parse(value, dateFormatter).atZone(ZoneId.systemDefault()).toInstant().toEpochMilli()
            } catch (_: Exception) {
                null
            }
        }
    }

    private fun resolveImages(csvValue: String?, pathMapping: Map<String, String>): String {
        if (csvValue.isNullOrBlank()) return ""
        val names = csvValue.split("|").map { it.trim() }.filter { it.isNotEmpty() }
        if (names.isEmpty()) return ""
        val paths = names.map { pathMapping[it] ?: it }
        return json.encodeToString(kotlinx.serialization.serializer(), paths)
    }

    private fun joinToJson(csvValue: String?): String {
        if (csvValue.isNullOrBlank()) return ""
        val items = csvValue.split("|").map { it.trim() }.filter { it.isNotEmpty() }
        return if (items.isEmpty()) "" else json.encodeToString(kotlinx.serialization.serializer(), items)
    }

    private suspend fun updateCrossReferences(idMaps: Map<Class<*>, Map<Long, Long>>) {
        val assetMap = idMaps[Asset::class.java] ?: emptyMap()
        val billMap = idMaps[Bill::class.java] ?: emptyMap()
        val walletMap = idMaps[Wallet::class.java] ?: emptyMap()
        val goalMap = idMaps[Goal::class.java] ?: emptyMap()
        val anniversaryMap = idMaps[Anniversary::class.java] ?: emptyMap()
        val momentMap = idMaps[Moment::class.java] ?: emptyMap()

        if (assetMap.isNotEmpty()) {
            db.billDao().getAllBills().first().forEach { bill ->
                var updated = false
                var newLinkedAssetId = bill.linkedAssetId
                if (newLinkedAssetId != null && newLinkedAssetId in assetMap) {
                    newLinkedAssetId = assetMap[newLinkedAssetId]
                    updated = true
                }
                if (updated) {
                    db.billDao().updateBill(bill.copy(linkedAssetId = newLinkedAssetId))
                }
            }
            db.momentDao().getAllMoments().first().forEach { moment ->
                var updated = false
                var newLinkedAssetId = moment.linkedAssetId
                if (newLinkedAssetId != null && newLinkedAssetId in assetMap) {
                    newLinkedAssetId = assetMap[newLinkedAssetId]
                    updated = true
                }
                if (updated) {
                    db.momentDao().updateMoment(moment.copy(linkedAssetId = newLinkedAssetId))
                }
            }
            db.goalDao().getAllGoals().first().forEach { goal ->
                var updated = false
                var newLinkedAssetId = goal.linkedAssetId
                if (newLinkedAssetId != null && newLinkedAssetId in assetMap) {
                    newLinkedAssetId = assetMap[newLinkedAssetId]
                    updated = true
                }
                if (updated) {
                    db.goalDao().updateGoal(goal.copy(linkedAssetId = newLinkedAssetId))
                }
            }
        }

        if (billMap.isNotEmpty()) {
            db.assetDao().getAllAssets().first().forEach { asset ->
                var updated = false
                var newLinkedBillId = asset.linkedBillId
                if (newLinkedBillId != null && newLinkedBillId in billMap) {
                    newLinkedBillId = billMap[newLinkedBillId]
                    updated = true
                }
                if (updated) {
                    db.assetDao().updateAsset(asset.copy(linkedBillId = newLinkedBillId))
                }
            }
        }

        if (walletMap.isNotEmpty()) {
            db.billDao().getAllBills().first().forEach { bill ->
                var updated = false
                var newWalletId = bill.walletId
                var newToWalletId = bill.toWalletId
                if (newWalletId != null && newWalletId in walletMap) {
                    newWalletId = walletMap[newWalletId]
                    updated = true
                }
                if (newToWalletId != null && newToWalletId in walletMap) {
                    newToWalletId = walletMap[newToWalletId]
                    updated = true
                }
                if (updated) {
                    db.billDao().updateBill(bill.copy(walletId = newWalletId, toWalletId = newToWalletId))
                }
            }
        }

        if (goalMap.isNotEmpty()) {
            for ((oldId, newId) in goalMap) {
                db.goalCheckInDao().getCheckInsByGoal(oldId).first().forEach { checkIn ->
                    db.goalCheckInDao().updateCheckIn(checkIn.copy(goalId = newId))
                }
            }
            db.momentDao().getAllMoments().first().forEach { moment ->
                var updated = false
                var newLinkedGoalId = moment.linkedGoalId
                if (newLinkedGoalId != null && newLinkedGoalId in goalMap) {
                    newLinkedGoalId = goalMap[newLinkedGoalId]
                    updated = true
                }
                if (updated) {
                    db.momentDao().updateMoment(moment.copy(linkedGoalId = newLinkedGoalId))
                }
            }
        }

        if (anniversaryMap.isNotEmpty()) {
            db.momentDao().getAllMoments().first().forEach { moment ->
                var updated = false
                var newLinkedAnniversaryId = moment.linkedAnniversaryId
                if (newLinkedAnniversaryId != null && newLinkedAnniversaryId in anniversaryMap) {
                    newLinkedAnniversaryId = anniversaryMap[newLinkedAnniversaryId]
                    updated = true
                }
                if (updated) {
                    db.momentDao().updateMoment(moment.copy(linkedAnniversaryId = newLinkedAnniversaryId))
                }
            }
        }

        if (momentMap.isNotEmpty()) {
            db.assetDao().getAllAssets().first().forEach { asset ->
                var updated = false
                var newLinkedMomentId = asset.linkedMomentId
                if (newLinkedMomentId != null && newLinkedMomentId in momentMap) {
                    newLinkedMomentId = momentMap[newLinkedMomentId]
                    updated = true
                }
                if (updated) {
                    db.assetDao().updateAsset(asset.copy(linkedMomentId = newLinkedMomentId))
                }
            }
            db.anniversaryDao().getAllAnniversaries().first().forEach { anniversary ->
                var updated = false
                var newLinkedMomentId = anniversary.linkedMomentId
                if (newLinkedMomentId != null && newLinkedMomentId in momentMap) {
                    newLinkedMomentId = momentMap[newLinkedMomentId]
                    updated = true
                }
                if (updated) {
                    db.anniversaryDao().updateAnniversary(anniversary.copy(linkedMomentId = newLinkedMomentId))
                }
            }
        }
    }

    private fun String?.toBoolean(): Boolean = this == "是" || this == "true"
}
