package com.palmnote.data.export

import android.content.Context
import android.net.Uri
import com.palmnote.domain.model.AssetStatus
import com.palmnote.domain.model.BillType
import com.palmnote.domain.model.PaymentMethod
import com.palmnote.domain.model.RecurringFrequency
import com.palmnote.domain.util.AppLogger
import com.palmnote.app.R
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.contentOrNull
import com.palmnote.data.db.AppDatabase
import com.palmnote.data.db.entity.*
import com.palmnote.data.datastore.PreferencesManager
import com.palmnote.ui.theme.AppIcon
import androidx.room.withTransaction
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.withContext
import java.io.*
import java.lang.reflect.Modifier
import java.time.Instant
import java.time.LocalDateTime
import java.time.ZoneId
import java.time.format.DateTimeFormatter
import java.util.*
import java.util.zip.ZipEntry
import java.util.zip.ZipInputStream
import java.util.zip.ZipOutputStream
import com.palmnote.domain.model.Money
import com.palmnote.domain.util.AppException

class CsvDataExporter(
    private val context: Context,
    private val db: AppDatabase,
    private val preferencesManager: PreferencesManager
) {
    private val json = Json { ignoreUnknownKeys = true; coerceInputValues = true; encodeDefaults = true }

    companion object {
        /** 全量导入包的体积上限：解压后所有条目驻留内存，给明确报错而不是等 OOM 闪退 */
        private const val MAX_IMPORT_BYTES = 300L * 1024 * 1024

        private val EXCLUDED_FIELDS: Map<Class<*>, Set<String>> = mapOf(
            Asset::class.java to setOf("receiptPath"),
            Bill::class.java to setOf("yearMonth", "isAutoGenerated"),
            Moment::class.java to setOf("videoPath", "audioPath"),
            RecurringTemplate::class.java to setOf("lastGeneratedDate", "nextGenerateDate")
        )

        private val DATE_FIELDS = setOf(
            "date", "deadline", "solarDate", "startDate", "periodStartDate",
            "lastCheckInDate", "usedAt", "acquisitionDate",
            "warrantyExpireDate", "insuranceExpireDate", "lastMaintenanceDate",
            "nextMaintenanceDate", "retireDate", "lostDate", "soldDate",
            "reimbursedDate", "createdAt", "updatedAt"
        )
        private val MONEY_FIELDS = setOf(
            "amount", "purchasePrice", "currentValue", "soldPrice",
            "initialBalance", "currentBalance", "totalBudget", "unitPrice"
        )
        private val LIST_FIELDS = setOf("tags", "applicableTypes", "multiRemindJson")
        private const val IMAGE_PREFIX = "img_"
        private const val PREFERENCES_ENTRY = "preferences.json"
        val ENTITY_CLASSES = listOf(
            Asset::class.java, Bill::class.java, Wallet::class.java,
            Goal::class.java, GoalCheckIn::class.java, Anniversary::class.java,
            Moment::class.java, RecurringTemplate::class.java, Budget::class.java,
            CategoryConfig::class.java, CustomTag::class.java,
            CategoryMapping::class.java
        )

        private val CODE_TO_CN: Map<Class<*>, Map<String, Map<String, String>>> = mapOf(
            Asset::class.java to mapOf(
                "status" to mapOf(AssetStatus.HELD.value to "持有中", AssetStatus.AWAY.value to "暂离中", AssetStatus.REMOVED.value to "已清出"),
                "acquisitionType" to mapOf("PURCHASE" to "购买", "GIFT" to "赠送", "LOTTERY" to "抽奖", "PRIZE" to "奖品", "INHERITANCE" to "继承", "OTHER" to "其他"),
                "condition" to mapOf("NEW" to "全新", "GOOD" to "良好", "FAIR" to "一般", "POOR" to "较差"),
                "costMode" to mapOf("DAILY" to "按天计算", "PER_USE" to "按次计算", "DEPRECIATION" to "折旧")
            ),
            Bill::class.java to mapOf(
                "type" to mapOf(BillType.EXPENSE.value to "支出", BillType.INCOME.value to "收入", BillType.TRANSFER.value to "转账"),
                "paymentMethod" to mapOf("CASH" to "现金", "WECHAT" to "微信", "ALIPAY" to "支付宝", "CARD" to "银行卡", "BANK_TRANSFER" to "银行转账", "OTHER" to "其他"),
                "linkType" to mapOf("PURCHASE" to "购买", "MAINTENANCE" to "维护", "WARRANTY" to "质保", "INSURANCE" to "保险")
            ),
            Wallet::class.java to mapOf(
                "type" to mapOf("CASH" to "现金", "E_WALLET" to "电子钱包", "BANK_CARD" to "银行卡", "CREDIT_CARD" to "信用卡", "INVESTMENT" to "投资账户", "OTHER" to "其他")
            ),
            Goal::class.java to mapOf(
                "priority" to mapOf("HIGH" to "高", "MEDIUM" to "中", "LOW" to "低"),
                "goalType" to mapOf("CUMULATIVE" to "累计", "HABIT" to "习惯", "TARGET" to "目标"),
                "frequency" to mapOf("DAILY" to "每日", "WEEKLY" to "每周", "MONTHLY" to "每月"),
                "category" to mapOf("FITNESS" to "运动", "READING" to "阅读", "SKILL" to "技能", "HABIT" to "习惯", "PROJECT" to "项目", "SAVING" to "储蓄", "CUSTOM" to "自定义")
            ),
            Anniversary::class.java to mapOf(
                "type" to mapOf("BIRTHDAY" to "生日", "WEDDING" to "结婚", "MEETING" to "相识", "GRADUATION" to "毕业", "JOB" to "工作", "TRAVEL" to "旅行", "BABY" to "宝宝", "PET" to "宠物", "CUSTOM" to "自定义")
            ),
            Moment::class.java to mapOf(
                "mood" to mapOf("GREAT" to "开心", "GOOD" to "不错", "OK" to "一般", "BAD" to "难过", "TERRIBLE" to "糟糕"),
                "weather" to mapOf("SUNNY" to "晴", "CLOUDY" to "多云", "RAINY" to "雨", "SNOWY" to "雪", "WINDY" to "风", "FOGGY" to "雾"),
                "privacy" to mapOf("PRIVATE" to "私密", "FRIENDS" to "好友", "PUBLIC" to "公开"),
                "category" to mapOf("TRAVEL" to "旅行", "FOOD" to "美食", "FAMILY" to "家庭", "WORK" to "工作", "FRIEND" to "朋友", "HOBBY" to "爱好", "NATURE" to "自然", "PET" to "宠物", "CUSTOM" to "其他")
            ),
            CategoryConfig::class.java to mapOf(
                "type" to mapOf("ASSET" to "物品", "BILL_EXPENSE" to "支出", "BILL_INCOME" to "收入", "GOAL" to "目标", "ANNIVERSARY" to "纪念日", "MOMENT" to "瞬间", "TAG" to "标签")
            ),
            GoalCheckIn::class.java to mapOf(
                "mood" to mapOf("GREAT" to "开心", "GOOD" to "不错", "OK" to "一般", "BAD" to "难过")
            ),
            RecurringTemplate::class.java to mapOf(
                "type" to mapOf(BillType.EXPENSE.value to "支出", BillType.INCOME.value to "收入"),
                "frequency" to mapOf("DAILY" to "每日", "WEEKLY" to "每周", "MONTHLY" to "每月", "YEARLY" to "每年")
            )
        )

        val CN_TO_CODE: Map<Class<*>, Map<String, Map<String, String>>> by lazy {
            CODE_TO_CN.mapValues { (_, fieldMap) ->
                fieldMap.mapValues { (_, codeMap) ->
                    codeMap.entries.associate { (code, cn) -> cn to code }
                }
            }
        }

        val FIELD_LABEL_CN: Map<String, String> = mapOf(
            "id" to "编号", "name" to "名称", "type" to "类型",
            "category" to "分类", "subCategory" to "子分类",
            "color" to "颜色", "icon" to "图标", "description" to "描述",
            "createdAt" to "创建时间", "updatedAt" to "更新时间",
            "sortOrder" to "排序", "tags" to "标签", "images" to "图片",
            "note" to "备注", "date" to "日期",
            "brand" to "品牌", "model" to "型号",
            "quantity" to "数量",
            "purchasePrice" to "购买价格",
            "acquisitionType" to "获取方式", "acquisitionDate" to "获取日期",
            "status" to "状态", "costMode" to "计费方式",
            "useCount" to "使用次数", "totalUsageHours" to "使用总时长",
            "location" to "存放位置", "room" to "房间",
            "purchaseChannel" to "购买渠道",
            "warrantyExpireDate" to "保修日期", "insuranceExpireDate" to "保险到期日",
            "insuranceCompany" to "保险公司", "insurancePolicyNo" to "保单号",
            "condition" to "成色", "serialNumber" to "序列号",
            "depreciationRate" to "折旧率", "currentValue" to "现值",
            "maintenanceIntervalDays" to "维护周期", "lastMaintenanceDate" to "上次维护",
            "nextMaintenanceDate" to "下次维护", "maintenanceNotes" to "维护备注",
            "isFavorite" to "收藏", "linkedBillId" to "关联账单",
            "linkedMomentId" to "关联瞬间", "retireDate" to "退役日期",
            "retireReason" to "退役原因", "lostDate" to "丢失日期",
            "lostReason" to "遗失原因", "soldDate" to "售出日期",
            "soldPrice" to "售出价格", "soldChannel" to "售出渠道",
            "soldToWhom" to "售出对象",
            "amount" to "金额", "yearMonth" to "年月",
            "walletId" to "钱包",
            "toWalletId" to "目标钱包", "paymentMethod" to "支付方式",
            "merchant" to "商户名称", "transactionId" to "交易单号", "linkedAssetId" to "关联物品",
            "linkType" to "关联类型",
            "recurringId" to "模板ID", "recurringFrequency" to "周期频率",
            "splitGroupId" to "拆分组ID",
            "isReimbursable" to "可报销", "isReimbursed" to "已报销",
            "reimbursedDate" to "报销日期", "isTaxDeductible" to "可抵税",
            "latitude" to "纬度", "longitude" to "经度",
            "bankName" to "银行名称", "cardNumber" to "卡号",
            "initialBalance" to "初始余额", "currentBalance" to "当前余额",
            "currency" to "币种", "isDefault" to "默认",
            "isEnabled" to "启用",
            "title" to "标题", "goalType" to "目标类型",
            "totalCount" to "目标次数", "currentCount" to "当前次数",
            "unit" to "单位", "frequency" to "频率",
            "targetPerPeriod" to "周期目标", "currentPeriodCount" to "本期完成",
            "periodStartDate" to "周期开始日期", "deadline" to "截止日期",
            "startDate" to "开始日期", "priority" to "优先级",
            "streak" to "连续天数", "longestStreak" to "最长连续",
            "lastCheckInDate" to "上次打卡日期", "totalCheckInDays" to "打卡总天数",
            "reminderEnabled" to "提醒", "reminderTime" to "提醒时间",
            "isPublic" to "公开", "notes" to "备注",
            "goalId" to "目标ID", "count" to "次数",
            "duration" to "时长", "mood" to "心情",
            "solarDate" to "公历日期", "isLunar" to "农历",
            "lunarYear" to "农历年", "lunarMonth" to "农历月",
            "lunarDay" to "农历日", "lunarLeapMonth" to "闰月",
            "personName" to "姓名", "personRelation" to "关系",
            "isYearly" to "每年", "displayMode" to "显示模式",
            "multiRemindJson" to "多次提醒", "notificationEnabled" to "通知",
            "emoji" to "表情", "isPinned" to "置顶",
            "content" to "内容", "timestamp" to "时间",
            "weather" to "天气", "temperature" to "温度",
            "privacy" to "隐私",
            "wordCount" to "字数",
            "linkedAnniversaryId" to "关联纪念日", "linkedGoalId" to "关联目标",
            "dayOfMonth" to "每月几号", "dayOfWeek" to "每周几",
            "isActive" to "激活", "autoGenerate" to "自动生成",
            "totalBudget" to "预算总额", "reminderThreshold" to "提醒阈值",
            "reminderAtThreshold" to "阈值提醒", "reminderOverBudget" to "超支提醒",
            "parentId" to "父分类", "usageCount" to "使用次数",
            "applicableTypes" to "适用类型",
            "assetCategory" to "物品分类", "billCategory" to "账单分类",
            "assetId" to "物品ID", "usedAt" to "使用时间",
            "usageRecords" to "使用记录"
        )
    }

    private val dateFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")
    private val yearMonthFormatter = DateTimeFormatter.ofPattern("yyyy-MM")
    private val imageFileMap = mutableMapOf<String, File>()

    suspend fun exportToUri(uri: Uri, scope: ExportScope = ExportScope.ALL): Result<String> {
        return withContext(Dispatchers.IO) {
            try {
                imageFileMap.clear()
                val wallets = db.walletDao().getAllWallets().first()
                val bills = db.billDao().getAllBills().first()
                val templates = db.recurringTemplateDao().getAllTemplates().first()
                val budgets = db.budgetDao().getAllBudgets().first()
                val assets = db.assetDao().getAllAssets().first()
                val usageRecords = db.usageRecordDao().getAllUsageRecords().first()
                val goals = db.goalDao().getAllGoals().first()
                val goalCheckIns = if (goals.isNotEmpty()) {
                    db.goalCheckInDao().getCheckInsByGoalIds(goals.map { it.id }).first()
                } else {
                    emptyList()
                }
                val anniversaries = db.anniversaryDao().getAllAnniversaries().first()
                val moments = db.momentDao().getAllMoments().first()
                val categoryConfigs = db.categoryConfigDao().getAllCategories().first()
                val customTags = db.customTagDao().getAllTags().first()
                val categoryMappings = db.categoryMappingDao().getAllMappings().first()

                val entityMap: Map<Class<*>, List<*>> = mapOf(
                    Bill::class.java to bills, Wallet::class.java to wallets,
                    RecurringTemplate::class.java to templates, Budget::class.java to budgets,
                    CategoryConfig::class.java to categoryConfigs, CategoryMapping::class.java to categoryMappings,
                    Asset::class.java to assets,
                    Goal::class.java to goals, GoalCheckIn::class.java to goalCheckIns,
                    Anniversary::class.java to anniversaries, Moment::class.java to moments,
                    CustomTag::class.java to customTags
                )

                var totalCount = 0
                var imageCount = 0
                val usageByAssetId = usageRecords.groupBy { it.assetId }
                val usageJsonByAssetId = usageByAssetId.mapValues { (_, records) ->
                    records.joinToString(",", "[", "]") { r ->
                        val m = buildMap<String, kotlinx.serialization.json.JsonElement> {
                            put("usedAt", JsonPrimitive(r.usedAt))
                            put("note", JsonPrimitive(r.note))
                        }
                        JsonObject(m).toString()
                    }
                }

                val extraColumns: Map<Class<*>, List<Pair<String, (Any?) -> Any>>> = mapOf(
                    Asset::class.java to listOf("usageRecords" to { entity: Any? ->
                        val asset = entity as Asset
                        usageJsonByAssetId[asset.id] ?: ""
                    })
                )

                // 部分导出会让「物品」脱离账单与瞬间独立出走。那两个字段存的是本机自增 id，
                // 在别的库里毫无意义；而导入侧是「保留原 id + OnConflictStrategy.REPLACE」，
                // 悬空 id 可能撞上同 id 记录、从「没有关联」变成「错误关联」（物品挂到别人的账单上）。
                // 所以非完整导出时干脆不带这两列 —— 宁可丢关联，不能错关联。
                val crossGroupExcluded: Map<Class<*>, Set<String>> =
                    if (scope.isComplete) emptyMap()
                    else mapOf(Asset::class.java to setOf("linkedBillId", "linkedMomentId"))

                val themeMode = preferencesManager.themeMode.first()
                val defaultBillType = preferencesManager.defaultBillType.first()
                val budgetReminderEnabled = preferencesManager.budgetReminderEnabled.first()
                val prefsJson = JsonObject(buildMap {
                    put("themeMode", JsonPrimitive(themeMode))
                    put("defaultBillType", JsonPrimitive(defaultBillType))
                    put("budgetReminderEnabled", JsonPrimitive(budgetReminderEnabled))
                }).toString()

                val outputStream = context.contentResolver.openOutputStream(uri)
                    ?: return@withContext Result.failure(Exception(context.getString(R.string.export_error_create_file)))
                outputStream.use { os ->
                    ZipOutputStream(BufferedOutputStream(os)).use { zos ->
                        for ((groupScope, csvName, classes) in CSV_GROUPS) {
                            if (scope != ExportScope.ALL && groupScope != scope) continue
                            val active = classes.mapNotNull { clazz ->
                                val typeName = TYPE_NAME_BY_CLASS[clazz] ?: return@mapNotNull null
                                val entities = entityMap[clazz] ?: return@mapNotNull null
                                (typeName to entities).takeIf { it.second.isNotEmpty() }
                            }
                            if (active.isEmpty()) continue
                            totalCount += active.sumOf { (_, list) -> list.size }
                            val csv = buildGroupCsv(active, extraColumns, crossGroupExcluded)
                            val data = csv.toByteArray(Charsets.UTF_8)
                            val entry = ZipEntry("$csvName.csv")
                            entry.size = data.size.toLong()
                            zos.putNextEntry(entry)
                            zos.write(data)
                            zos.closeEntry()
                        }

                        // 设置类条目只在完整导出时随包出去：部分导出是「给别人读的内容清单」，
                        // 顺带把本机主题、默认账单类型带过去没有道理，导入方会被莫名改设置。
                        if (scope.isComplete) {
                            val prefsData = prefsJson.toByteArray(Charsets.UTF_8)
                            val prefsEntry = ZipEntry(PREFERENCES_ENTRY)
                            prefsEntry.size = prefsData.size.toLong()
                            zos.putNextEntry(prefsEntry)
                            zos.write(prefsData)
                            zos.closeEntry()
                        }

                        for ((name, file) in imageFileMap) {
                            if (!file.exists()) continue
                            val imageBytes = file.readBytes()
                            val imageEntry = ZipEntry("images/$name")
                            imageEntry.size = imageBytes.size.toLong()
                            zos.putNextEntry(imageEntry)
                            zos.write(imageBytes)
                            zos.closeEntry()
                            imageCount++
                        }

                        zos.flush()
                    }
                }
                val msg = if (imageCount > 0) context.getString(R.string.export_success_images, totalCount, imageCount)
                          else context.getString(R.string.export_success, totalCount)
                Result.success(msg)
            } catch (e: AppException) {
                Result.failure(e)
            } catch (e: java.io.IOException) {
                Result.failure(AppException.Io(context.getString(R.string.export_error_io, e.message), e))
            } catch (e: kotlinx.serialization.SerializationException) {
                Result.failure(AppException.Serialization(context.getString(R.string.export_error_serialization, e.message), e))
            } catch (e: Exception) {
                Result.failure(AppException.Unknown(context.getString(R.string.export_error_unknown, e.message), e))
            }
        }
    }

    suspend fun importFromUri(uri: Uri): Result<ImportReport> {
        return withContext(Dispatchers.IO) {
            val tempFile = File(context.cacheDir, "csvimport_${UUID.randomUUID()}.tmp")
            try {
                context.contentResolver.openInputStream(uri)?.use { input ->
                    tempFile.outputStream().use { output -> input.copyTo(output) }
                } ?: return@withContext Result.failure(Exception(context.getString(R.string.export_error_read_file)))

                val zipEntries = mutableMapOf<String, ByteArray>()
                var totalBytes = 0L
                FileInputStream(tempFile).use { fis ->
                    ZipInputStream(BufferedInputStream(fis)).use { zis ->
                        var entry = zis.nextEntry
                        while (entry != null) {
                            if (!entry.isDirectory) {
                                val bytes = zis.readBytes()
                                totalBytes += bytes.size
                                // 全部条目驻留内存（含图片）：给一个明确的过大提示，而不是等 OOM 崩溃
                                if (totalBytes > MAX_IMPORT_BYTES) {
                                    return@withContext Result.failure(
                                        AppException.Unknown(context.getString(R.string.import_error_too_large))
                                    )
                                }
                                zipEntries[entry.name] = bytes
                            }
                            zis.closeEntry()
                            entry = zis.nextEntry
                        }
                    }
                }

                val imagesDir = File(context.filesDir, "images")
                if (!imagesDir.exists()) imagesDir.mkdirs()
                val pathMapping = mutableMapOf<String, String>()

                for ((name, bytes) in zipEntries) {
                    if (name.startsWith("images/") && name.length > 7) {
                        val filename = name.substringAfter("images/")
                        // 防 zip-slip：拒绝含路径分隔符/相对路径的条目名
                        if (filename.contains("..") || filename.contains("/") || filename.contains("\\")) continue
                        val destFile = File(imagesDir, filename)
                        // 图片名是导出侧的原始文件名（含 uuid）：同机重复导入时直接复用，
                        // 否则每次导入都会把整套图片再落一遍盘、留下成堆无引用的孤儿文件
                        if (!destFile.exists()) destFile.writeBytes(bytes)
                        pathMapping[filename] = destFile.absolutePath
                    }
                }

                // 全部 DB 写入包在一个事务里：要么全成，要么全撤，不留半截导入。
                // 用 withTransaction（suspend 事务）包裹 suspend DAO 调用；
                // 旧写法 runInTransaction { runBlocking { ... } } 会与 Room 事务执行器争用单线程而可能死锁。
                val report = db.withTransaction { importIntoDb(zipEntries, pathMapping) }

                if (report.inserted > 0) zipEntries[PREFERENCES_ENTRY]?.let { bytes ->
                    try {
                        val prefsObj = json.parseToJsonElement(String(bytes, Charsets.UTF_8)).jsonObject
                        prefsObj["themeMode"]?.let { v ->
                            val value = (v as? JsonPrimitive)?.contentOrNull ?: v.toString()
                            preferencesManager.setThemeMode(value)
                        }
                        prefsObj["defaultBillType"]?.let { v ->
                            val value = (v as? JsonPrimitive)?.contentOrNull ?: v.toString()
                            preferencesManager.setDefaultBillType(value)
                        }
                        prefsObj["budgetReminderEnabled"]?.let { v ->
                            val str = (v as? JsonPrimitive)?.contentOrNull ?: v.toString()
                            val enabled = str == "true" || str == "是"
                            preferencesManager.setBudgetReminderEnabled(enabled)
                        }
                    } catch (e: Exception) { AppLogger.e("CsvDataExporter", "Import preferences failed", e) }
                }

                Result.success(report)
            } catch (e: AppException) {
                Result.failure(e)
            } catch (e: java.io.IOException) {
                Result.failure(AppException.Io(context.getString(R.string.import_error_io, e.message), e))
            } catch (e: kotlinx.serialization.SerializationException) {
                Result.failure(AppException.Serialization(context.getString(R.string.import_error_parse, e.message), e))
            } catch (e: Throwable) {
                // OutOfMemoryError 是 Error 不是 Exception：大包导入给失败提示而非闪退
                Result.failure(AppException.Unknown(context.getString(R.string.import_error_unknown, e.message), e))
            } finally {
                tempFile.delete()
            }
        }
    }

    // ── Group CSV (one file per category, merged entities with "类型" column) ──

    private val entityFieldMaps: Map<Class<*>, Map<String, java.lang.reflect.Field>> by lazy {
        ENTITY_CLASSES.associateWith { clazz ->
            clazz.declaredFields
                .filter { !Modifier.isStatic(it.modifiers) && !it.name.startsWith("$") && it.name != "serialVersionUID" }
                .onEach { it.isAccessible = true }
                .associateBy { it.name }
        }
    }

    private val commonPrefix: Map<Class<*>, List<String>> = mapOf(
        Asset::class.java to listOf(
            "name", "category", "subCategory", "brand", "model",
            "quantity", "purchasePrice", "acquisitionType", "acquisitionDate",
            "status", "condition", "serialNumber",
            "location", "room"
        ),
        Bill::class.java to listOf(
            "amount", "type", "date", "category", "subCategory",
            "note", "paymentMethod", "merchant", "location", "tags"
        ),
        Wallet::class.java to listOf(
            "name", "type", "currentBalance", "initialBalance",
            "bankName", "cardNumber", "currency"
        ),
        Goal::class.java to listOf(
            "title", "goalType", "category", "totalCount", "currentCount",
            "unit", "deadline", "startDate", "priority"
        ),
        Anniversary::class.java to listOf(
            "title", "solarDate", "isLunar", "type", "personName", "personRelation"
        ),
        Moment::class.java to listOf(
            "content", "timestamp", "title", "mood", "weather", "temperature",
            "location", "tags", "category", "privacy"
        ),
        GoalCheckIn::class.java to listOf(
            "goalId", "date", "count", "mood", "duration", "note"
        ),
        RecurringTemplate::class.java to listOf(
            "name", "amount", "type", "category", "frequency", "note"
        ),
        Budget::class.java to listOf(
            "totalBudget", "reminderThreshold",
            "reminderAtThreshold", "reminderOverBudget"
        ),
        CategoryConfig::class.java to listOf(
            "type", "name", "icon", "color", "sortOrder", "isEnabled"
        ),
        CustomTag::class.java to listOf(
            "name", "color", "usageCount", "applicableTypes"
        ),
        CategoryMapping::class.java to listOf(
            "assetCategory", "billCategory", "isDefault"
        )
    )

    private fun reorderFields(fields: Iterable<String>, clazz: Class<*>): List<String> {
        val prefix = commonPrefix[clazz].orEmpty()
        val set = fields.toSet()
        return prefix.filter { it in set } + (set - prefix.toSet()).toList()
    }

    private fun buildGroupCsv(
        groupEntries: List<Pair<String, List<*>>>,
        extraColumns: Map<Class<*>, List<Pair<String, (Any?) -> Any>>> = emptyMap(),
        extraExcluded: Map<Class<*>, Set<String>> = emptyMap()
    ): String {
        val allFields = linkedSetOf<String>()
        val classExtraCols = mutableMapOf<Class<*>, List<Pair<String, (Any?) -> Any>>>()
        for ((_, entities) in groupEntries) {
            if (entities.isEmpty()) continue
            val clazz = (entities.first() ?: continue)::class.java
            entityFieldMaps[clazz]?.keys
                ?.filter { it !in EXCLUDED_FIELDS[clazz].orEmpty() && it !in extraExcluded[clazz].orEmpty() }
                ?.let { reorderFields(it, clazz) }
                ?.let { allFields.addAll(it) }
            extraColumns[clazz]?.let { cols ->
                classExtraCols[clazz] = cols
                allFields.addAll(cols.map { it.first })
            }
        }
        val fieldNames = allFields.toList()
        val headers = listOf("实体类型") + fieldNames.map { FIELD_LABEL_CN[it] ?: it }
        // 不做「列名 → 字段名」反查：note/notes 等歧义列名在这里会错位（两列写同一个值）。
        // headers 本就由 fieldNames 派生，直接用原字段名取值即是恒等往返。
        val fieldLookup = fieldNames

        val sb = StringBuilder("\uFEFF")
        sb.appendLine(headers.joinToString(",") { escapeCsv(it) })
        for ((typeName, entities) in groupEntries) {
            if (entities.isEmpty()) continue
            val clazz = (entities.first() ?: continue)::class.java
            val fieldMap = entityFieldMaps[clazz] ?: continue
            val extraForClass = classExtraCols[clazz].orEmpty()
            val typeNameEsc = escapeCsv(typeName)
            for (entity in entities) {
                val values = fieldLookup.mapIndexed { i, fieldName ->
                    if (i == 0) typeNameEsc
                    else {
                        val extraValDef = extraForClass.firstOrNull { it.first == fieldName }
                        if (extraValDef != null) {
                            valueToCsv(fieldName, extraValDef.second(entity), clazz)
                        } else {
                            val field = fieldMap[fieldName]
                            if (field != null) valueToCsv(fieldName, field.get(entity), clazz) else ""
                        }
                    }
                }
                sb.appendLine(values.joinToString(","))
            }
        }
        return sb.toString()
    }

    private fun valueToCsv(fieldName: String, value: Any?, entityClass: Class<*>): String {
        return when {
            value == null -> ""
            value is Boolean -> if (value) "是" else "否"
            value is Long && fieldName in DATE_FIELDS -> dateFormatter.format(Instant.ofEpochMilli(value).atZone(ZoneId.systemDefault()))
            value is Number && fieldName in MONEY_FIELDS -> String.format(java.util.Locale.US, "%.2f", value.toDouble() / 100.0)
            value is Number -> value.toString()
            value is String && fieldName == "images" -> processImagesForExport(value)
            value is String && fieldName in LIST_FIELDS -> parseAndJoin(value)
            value is String -> {
                val fieldCnMap = CODE_TO_CN[entityClass]?.get(fieldName)
                if (fieldCnMap != null) escapeCsv(fieldCnMap[value] ?: value)
                else escapeCsv(value)
            }
            else -> escapeCsv(value.toString())
        }
    }

    private fun processImagesForExport(imagesJson: String): String {
        if (imagesJson.isBlank()) return ""
        val paths = try {
            json.decodeFromString<List<String>>(imagesJson)
        } catch (_: Exception) {
            try {
                listOf(imagesJson)
            } catch (_: Exception) {
                null
            }
        } ?: return escapeCsv(imagesJson) // fallback: keep original text

        val names = paths.map { path ->
            val file = File(path)
            if (file.exists()) {
                val name = "${IMAGE_PREFIX}${UUID.randomUUID()}.jpg"
                imageFileMap[name] = file
                name
            } else {
                "${IMAGE_PREFIX}${UUID.randomUUID()}.jpg"
            }
        }
        return if (names.isEmpty()) "" else escapeCsv(names.joinToString("|"))
    }

    private fun parseAndJoin(jsonStr: String): String {
        if (jsonStr.isBlank()) return ""
        return try {
            val list = json.decodeFromString<List<String>>(jsonStr)
            if (list.isEmpty()) "" else escapeCsv(list.joinToString("|"))
        } catch (_: Exception) {
            escapeCsv(jsonStr)
        }
    }

    private fun escapeCsv(value: String): String {
        return if (value.contains(',') || value.contains('"') || value.contains('\n') || value.contains('\r')) {
            "\"${value.replace("\"", "\"\"")}\""
        } else value
    }

    // ── CSV parsing ──

    // 一个列名可能对应多个实体的字段（note/notes 都导出为「备注」，useCount/usageCount 都
    // 是「使用次数」）。反查时展开为**全部**同名字段，让每个实体的行读取器都能取到值——
    // associate 的 last-wins 会静默丢掉另一半字段（备注丢失还会破坏判重指纹）。
    private val HEADER_LABEL_TO_FIELDS: Map<String, List<String>> by lazy {
        FIELD_LABEL_CN.entries.groupBy({ it.value }, { it.key }).mapValues { it.value }
    }

    private fun csvToRows(csv: String): List<Map<String, String>> {
        val clean = csv.removePrefix("\uFEFF")
        // 导出会对含引号的字段做转义；引号内换行会把一条记录拆成多行，先按引号奇偶拼回
        val logicalLines = reflowQuotedLines(clean).filter { it.isNotBlank() }
        if (logicalLines.size < 2) return emptyList()
        val rawHeaders = parseCsvLine(logicalLines[0])
        val headers = rawHeaders.map { HEADER_LABEL_TO_FIELDS[it] ?: listOf(it) }
        return logicalLines.drop(1).map { line ->
            val values = parseCsvLine(line)
            buildMap {
                headers.forEachIndexed { i, fields ->
                    val v = values.getOrElse(i) { "" }
                    fields.forEach { put(it, v) }
                }
            }
        }
    }

    /** 引号内含换行的字段会把一条记录拆成多行：按引号奇偶把物理行重新拼回逻辑记录。 */
    private fun reflowQuotedLines(raw: String): List<String> {
        val out = mutableListOf<String>()
        val buf = StringBuilder()
        raw.lines().forEach { line ->
            if (buf.isNotEmpty()) buf.append('\n')
            buf.append(line)
            if (buf.count { it == '"' } % 2 == 0) {
                out.add(buf.toString())
                buf.clear()
            }
        }
        if (buf.isNotEmpty()) out.add(buf.toString())
        return out
    }

    private fun parseCsvLine(line: String): List<String> {
        val result = mutableListOf<String>()
        val current = StringBuilder()
        var inQuotes = false
        var i = 0
        while (i < line.length) {
            val ch = line[i]
            when {
                ch == '"' && !inQuotes -> inQuotes = true
                ch == '"' && inQuotes -> {
                    if (i + 1 < line.length && line[i + 1] == '"') {
                        current.append('"')
                        i++
                    } else {
                        inQuotes = false
                    }
                }
                ch == ',' && !inQuotes -> {
                    result.add(current.toString())
                    current.clear()
                }
                else -> current.append(ch)
            }
            i++
        }
        result.add(current.toString())
        return result
    }

    private val CLASS_BY_TYPE_NAME: Map<String, Class<*>> = mapOf(
        "物品" to Asset::class.java,
        "账单" to Bill::class.java,
        "钱包" to Wallet::class.java,
        "目标" to Goal::class.java,
        "纪念日" to Anniversary::class.java,
        "瞬间" to Moment::class.java,
        "打卡记录" to GoalCheckIn::class.java,
        "周期模板" to RecurringTemplate::class.java,
        "预算" to Budget::class.java,
        "分类配置" to CategoryConfig::class.java,
        "标签" to CustomTag::class.java,
        "分类映射" to CategoryMapping::class.java
    )

    // 三元组的含义：导出范围 · ZIP 内 CSV 文件名 · 该组的实体。组名同时是文件名，
    // 导入侧按行内「实体类型」列解析，因此改名会破坏互相可导入的契约——不要改。
    private val CSV_GROUPS: List<Triple<ExportScope, String, List<Class<*>>>> = listOf(
        Triple(
            ExportScope.BILL,
            "记账",
            listOf(
                Bill::class.java, Wallet::class.java, RecurringTemplate::class.java,
                Budget::class.java, CategoryConfig::class.java, CategoryMapping::class.java
            )
        ),
        Triple(ExportScope.ASSET, "物品", listOf(Asset::class.java)),
        Triple(
            ExportScope.LIFE,
            "生活",
            listOf(
                Goal::class.java, GoalCheckIn::class.java, Anniversary::class.java,
                Moment::class.java, CustomTag::class.java
            )
        )
    )

    private val TYPE_NAME_BY_CLASS: Map<Class<*>, String> by lazy {
        CLASS_BY_TYPE_NAME.entries.associate { (name, clazz) -> clazz to name }
    }

    private fun translateRow(row: Map<String, String>, entityClass: Class<*>): Map<String, String> {
        val cnToCodeFields = CN_TO_CODE[entityClass] ?: return row
        return row.mapValues { (key, value) ->
            val reverseMap = cnToCodeFields[key]
            if (reverseMap != null) reverseMap[value] ?: value else value
        }
    }

    /**
     * 行 → 实体。**只解析、不写库。**
     *
     * 与 [insertHandler] 拆开是判重的前提：必须先拿到实体，才能算出它的业务键、
     * 也才能看出「包里带的 id」是不是已经压到了本机的另一条记录。
     * 旧实现把解析和写库揉在同一个 lambda 里，于是只能「先写再说」——正是覆盖的根源。
     */
    private val parseHandler: Map<Class<*>, (Map<String, String>, Map<String, String>) -> Any?> = mapOf(
        Asset::class.java to { r, pm -> rowToAsset(r, pm) },
        Bill::class.java to { r, pm -> rowToBill(r, pm) },
        Wallet::class.java to { r, _ -> rowToWallet(r) },
        Goal::class.java to { r, _ -> rowToGoal(r) },
        Anniversary::class.java to { r, _ -> rowToAnniversary(r) },
        Moment::class.java to { r, pm -> rowToMoment(r, pm) },
        GoalCheckIn::class.java to { r, _ -> rowToGoalCheckIn(r) },
        RecurringTemplate::class.java to { r, _ -> rowToRecurringTemplate(r) },
        Budget::class.java to { r, _ -> rowToBudget(r) },
        CategoryConfig::class.java to { r, _ -> rowToCategoryConfig(r) },
        CustomTag::class.java to { r, _ -> rowToCustomTag(r) },
        CategoryMapping::class.java to { r, _ -> rowToCategoryMapping(r) }
    )

    /**
     * 实体 → 写库，返回新主键。
     *
     * 注意这些 DAO 的 insert 都是 `OnConflictStrategy.REPLACE`：**写进去就会覆盖同主键的行**。
     * 调用方必须先经过业务键判重与 id 碰撞检查，绝不能把包里的 id 直接塞进来。
     */
    private val insertHandler: Map<Class<*>, suspend (Any) -> Long> = mapOf(
        Asset::class.java to { e -> db.assetDao().insertAsset(e as Asset) },
        Bill::class.java to { e -> db.billDao().insertBill(e as Bill) },
        Wallet::class.java to { e -> db.walletDao().insert(e as Wallet) },
        Goal::class.java to { e -> db.goalDao().insertGoal(e as Goal) },
        Anniversary::class.java to { e -> db.anniversaryDao().insertAnniversary(e as Anniversary) },
        Moment::class.java to { e -> db.momentDao().insertMoment(e as Moment) },
        GoalCheckIn::class.java to { e -> db.goalCheckInDao().insertCheckIn(e as GoalCheckIn) },
        RecurringTemplate::class.java to { e -> db.recurringTemplateDao().insertTemplate(e as RecurringTemplate) },
        Budget::class.java to { e -> db.budgetDao().insertBudget(e as Budget) },
        CategoryConfig::class.java to { e -> db.categoryConfigDao().insert(e as CategoryConfig) },
        CustomTag::class.java to { e -> db.customTagDao().insert(e as CustomTag) },
        CategoryMapping::class.java to { e -> db.categoryMappingDao().insertMapping(e as CategoryMapping) }
    )

    // ── Import core ──

    /**
     * 事务内的导入主循环。
     *
     * 旧实现在这里做的是：把 CSV 里的 `id` 原样写库，`id` 撞了就靠
     * `OnConflictStrategy.REPLACE` **覆盖**。于是「导入一份几周前的自己包」
     * 会把这几周的记录回滚成包里的旧值，全程一句提示都没有。
     *
     * 现在三条规则：
     *
     * 1. **业务键判重**：键已存在 → 跳过，绝不覆盖（键怎么取见 [ImportKeys]）。
     * 2. **id 碰撞改派**：键不存在、但包里带的 `id` 已被本机另一条记录占用
     *    （跨设备合并时的典型情况）→ 不硬写该 id，交给 Room 自增，并登记
     *    `旧 id → 新 id` 供收尾时重写交叉引用。
     * 3. **只为真的写了东西的钱包重算余额**：守住 `余额 == 初始余额 + Σ账单净额`。
     */
    private suspend fun importIntoDb(
        zipEntries: Map<String, ByteArray>,
        pathMapping: Map<String, String>
    ): ImportReport {
        val idMaps = mutableMapOf<Class<*>, MutableMap<Long, Long>>()
        // 业务键 → 记录 id（含本次刚写入的，因此同一文件内的重复行也会被拦下）
        val knownKeys = mutableMapOf<Class<*>, MutableMap<String, Long>>()
        // 每张表已被占用的主键，用来判断「原样写这个 id 会不会压到别人」
        val occupiedIds = mutableMapOf<Class<*>, MutableSet<Long>>()
        // 本次导入**新写入**的行 id（按实体类）：交叉引用改写只允许作用于这些行
        val importedIds = mutableMapOf<Class<*>, MutableSet<Long>>()
        // 本次写入的钱包（最终 id）／被本次新账单引用的钱包（可能是包里的旧 id）
        val insertedWalletIds = mutableSetOf<Long>()
        val referencedWalletIds = mutableSetOf<Long>()

        for ((clazz, entities) in existingEntitySnapshot()) {
            val ids = occupiedIds.getOrPut(clazz) { mutableSetOf() }
            val keys = knownKeys.getOrPut(clazz) { mutableMapOf() }
            for (entity in entities) {
                val id = entityIdOf(clazz, entity) ?: continue
                ids.add(id)
                businessKeyOf(clazz, entity)?.let { keys.putIfAbsent(it, id) }
            }
        }

        var inserted = 0
        var skipped = 0

        for ((filename, bytes) in zipEntries) {
            if (filename.startsWith("images/") || !filename.endsWith(".csv")) continue
            val rows = csvToRows(String(bytes, Charsets.UTF_8))
            if (rows.isEmpty()) continue

            for (row in rows) {
                val clazz = CLASS_BY_TYPE_NAME[row["实体类型"]] ?: continue
                val translated = translateRow(row, clazz)
                val parsed = parseHandler[clazz]?.invoke(translated, pathMapping) ?: continue

                // 先把「此刻已经能确定」的交叉引用落到本机 id 上再算键，
                // 否则跨设备合并时同一次打卡会因为目标 id 不同而被当成两条。
                // （导出侧父行一定排在子行之前，所以映射此时已就绪。）
                val resolved = resolveIncomingRefs(clazz, parsed, idMaps)
                val key = businessKeyOf(clazz, resolved)

                if (key != null) {
                    val existingId = knownKeys.getOrPut(clazz) { mutableMapOf() }[key]
                    if (existingId != null) {
                        // 同一条已经在库里：跳过。跳过 = 保留现有数据，不是失败。
                        entityIdOf(clazz, resolved)?.let { recordIdMap(idMaps, clazz, it, existingId) }
                        skipped++
                        continue
                    }
                }

                val rawId = entityIdOf(clazz, resolved) ?: 0L
                val occupied = occupiedIds.getOrPut(clazz) { mutableSetOf() }
                val toInsert = if (rawId != 0L && rawId in occupied) withZeroId(clazz, resolved) else resolved

                val newId = insertHandler[clazz]?.invoke(toInsert) ?: continue
                recordIdMap(idMaps, clazz, rawId, newId)
                occupied.add(newId)
                importedIds.getOrPut(clazz) { mutableSetOf() }.add(newId)
                if (key != null) {
                    val keys = knownKeys.getOrPut(clazz) { mutableMapOf() }
                    if (!keys.containsKey(key)) keys[key] = newId
                }
                inserted++

                if (clazz == Wallet::class.java) {
                    insertedWalletIds.add(newId)
                } else if (clazz == Bill::class.java) {
                    val bill = toInsert as? Bill
                    bill?.walletId?.let { referencedWalletIds.add(it) }
                    bill?.toWalletId?.let { referencedWalletIds.add(it) }
                } else if (clazz == Asset::class.java) {
                    importUsageRecords(row["usageRecords"], newId)
                }
            }
        }

        if (idMaps.isNotEmpty()) {
            // 交叉引用改写只允许作用于**本次导入写入的行**：
            // 无差别改写全表会让本地既有行里恰好撞上包内旧 id 的引用被错改
            updateCrossReferences(idMaps, importedIds)
        }

        // 只有本次真的动了账单或钱包，余额才可能与账单脱节
        val walletMap = idMaps[Wallet::class.java].orEmpty()
        val walletsToRecalculate = mutableSetOf<Long>()
        walletsToRecalculate.addAll(insertedWalletIds)
        referencedWalletIds.forEach { walletsToRecalculate.add(walletMap[it] ?: it) }

        return ImportReport(
            inserted = inserted,
            skipped = skipped,
            walletsRecalculated = recalculateWalletBalances(walletsToRecalculate)
        )
    }

    /** 现有全部实体的快照，用来建「业务键 → id」与「已占用主键」两张表。 */
    private suspend fun existingEntitySnapshot(): Map<Class<*>, List<Any>> {
        val snapshot = mutableMapOf<Class<*>, List<Any>>()
        snapshot[Bill::class.java] = db.billDao().getAllBills().first()
        snapshot[Wallet::class.java] = db.walletDao().getAllWallets().first()
        snapshot[RecurringTemplate::class.java] = db.recurringTemplateDao().getAllTemplates().first()
        snapshot[Budget::class.java] = db.budgetDao().getAllBudgets().first()
        snapshot[CategoryConfig::class.java] = db.categoryConfigDao().getAllCategories().first()
        snapshot[CategoryMapping::class.java] = db.categoryMappingDao().getAllMappings().first()
        snapshot[Asset::class.java] = db.assetDao().getAllAssets().first()
        val goals = db.goalDao().getAllGoals().first()
        snapshot[Goal::class.java] = goals
        snapshot[GoalCheckIn::class.java] = if (goals.isEmpty()) emptyList()
        else db.goalCheckInDao().getCheckInsByGoalIds(goals.map { it.id }).first()
        snapshot[Anniversary::class.java] = db.anniversaryDao().getAllAnniversaries().first()
        snapshot[Moment::class.java] = db.momentDao().getAllMoments().first()
        snapshot[CustomTag::class.java] = db.customTagDao().getAllTags().first()
        return snapshot
    }

    private fun entityIdOf(clazz: Class<*>, entity: Any): Long? =
        entityFieldMaps[clazz]?.get("id")?.get(entity) as? Long

    /** 实体 → 业务键。具体取法见 [ImportKeys]；未登记的类型返回 null（不参与判重）。 */
    private fun businessKeyOf(clazz: Class<*>, entity: Any): String? = when (clazz) {
        Bill::class.java -> (entity as? Bill)?.let {
            ImportKeys.bill(
                transactionId = it.transactionId,
                walletId = it.walletId,
                amount = it.amount,
                date = it.date,
                category = it.category,
                subCategory = it.subCategory,
                note = it.note,
                merchant = it.merchant,
                paymentMethod = it.paymentMethod.value
            )
        }
        Wallet::class.java -> (entity as? Wallet)?.let { ImportKeys.wallet(it.name, it.type) }
        Asset::class.java -> (entity as? Asset)?.let { ImportKeys.asset(it.name, it.acquisitionDate) }
        Goal::class.java -> (entity as? Goal)?.let { ImportKeys.goal(it.title, it.startDate) }
        Anniversary::class.java -> (entity as? Anniversary)?.let { ImportKeys.anniversary(it.title, it.solarDate) }
        Moment::class.java -> (entity as? Moment)?.let { ImportKeys.moment(it.timestamp, it.content) }
        GoalCheckIn::class.java -> (entity as? GoalCheckIn)?.let { ImportKeys.goalCheckIn(it.goalId, it.date) }
        RecurringTemplate::class.java -> (entity as? RecurringTemplate)?.let {
            ImportKeys.recurringTemplate(it.name, it.type.value, it.frequency.value)
        }
        Budget::class.java -> (entity as? Budget)?.let { ImportKeys.budget(it.yearMonth) }
        CategoryConfig::class.java -> (entity as? CategoryConfig)?.let { ImportKeys.categoryConfig(it.type, it.name) }
        CustomTag::class.java -> (entity as? CustomTag)?.let { ImportKeys.customTag(it.name) }
        CategoryMapping::class.java -> (entity as? CategoryMapping)?.let { ImportKeys.categoryMapping(it.assetCategory, it.billCategory) }
        else -> null
    }

    /** 把 id 归零，让 Room 自增——用于「包里带的 id 被本机别人占了」的情况。 */
    private fun withZeroId(clazz: Class<*>, entity: Any): Any = when (clazz) {
        Bill::class.java -> (entity as Bill).copy(id = 0)
        Wallet::class.java -> (entity as Wallet).copy(id = 0)
        Asset::class.java -> (entity as Asset).copy(id = 0)
        Goal::class.java -> (entity as Goal).copy(id = 0)
        Anniversary::class.java -> (entity as Anniversary).copy(id = 0)
        Moment::class.java -> (entity as Moment).copy(id = 0)
        GoalCheckIn::class.java -> (entity as GoalCheckIn).copy(id = 0)
        RecurringTemplate::class.java -> (entity as RecurringTemplate).copy(id = 0)
        Budget::class.java -> (entity as Budget).copy(id = 0)
        CategoryConfig::class.java -> (entity as CategoryConfig).copy(id = 0)
        CustomTag::class.java -> (entity as CustomTag).copy(id = 0)
        CategoryMapping::class.java -> (entity as CategoryMapping).copy(id = 0)
        else -> entity
    }

    /**
     * 算键之前先把已知的引用映射落到本机 id —— 目前只有「打卡 → 目标」这一条链：
     * 目标先于打卡导出，因此轮到这里时目标的新 id 一定已经登记好了。
     * 其余引用全部交给收尾的 [updateCrossReferences] 统一重写。
     */
    private fun resolveIncomingRefs(clazz: Class<*>, entity: Any, idMaps: Map<Class<*>, Map<Long, Long>>): Any {
        if (clazz != GoalCheckIn::class.java) return entity
        val checkIn = entity as? GoalCheckIn ?: return entity
        val goalId = checkIn.goalId ?: return entity
        val mapped = idMaps[Goal::class.java]?.get(goalId) ?: return entity
        return checkIn.copy(goalId = mapped)
    }

    private fun recordIdMap(
        idMaps: MutableMap<Class<*>, MutableMap<Long, Long>>,
        clazz: Class<*>,
        oldId: Long,
        newId: Long
    ) {
        if (oldId == 0L || oldId == newId) return
        idMaps.getOrPut(clazz) { mutableMapOf() }[oldId] = newId
    }

    /**
     * 写入物品的使用记录。
     *
     * 只有物品**本次新增**时才会走到这里——物品被跳过时，它的使用记录也必然已经存在，
     * 所以重复导入不再让使用次数无限膨胀。
     * 同一份 JSON 内部再按 (usedAt, note) 去一次重，防止包本身带了重复行。
     */
    private suspend fun importUsageRecords(raw: String?, assetId: Long) {
        if (raw.isNullOrBlank()) return
        try {
            val seen = mutableSetOf<String>()
            json.parseToJsonElement(raw).jsonArray.forEach { element ->
                val rec = element.jsonObject
                val usedAt = (rec["usedAt"] as? JsonPrimitive)?.let {
                    try { it.content.toLong() } catch (_: Exception) { null }
                } ?: System.currentTimeMillis()
                val note = (rec["note"] as? JsonPrimitive)?.contentOrNull ?: ""
                if (!seen.add(ImportKeys.usageRecord(usedAt, note))) return@forEach
                db.usageRecordDao().insertUsageRecord(UsageRecord(assetId = assetId, usedAt = usedAt, note = note))
            }
        } catch (e: Exception) {
            AppLogger.e("CsvDataExporter", "Import usage records failed", e)
        }
    }

    /**
     * 按账单重算钱包余额，守住不变量：`currentBalance == initialBalance + Σ 该钱包账单净额`。
     *
     * **为什么必须重算**：导入是「合并」，新账单会落进**已存在**的钱包；而钱包行本身
     * 因为业务键相同被跳过了，余额不会跟着动 —— 账单加了、余额没加，账实不符。
     *
     * **为什么安全**：应用自己在 `WalletEditScreen` 改初始余额时，就是把 `currentBalance`
     * 平移同一个差额。也就是说 `currentBalance` 本来就只是 `initialBalance` 的派生值，
     * 不存在「用户手填的当前余额」会被这次重算抹掉。
     *
     * @return 余额确实被修正过的钱包数（本来就对的不计）。
     */
    private suspend fun recalculateWalletBalances(walletIds: Set<Long>): Int {
        if (walletIds.isEmpty()) return 0
        val wallets = db.walletDao().getAllWallets().first().associateBy { it.id }
        val deltas = mutableMapOf<Long, Long>()
        fun add(walletId: Long?, amount: Long) {
            if (walletId != null) deltas[walletId] = (deltas[walletId] ?: 0L) + amount
        }
        for (bill in db.billDao().getAllBills().first()) {
            when (bill.type) {
                BillType.EXPENSE -> add(bill.walletId, -bill.amount)
                BillType.INCOME -> add(bill.walletId, bill.amount)
                BillType.TRANSFER -> {
                    add(bill.walletId, -bill.amount)
                    add(bill.toWalletId, bill.amount)
                }
            }
        }
        var changed = 0
        for (id in walletIds) {
            val wallet = wallets[id] ?: continue
            val expected = wallet.initialBalance + (deltas[id] ?: 0L)
            if (wallet.currentBalance != expected) {
                db.walletDao().updateBalance(id, expected)
                changed++
            }
        }
        return changed
    }

    // ── Row-to-entity converters ──

    private fun rowToAsset(row: Map<String, String>, pathMapping: Map<String, String>): Asset? {
        return try {
            Asset(
                id = row["id"]?.toLongOrNull() ?: 0,
                name = row["name"] ?: return null,
                category = row["category"] ?: "",
                subCategory = row["subCategory"] ?: "",
                brand = row["brand"] ?: "",
                model = row["model"] ?: "",
                purchasePrice = row["purchasePrice"]?.let { Money.parse(it)?.cents } ?: 0,
                acquisitionType = row["acquisitionType"] ?: "PURCHASE",
                acquisitionDate = parseDateOrNull(row["acquisitionDate"]),
                quantity = row["quantity"]?.toIntOrNull()?.coerceAtLeast(1) ?: 1,
                status = AssetStatus.from(row["status"] ?: "HELD"),
                costMode = row["costMode"] ?: "DAILY",
                useCount = row["useCount"]?.toIntOrNull() ?: 0,
                totalUsageHours = row["totalUsageHours"]?.toDoubleOrNull() ?: 0.0,
                location = row["location"] ?: "",
                room = row["room"] ?: "",
                purchaseChannel = row["purchaseChannel"] ?: "",
                warrantyExpireDate = parseDateOrNull(row["warrantyExpireDate"]),
                insuranceExpireDate = parseDateOrNull(row["insuranceExpireDate"]),
                insuranceCompany = row["insuranceCompany"] ?: "",
                insurancePolicyNo = row["insurancePolicyNo"] ?: "",
                images = resolveImages(row["images"], pathMapping),
                description = row["description"] ?: "",
                condition = row["condition"] ?: "GOOD",
                serialNumber = row["serialNumber"] ?: "",
                receiptPath = row["receiptPath"] ?: "",
                depreciationRate = row["depreciationRate"]?.toDoubleOrNull() ?: 0.0,
                currentValue = row["currentValue"]?.let { Money.parse(it)?.cents } ?: 0,
                maintenanceIntervalDays = row["maintenanceIntervalDays"]?.toIntOrNull() ?: 0,
                lastMaintenanceDate = parseDateOrNull(row["lastMaintenanceDate"]),
                nextMaintenanceDate = parseDateOrNull(row["nextMaintenanceDate"]),
                maintenanceNotes = row["maintenanceNotes"] ?: "",
                isFavorite = row["isFavorite"].toBoolean(),
                tags = joinToJson(row["tags"]),
                linkedBillId = row["linkedBillId"]?.toLongOrNull(),
                linkedMomentId = row["linkedMomentId"]?.toLongOrNull(),
                retireDate = parseDateOrNull(row["retireDate"]),
                retireReason = row["retireReason"] ?: "",
                lostDate = parseDateOrNull(row["lostDate"]),
                lostReason = row["lostReason"] ?: "",
                soldDate = parseDateOrNull(row["soldDate"]),
                soldPrice = row["soldPrice"]?.let { Money.parse(it)?.cents },
                soldChannel = row["soldChannel"],
                soldToWhom = row["soldToWhom"],
                sortOrder = row["sortOrder"]?.toIntOrNull() ?: 0,
                createdAt = parseDateOrNull(row["createdAt"]) ?: System.currentTimeMillis(),
                updatedAt = parseDateOrNull(row["updatedAt"]) ?: System.currentTimeMillis()
            )
        } catch (_: Exception) { null }
    }

    private fun rowToBill(row: Map<String, String>, pathMapping: Map<String, String>): Bill? {
        val billDate = parseDateOrNull(row["date"]) ?: return null
        return try {
            Bill(
                id = row["id"]?.toLongOrNull() ?: 0,
                amount = row["amount"]?.let { Money.parse(it)?.cents } ?: return null,
                type = BillType.from(row["type"] ?: return null),
                category = row["category"] ?: "",
                subCategory = row["subCategory"] ?: "",
                note = row["note"] ?: "",
                date = billDate,
                yearMonth = row["yearMonth"] ?: yearMonthFormatter.format(java.time.Instant.ofEpochMilli(billDate).atZone(java.time.ZoneId.systemDefault())),
                walletId = row["walletId"]?.toLongOrNull(),
                toWalletId = row["toWalletId"]?.toLongOrNull(),
                paymentMethod = PaymentMethod.from(row["paymentMethod"] ?: ""),
                merchant = row["merchant"] ?: "",
                transactionId = row["transactionId"] ?: "",
                location = row["location"] ?: "",
                tags = joinToJson(row["tags"]),
                images = resolveImages(row["images"], pathMapping),
                linkedAssetId = row["linkedAssetId"]?.toLongOrNull(),
                linkType = row["linkType"],
                recurringId = row["recurringId"]?.toLongOrNull(),
                recurringFrequency = RecurringFrequency.from(row["recurringFrequency"] ?: ""),
                splitGroupId = row["splitGroupId"] ?: "",
                isReimbursable = row["isReimbursable"].toBoolean(),
                isReimbursed = row["isReimbursed"].toBoolean(),
                reimbursedDate = parseDateOrNull(row["reimbursedDate"]),
                isTaxDeductible = row["isTaxDeductible"].toBoolean(),
                latitude = row["latitude"]?.toDoubleOrNull(),
                longitude = row["longitude"]?.toDoubleOrNull(),
                isAutoGenerated = row["isAutoGenerated"].toBoolean(),
                createdAt = parseDateOrNull(row["createdAt"]) ?: System.currentTimeMillis(),
                updatedAt = parseDateOrNull(row["updatedAt"]) ?: System.currentTimeMillis()
            )
        } catch (_: Exception) { null }
    }

    private fun rowToWallet(row: Map<String, String>): Wallet? {
        return try {
            Wallet(
                id = row["id"]?.toLongOrNull() ?: 0,
                name = row["name"] ?: return null,
                type = row["type"] ?: "CASH",
                icon = AppIcon.fromName(row["icon"] ?: "Payments"),
                color = row["color"] ?: "#4CAF50",
                bankName = row["bankName"] ?: "",
                cardNumber = row["cardNumber"] ?: "",
                initialBalance = row["initialBalance"]?.let { Money.parse(it)?.cents } ?: 0,
                currentBalance = row["currentBalance"]?.let { Money.parse(it)?.cents } ?: 0,
                currency = row["currency"] ?: "CNY",
                isDefault = row["isDefault"].toBoolean(),
                isEnabled = row["isEnabled"].toBoolean(),
                sortOrder = row["sortOrder"]?.toIntOrNull() ?: 0,
                description = row["description"] ?: "",
                createdAt = parseDateOrNull(row["createdAt"]) ?: System.currentTimeMillis(),
                updatedAt = parseDateOrNull(row["updatedAt"]) ?: System.currentTimeMillis()
            )
        } catch (_: Exception) { null }
    }

    private fun rowToGoal(row: Map<String, String>): Goal? {
        return try {
            Goal(
                id = row["id"]?.toLongOrNull() ?: 0,
                title = row["title"] ?: return null,
                description = row["description"] ?: "",
                category = row["category"] ?: "",
                goalType = row["goalType"] ?: "CUMULATIVE",
                totalCount = row["totalCount"]?.toIntOrNull() ?: 100,
                currentCount = row["currentCount"]?.toIntOrNull() ?: 0,
                unit = row["unit"] ?: "次",
                frequency = row["frequency"] ?: "",
                targetPerPeriod = row["targetPerPeriod"]?.toIntOrNull() ?: 0,
                currentPeriodCount = row["currentPeriodCount"]?.toIntOrNull() ?: 0,
                periodStartDate = parseDateOrNull(row["periodStartDate"]),
                deadline = parseDateOrNull(row["deadline"]),
                startDate = parseDateOrNull(row["startDate"]) ?: System.currentTimeMillis(),
                priority = row["priority"] ?: "MEDIUM",
                color = row["color"] ?: "",
                icon = AppIcon.fromName(row["icon"] ?: "Flag"),
                streak = row["streak"]?.toIntOrNull() ?: 0,
                longestStreak = row["longestStreak"]?.toIntOrNull() ?: 0,
                lastCheckInDate = parseDateOrNull(row["lastCheckInDate"]),
                totalCheckInDays = row["totalCheckInDays"]?.toIntOrNull() ?: 0,
                reminderEnabled = row["reminderEnabled"].toBoolean(),
                reminderTime = row["reminderTime"] ?: "",
                linkedAssetId = row["linkedAssetId"]?.toLongOrNull(),
                isPublic = row["isPublic"].toBoolean(),
                notes = row["notes"] ?: "",
                createdAt = parseDateOrNull(row["createdAt"]) ?: System.currentTimeMillis(),
                updatedAt = parseDateOrNull(row["updatedAt"]) ?: System.currentTimeMillis()
            )
        } catch (_: Exception) { null }
    }

    private fun rowToAnniversary(row: Map<String, String>): Anniversary? {
        return try {
            Anniversary(
                id = row["id"]?.toLongOrNull() ?: 0,
                title = row["title"] ?: return null,
                description = row["description"] ?: "",
                solarDate = parseDateOrNull(row["solarDate"]) ?: return null,
                isLunar = row["isLunar"].toBoolean(),
                lunarYear = row["lunarYear"]?.toIntOrNull(),
                lunarMonth = row["lunarMonth"]?.toIntOrNull(),
                lunarDay = row["lunarDay"]?.toIntOrNull(),
                lunarLeapMonth = row["lunarLeapMonth"].toBoolean(),
                type = row["type"] ?: "OTHER",
                personName = row["personName"] ?: "",
                personRelation = row["personRelation"] ?: "",
                isYearly = row["isYearly"].toBoolean(),
                displayMode = row["displayMode"] ?: "COUNT_UP",
                multiRemindJson = joinToJson(row["multiRemindJson"]),
                reminderTime = row["reminderTime"] ?: "09:00",
                notificationEnabled = row["notificationEnabled"].toBoolean(),
                color = row["color"] ?: "",
                icon = AppIcon.fromName(row["icon"] ?: "Favorite"),
                linkedMomentId = row["linkedMomentId"]?.toLongOrNull(),
                isPinned = row["isPinned"].toBoolean(),
                createdAt = parseDateOrNull(row["createdAt"]) ?: System.currentTimeMillis(),
                updatedAt = parseDateOrNull(row["updatedAt"]) ?: System.currentTimeMillis()
            )
        } catch (_: Exception) { null }
    }

    private fun rowToMoment(row: Map<String, String>, pathMapping: Map<String, String>): Moment? {
        return try {
            Moment(
                id = row["id"]?.toLongOrNull() ?: 0,
                title = row["title"] ?: "",
                content = row["content"] ?: return null,
                timestamp = parseDateOrNull(row["timestamp"]) ?: parseDateOrNull(row["date"]) ?: System.currentTimeMillis(),
                images = resolveImages(row["images"], pathMapping),
                videoPath = row["videoPath"] ?: "",
                audioPath = row["audioPath"] ?: "",
                mood = row["mood"] ?: "",
                weather = row["weather"] ?: "",
                temperature = row["temperature"]?.toIntOrNull() ?: Int.MIN_VALUE,
                location = row["location"] ?: "",
                latitude = row["latitude"]?.toDoubleOrNull(),
                longitude = row["longitude"]?.toDoubleOrNull(),
                tags = joinToJson(row["tags"]),
                category = row["category"] ?: "",
                privacy = row["privacy"] ?: "PRIVATE",
                isPinned = row["isPinned"].toBoolean(),
                isFavorite = row["isFavorite"].toBoolean(),
                wordCount = row["wordCount"]?.toIntOrNull() ?: 0,
                linkedAssetId = row["linkedAssetId"]?.toLongOrNull(),
                linkedAnniversaryId = row["linkedAnniversaryId"]?.toLongOrNull(),
                linkedGoalId = row["linkedGoalId"]?.toLongOrNull(),
                createdAt = parseDateOrNull(row["createdAt"]) ?: System.currentTimeMillis(),
                updatedAt = parseDateOrNull(row["updatedAt"]) ?: System.currentTimeMillis()
            )
        } catch (_: Exception) { null }
    }

    private fun rowToGoalCheckIn(row: Map<String, String>): GoalCheckIn? {
        return try {
            GoalCheckIn(
                id = row["id"]?.toLongOrNull() ?: 0,
                goalId = row["goalId"]?.toLongOrNull() ?: return null,
                date = parseDateOrNull(row["date"]) ?: return null,
                count = row["count"]?.toIntOrNull() ?: 1,
                note = row["note"] ?: "",
                mood = row["mood"] ?: "",
                duration = row["duration"]?.toIntOrNull() ?: 0,
                createdAt = parseDateOrNull(row["createdAt"]) ?: System.currentTimeMillis()
            )
        } catch (_: Exception) { null }
    }

    private fun rowToRecurringTemplate(row: Map<String, String>): RecurringTemplate? {
        return try {
            RecurringTemplate(
                id = row["id"]?.toLongOrNull() ?: 0,
                name = row["name"] ?: return null,
                amount = row["amount"]?.let { Money.parse(it)?.cents } ?: return null,
                type = BillType.from(row["type"] ?: return null),
                category = row["category"] ?: "",
                frequency = RecurringFrequency.from(row["frequency"] ?: return null),
                dayOfMonth = row["dayOfMonth"]?.toIntOrNull() ?: 0,
                dayOfWeek = row["dayOfWeek"]?.toIntOrNull() ?: 0,
                isActive = row["isActive"].toBoolean(),
                lastGeneratedDate = parseDateOrNull(row["lastGeneratedDate"]),
                nextGenerateDate = parseDateOrNull(row["nextGenerateDate"]),
                autoGenerate = row["autoGenerate"].toBoolean(),
                remindBeforeDays = row["remindBeforeDays"]?.toIntOrNull() ?: 1,
                note = row["note"] ?: "",
                createdAt = parseDateOrNull(row["createdAt"]) ?: System.currentTimeMillis(),
                updatedAt = parseDateOrNull(row["updatedAt"]) ?: System.currentTimeMillis()
            )
        } catch (_: Exception) { null }
    }

    private fun rowToBudget(row: Map<String, String>): Budget? {
        return try {
            Budget(
                id = row["id"]?.toLongOrNull() ?: 0,
                yearMonth = row["yearMonth"] ?: return null,
                totalBudget = row["totalBudget"]?.let { Money.parse(it)?.cents } ?: return null,
                reminderThreshold = row["reminderThreshold"]?.toDoubleOrNull() ?: 0.8,
                reminderAtThreshold = row["reminderAtThreshold"].toBoolean(),
                reminderOverBudget = row["reminderOverBudget"].toBoolean(),
                createdAt = parseDateOrNull(row["createdAt"]) ?: System.currentTimeMillis(),
                updatedAt = parseDateOrNull(row["updatedAt"]) ?: System.currentTimeMillis()
            )
        } catch (_: Exception) { null }
    }

    private fun rowToCategoryConfig(row: Map<String, String>): CategoryConfig? {
        return try {
            CategoryConfig(
                id = row["id"]?.toLongOrNull() ?: 0,
                type = row["type"] ?: return null,
                name = row["name"] ?: return null,
                icon = AppIcon.fromName(row["icon"] ?: "Settings"),
                color = row["color"] ?: "",
                sortOrder = row["sortOrder"]?.toIntOrNull() ?: 0,
                isDefault = row["isDefault"].toBoolean(),
                isEnabled = row["isEnabled"].toBoolean(),
                parentId = row["parentId"]?.toLongOrNull(),
                description = row["description"] ?: "",
                createdAt = parseDateOrNull(row["createdAt"]) ?: System.currentTimeMillis(),
                updatedAt = parseDateOrNull(row["updatedAt"]) ?: System.currentTimeMillis()
            )
        } catch (_: Exception) { null }
    }

    private fun rowToCustomTag(row: Map<String, String>): CustomTag? {
        return try {
            CustomTag(
                id = row["id"]?.toLongOrNull() ?: 0,
                name = row["name"] ?: return null,
                color = row["color"] ?: "",
                icon = AppIcon.fromName(row["icon"] ?: "Flag"),
                usageCount = row["usageCount"]?.toIntOrNull() ?: 0,
                applicableTypes = joinToJson(row["applicableTypes"]),
                createdAt = parseDateOrNull(row["createdAt"]) ?: System.currentTimeMillis(),
                updatedAt = parseDateOrNull(row["updatedAt"]) ?: System.currentTimeMillis()
            )
        } catch (_: Exception) { null }
    }

    private fun rowToCategoryMapping(row: Map<String, String>): CategoryMapping? {
        return try {
            CategoryMapping(
                id = row["id"]?.toLongOrNull() ?: 0,
                assetCategory = row["assetCategory"] ?: return null,
                billCategory = row["billCategory"] ?: return null,
                isDefault = row["isDefault"].toBoolean(),
                createdAt = parseDateOrNull(row["createdAt"]) ?: System.currentTimeMillis(),
                updatedAt = parseDateOrNull(row["updatedAt"]) ?: System.currentTimeMillis()
            )
        } catch (_: Exception) { null }
    }

    // ── Value converters ──


    private fun parseDateOrNull(value: String?): Long? {
        if (value.isNullOrBlank()) return null
        return try {
            value.toLong()
        } catch (_: NumberFormatException) {
            try {
                LocalDateTime.parse(value, dateFormatter).atZone(ZoneId.systemDefault()).toInstant().toEpochMilli()
            } catch (_: Exception) {
                null
            }
        }
    }

    /**
     * 把 CSV 里的图片名还原成本机绝对路径。
     *
     * 映射不到的条目要分两种情况，不能一概而论：
     * - 是**我们自己生成**的名字（`img_<uuid>.jpg`）却映射不到 = 导出时文件就已经不在了，
     *   再把它当路径存回去只会留下一条永远打不开的悬空记录 → **丢弃**。
     * - **不是**我们生成的名字（手写、或别的软件给的 CSV 里可能是真实路径）→ 原样保留，
     *   不能替用户判断它有没有用。
     */
    private fun resolveImages(csvValue: String?, pathMapping: Map<String, String>): String {
        if (csvValue.isNullOrBlank()) return ""
        val names = csvValue.split("|").map { it.trim() }.filter { it.isNotEmpty() }
        if (names.isEmpty()) return ""
        val paths = names.mapNotNull { name ->
            pathMapping[name] ?: name.takeIf { !it.startsWith(IMAGE_PREFIX) }
        }
        if (paths.isEmpty()) return ""
        return json.encodeToString(kotlinx.serialization.serializer(), paths)
    }

    private fun joinToJson(csvValue: String?): String {
        if (csvValue.isNullOrBlank()) return ""
        val items = csvValue.split("|").map { it.trim() }.filter { it.isNotEmpty() }
        return if (items.isEmpty()) "" else json.encodeToString(kotlinx.serialization.serializer(), items)
    }

    private suspend fun updateCrossReferences(
        idMaps: Map<Class<*>, Map<Long, Long>>,
        importedIds: Map<Class<*>, Set<Long>>
    ) {
        val assetMap = idMaps[Asset::class.java] ?: emptyMap()
        val billMap = idMaps[Bill::class.java] ?: emptyMap()
        val walletMap = idMaps[Wallet::class.java] ?: emptyMap()
        val goalMap = idMaps[Goal::class.java] ?: emptyMap()
        val anniversaryMap = idMaps[Anniversary::class.java] ?: emptyMap()
        val momentMap = idMaps[Moment::class.java] ?: emptyMap()
        val templateMap = idMaps[RecurringTemplate::class.java] ?: emptyMap()
        val categoryMap = idMaps[CategoryConfig::class.java] ?: emptyMap()
        // 只有本次导入**新写入**的行才允许被改写引用；本地既有行哪怕 id 撞上包内旧 id 也不动
        val billIds = importedIds[Bill::class.java] ?: emptySet()
        val assetIds = importedIds[Asset::class.java] ?: emptySet()
        val momentIds = importedIds[Moment::class.java] ?: emptySet()
        val goalIds = importedIds[Goal::class.java] ?: emptySet()
        val anniversaryIds = importedIds[Anniversary::class.java] ?: emptySet()
        val categoryIds = importedIds[CategoryConfig::class.java] ?: emptySet()

        if (assetMap.isNotEmpty()) {
            db.billDao().getAllBills().first().filter { it.id in billIds }.forEach { bill ->
                var updated = false
                var newLinkedAssetId = bill.linkedAssetId
                if (newLinkedAssetId != null && newLinkedAssetId in assetMap) {
                    newLinkedAssetId = assetMap[newLinkedAssetId]
                    updated = true
                }
                if (updated) {
                    db.billDao().updateBill(bill.copy(linkedAssetId = newLinkedAssetId))
                }
            }
            db.momentDao().getAllMoments().first().filter { it.id in momentIds }.forEach { moment ->
                var updated = false
                var newLinkedAssetId = moment.linkedAssetId
                if (newLinkedAssetId != null && newLinkedAssetId in assetMap) {
                    newLinkedAssetId = assetMap[newLinkedAssetId]
                    updated = true
                }
                if (updated) {
                    db.momentDao().updateMoment(moment.copy(linkedAssetId = newLinkedAssetId))
                }
            }
            db.goalDao().getAllGoals().first().filter { it.id in goalIds }.forEach { goal ->
                var updated = false
                var newLinkedAssetId = goal.linkedAssetId
                if (newLinkedAssetId != null && newLinkedAssetId in assetMap) {
                    newLinkedAssetId = assetMap[newLinkedAssetId]
                    updated = true
                }
                if (updated) {
                    db.goalDao().updateGoal(goal.copy(linkedAssetId = newLinkedAssetId))
                }
            }
        }

        if (billMap.isNotEmpty()) {
            db.assetDao().getAllAssets().first().filter { it.id in assetIds }.forEach { asset ->
                var updated = false
                var newLinkedBillId = asset.linkedBillId
                if (newLinkedBillId != null && newLinkedBillId in billMap) {
                    newLinkedBillId = billMap[newLinkedBillId]
                    updated = true
                }
                if (updated) {
                    db.assetDao().updateAsset(asset.copy(linkedBillId = newLinkedBillId))
                }
            }
        }

        if (walletMap.isNotEmpty()) {
            db.billDao().getAllBills().first().filter { it.id in billIds }.forEach { bill ->
                var updated = false
                var newWalletId = bill.walletId
                var newToWalletId = bill.toWalletId
                if (newWalletId != null && newWalletId in walletMap) {
                    newWalletId = walletMap[newWalletId]
                    updated = true
                }
                if (newToWalletId != null && newToWalletId in walletMap) {
                    newToWalletId = walletMap[newToWalletId]
                    updated = true
                }
                if (updated) {
                    db.billDao().updateBill(bill.copy(walletId = newWalletId, toWalletId = newToWalletId))
                }
            }
        }

        if (goalMap.isNotEmpty()) {
            for ((oldId, newId) in goalMap) {
                // 仅当目标本身是本次新写入的才迁移其打卡记录；本地既有目标的打卡不许动
                if (newId !in goalIds) continue
                db.goalCheckInDao().getCheckInsByGoal(oldId).first().forEach { checkIn ->
                    db.goalCheckInDao().updateCheckIn(checkIn.copy(goalId = newId))
                }
            }
            db.momentDao().getAllMoments().first().filter { it.id in momentIds }.forEach { moment ->
                var updated = false
                var newLinkedGoalId = moment.linkedGoalId
                if (newLinkedGoalId != null && newLinkedGoalId in goalMap) {
                    newLinkedGoalId = goalMap[newLinkedGoalId]
                    updated = true
                }
                if (updated) {
                    db.momentDao().updateMoment(moment.copy(linkedGoalId = newLinkedGoalId))
                }
            }
        }

        if (anniversaryMap.isNotEmpty()) {
            db.momentDao().getAllMoments().first().filter { it.id in momentIds }.forEach { moment ->
                var updated = false
                var newLinkedAnniversaryId = moment.linkedAnniversaryId
                if (newLinkedAnniversaryId != null && newLinkedAnniversaryId in anniversaryMap) {
                    newLinkedAnniversaryId = anniversaryMap[newLinkedAnniversaryId]
                    updated = true
                }
                if (updated) {
                    db.momentDao().updateMoment(moment.copy(linkedAnniversaryId = newLinkedAnniversaryId))
                }
            }
        }

        if (momentMap.isNotEmpty()) {
            db.assetDao().getAllAssets().first().filter { it.id in assetIds }.forEach { asset ->
                var updated = false
                var newLinkedMomentId = asset.linkedMomentId
                if (newLinkedMomentId != null && newLinkedMomentId in momentMap) {
                    newLinkedMomentId = momentMap[newLinkedMomentId]
                    updated = true
                }
                if (updated) {
                    db.assetDao().updateAsset(asset.copy(linkedMomentId = newLinkedMomentId))
                }
            }
            db.anniversaryDao().getAllAnniversaries().first().filter { it.id in anniversaryIds }.forEach { anniversary ->
                var updated = false
                var newLinkedMomentId = anniversary.linkedMomentId
                if (newLinkedMomentId != null && newLinkedMomentId in momentMap) {
                    newLinkedMomentId = momentMap[newLinkedMomentId]
                    updated = true
                }
                if (updated) {
                    db.anniversaryDao().updateAnniversary(anniversary.copy(linkedMomentId = newLinkedMomentId))
                }
            }
        }

        // 账单 → 周期模板。漏掉这条会让「合并后账单挂到别人家的模板上」，
        // 比断开关联更糟：模板会自动按它生成新账单。
        if (templateMap.isNotEmpty()) {
            db.billDao().getAllBills().first().filter { it.id in billIds }.forEach { bill ->
                val recurringId = bill.recurringId
                if (recurringId != null && recurringId in templateMap) {
                    db.billDao().updateBill(bill.copy(recurringId = templateMap[recurringId]))
                }
            }
        }

        // 分类 → 父分类。子分类挂在错误的父节点下，用户在分类管理里会看到一棵错树。
        if (categoryMap.isNotEmpty()) {
            db.categoryConfigDao().getAllCategories().first().filter { it.id in categoryIds }.forEach { category ->
                val parentId = category.parentId
                if (parentId != null && parentId in categoryMap) {
                    db.categoryConfigDao().update(category.copy(parentId = categoryMap[parentId]))
                }
            }
        }
    }

    private fun String?.toBoolean(): Boolean = this == "是" || this == "true"
}
